const state={view:'dashboard',auth:false,session:null,role:null,afterAuth:null,cache:{},directory:[],academic:[],achievements:[],alumni:[],activeAwardees:[],charts:{},chartTokens:{},attendanceOptions:null};
const titles={dashboard:'Dashboard',directory:'Direktori Awardee',alumni:'Tracking Alumni',academic:'Akademik',attendance:'Absensi Pembinaan',coaching:'Coaching & IDP',achievements:'Prestasi',mentoring:'Jurnal Pendampingan',profile:'Profil Fasilitator',datacenter:'Data Center',settings:'Pengaturan',system:'System Center'};
const secureViews=new Set(['attendance','coaching','mentoring','profile','datacenter','settings','system']);
const ttl=90000;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>Number.isFinite(Number(v))?Number(v):0;
function showLoader(on){document.getElementById('loader')?.classList.toggle('show',!!on)}
function toast(msg,type=''){const h=document.getElementById('toast-host');if(!h)return;const text=String(msg||'Terjadi kesalahan.');if(h.lastElementChild?.textContent===text)return;const d=document.createElement('div');d.className='toast '+type;d.textContent=text;h.appendChild(d);setTimeout(()=>d.remove(),3800)}
function toggleSidebar(on){document.getElementById('sidebar')?.classList.toggle('open',on);document.getElementById('mobile-backdrop')?.classList.toggle('open',on)}
function openModal(id){document.getElementById(id)?.classList.add('open');window.lucide?.createIcons?.()}
function closeModal(id){document.getElementById(id)?.classList.remove('open')}
function openLogin(){document.getElementById('pin-message')?.classList.add('hidden');const input=document.getElementById('pin-input');if(input)input.value='';openModal('login-modal');setTimeout(()=>input?.focus(),80)}
function requireAuth(action){if(state.auth)return typeof action==='function'?action():true;state.afterAuth=typeof action==='function'?action:null;openLogin();return false}
function closeLogin(){closeModal('login-modal')}
function closeDrawer(){document.getElementById('awardee-drawer')?.classList.remove('open')}
function cacheGet(k){const x=state.cache[k];return x&&Date.now()-x.t<ttl?x.v:null}
function cacheSet(k,v){state.cache[k]={t:Date.now(),v};return v}
async function api(name,params,force=false){const k=name+JSON.stringify(params||null);if(!force){const c=cacheGet(k);if(c!==null)return c}showLoader(true);try{const r=await etosAPI.call(name,params);if(!r||r.success===false)throw new Error(r?.error||'Permintaan gagal');return cacheSet(k,r.data)}finally{showLoader(false)}}
function destroyChart(id){if(state.charts[id]){state.charts[id].destroy();delete state.charts[id]}}
function chart(id,config){destroyChart(id);const el=document.getElementById(id);if(!el)return;const token=(state.chartTokens[id]||0)+1;state.chartTokens[id]=token;const draw=()=>{if(state.chartTokens[id]!==token)return;const current=document.getElementById(id);if(!current||current!==el||!window.Chart)return;destroyChart(id);state.charts[id]=new Chart(current,config)};if(window.Chart)return draw();if(typeof window.etosLoadChart==='function')window.etosLoadChart().then(draw).catch(err=>console.warn('[ETOS chart]',err?.message||err))}
function navActive(view){document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const title=document.getElementById('page-title');if(title)title.textContent=titles[view]||'ETOS Palu'}
async function goView(view){if(secureViews.has(view)&&!state.auth){state.afterAuth=()=>goView(view);openLogin();return}state.view=view;document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById('view-'+view)?.classList.add('active');navActive(view);toggleSidebar(false);await loadView(view)}
async function loadView(v,force=false){try{if(v==='dashboard')return loadDashboard(force);if(v==='directory')return loadDirectory(force);if(v==='alumni')return loadAlumni(force);if(v==='academic')return loadAcademic(force);if(v==='attendance')return loadAttendance(force);if(v==='coaching')return loadCoaching(force);if(v==='achievements')return loadAchievements(force);if(v==='mentoring')return loadMentoring(force);if(v==='profile')return loadProfile(force);if(v==='datacenter'&&typeof window.loadDataCenter==='function')return window.loadDataCenter(force);if(v==='settings'){let result;if(typeof window.loadSettings==='function')result=await window.loadSettings(force);if(typeof window.loadAccessControl==='function')await window.loadAccessControl(force);return result}if(v==='system'&&typeof window.loadSystemCenter==='function')return window.loadSystemCenter(force)}catch(e){toast(e?.message||String(e),'error')}}
function refreshCurrent(){state.cache={};return loadView(state.view,true)}
function applySession(s){state.auth=!!s;state.session=s||null;state.role=s?String(s.kind==='pin'?'superadmin':s.role||s.profile?.role||'viewer').toLowerCase():null}
async function checkAuth(){const {data}=await etosAuth.getSession();applySession(data?.session||null);updateAuthUI()}
function updateAuthUI(){const mode=document.getElementById('system-mode'),label=document.getElementById('top-auth-label'),text=document.getElementById('sidebar-auth-text'),btn=document.getElementById('sidebar-auth-btn');if(state.auth){if(mode){mode.textContent=state.session?.kind==='pin'?'Superadmin PIN':(state.role||'Operasional');mode.className='pill pill-green'}if(label)label.textContent='Keluar';if(text)text.textContent='Session operasional aktif. Modul pembinaan dan pengelolaan tersedia sesuai hak akses.';if(btn){btn.innerHTML='<i data-lucide="log-out" class="w-4 h-4"></i>Keluar';btn.onclick=logout}}else{if(mode){mode.textContent='Public';mode.className='pill pill-gray'}if(label)label.textContent='Akses';if(text)text.textContent='Mode baca publik aktif. Masuk untuk membuka modul pembinaan dan pengelolaan.';if(btn){btn.innerHTML='<i data-lucide="log-in" class="w-4 h-4"></i>Buka Akses';btn.onclick=openLogin}}const top=document.getElementById('top-auth-btn');if(top)top.onclick=state.auth?logout:openLogin;window.lucide?.createIcons?.()}
async function submitPin(e){e.preventDefault();const pin=document.getElementById('pin-input')?.value||'',btn=document.getElementById('pin-submit'),msg=document.getElementById('pin-message');if(btn){btn.disabled=true;btn.textContent='Memverifikasi...'}msg?.classList.add('hidden');try{const r=await etosAuth.signInPin(pin);applySession(r?.session||null);if(!state.auth)throw new Error('Session operasional gagal dibuat.');updateAuthUI();closeLogin();toast('Akses operasional dibuka.','success');const next=state.afterAuth;state.afterAuth=null;if(next)setTimeout(()=>{try{next()}catch(err){toast(err.message||String(err),'error')}},60);else await loadView(state.view,true)}catch(err){if(msg){msg.textContent=err.message||'PIN tidak sesuai.';msg.classList.remove('hidden')}}finally{if(btn){btn.disabled=false;btn.innerHTML='<i data-lucide="shield-check" class="w-4 h-4"></i>Buka Dashboard Operasional'}window.lucide?.createIcons?.()}}
async function logout(){await etosAuth.signOut();applySession(null);state.afterAuth=null;updateAuthUI();if(secureViews.has(state.view))await goView('dashboard');toast('Session operasional ditutup.','success')}
function normalizeAttendanceAgendaControl(){const old=document.getElementById('attendance-form-agenda');if(!old||old.tagName==='SELECT')return;const select=document.createElement('select');select.id='attendance-form-agenda';select.className='input select';select.required=true;select.setAttribute('aria-label','Agenda absensi');old.replaceWith(select)}
normalizeAttendanceAgendaControl();
