(function(){
'use strict';
const PORTFOLIOS={
 'AWD-0009':{legacy_id:'PRT-0NaN',cv_url:'https://docs.google.com/document/d/1MTMyouZjgWOVXZhzIVzIM657YBALhXT2zbCaT1Pgmnk/edit?usp=sharing',contribution:'Kerja di UIN',evidence_drive_url:null,linkedin_url:null},
 'AWD-0006':{legacy_id:'PRT-0001',cv_url:'https://drive.google.com/file/d/1fmYGXA3b58kdQuG1J_81w9MTOzXDbqF1/view?usp=drive_link',contribution:'Dalam Interview Kerja',evidence_drive_url:'https://drive.google.com/file/d/1sFYQkvpymstDeQIaQlsMTbyWpV95pqwG/view?usp=sharing',linkedin_url:null},
 'AWD-0001':{legacy_id:'PRT-0002',cv_url:'https://drive.google.com/file/d/1Br4kaKSN3vUDHd6-SYL9FLCdGzc_B3IX/view?usp=sharing',contribution:'Mecanhical Engineer PT. Korea Energy Indonesia',evidence_drive_url:null,linkedin_url:null},
 'AWD-0004':{legacy_id:'PRT-0003',cv_url:null,contribution:'Guru SDIT Bina Insan Palu',evidence_drive_url:null,linkedin_url:null}
};
const SYNC_KEY='etos-media-sync-v3';
function fileId(url){const s=String(url||'');const m=s.match(/\/d\/([A-Za-z0-9_-]+)/)||s.match(/[?&]id=([A-Za-z0-9_-]+)/);return m?m[1]:''}
function photoUrl(url){const s=String(url||'').trim();if(!s)return'';if(/supabase\.co\/storage\/v1\/object\//i.test(s))return s;const id=fileId(s);if(id&&/drive\.google\.com/i.test(s))return `https://drive.google.com/thumbnail?id=${encodeURIComponent(id)}&sz=w700`;return s}
window.etosMedia={fileId,photoUrl,portfolios:PORTFOLIOS};
function appState(){try{return typeof state!=='undefined'?state:null}catch{return null}}
function css(){if(document.getElementById('etos-polish-style'))return;const s=document.createElement('style');s.id='etos-polish-style';s.textContent=`
.brand-production,.brand-head{padding:22px 22px 17px!important;background:transparent!important}
.brand-production-card,.brand-logo-card{height:auto!important;width:100%!important;background:transparent!important;border:0!important;border-radius:0!important;box-shadow:none!important;padding:0!important;display:flex!important;align-items:center!important;justify-content:flex-start!important;overflow:visible!important}
.brand-production-card img,.brand-logo-card img{width:172px!important;max-width:82%!important;height:auto!important;max-height:none!important;object-fit:contain!important;filter:drop-shadow(0 7px 15px rgba(0,0,0,.10))}
.brand-production-meta,.brand-caption{display:block!important;margin:5px 0 0 1px!important;padding:0!important;text-transform:none!important;letter-spacing:normal!important;color:inherit!important}
.etos-location{display:flex;align-items:center;gap:9px;margin-top:4px;color:#fff;font:800 13px/1 Manrope,Inter,sans-serif;letter-spacing:.20em;text-transform:uppercase}
.etos-location:before{content:"";width:21px;height:2px;border-radius:99px;background:#5cc72a;box-shadow:0 0 0 3px rgba(92,199,42,.08)}
.etos-brand-sub{margin-top:7px;color:rgba(255,255,255,.36);font-size:8px;font-weight:700;letter-spacing:.16em;text-transform:uppercase}
#boot-logo{background:transparent!important;padding:0!important;width:170px!important;height:auto!important;border-radius:0!important}
#boot-logo img{width:170px!important;height:auto!important;filter:drop-shadow(0 8px 18px rgba(0,0,0,.10))}
.avatar img{width:100%!important;height:100%!important;object-fit:cover!important;display:block!important}
@media(max-width:960px){.brand-production-card img,.brand-logo-card img{width:158px!important}}
`;document.head.appendChild(s)}
function brand(){css();const side=document.getElementById('sidebar');if(!side||!side.firstElementChild)return;const head=side.firstElementChild;head.className='brand-production';head.innerHTML=`<div style="position:relative"><div class="brand-production-card"><img src="/brand-etos.svg?v=6" alt="ETOS ID"></div><div class="etos-location"><span>PALU</span></div><div class="etos-brand-sub">Awardee Development Intelligence</div><button class="mobile-only absolute right-0 top-0 w-9 h-9 rounded-xl bg-white/5 text-white items-center justify-center" onclick="toggleSidebar(false)"><i data-lucide="x" class="w-4 h-4"></i></button></div>`;if(window.lucide)lucide.createIcons()}
function normalize(v){return String(v||'').trim().toLowerCase()}
function photoForName(name){const st=appState();const list=st&&Array.isArray(st.directory)?st.directory:[];const n=normalize(name);const a=list.find(x=>normalize(x.nama||x.name)===n);return a?photoUrl(a.photo_url||a.foto):''}
function repairAvatars(root=document){if(!root.querySelectorAll)return;root.querySelectorAll('img').forEach(img=>{const src=img.getAttribute('src')||'';const fixed=photoUrl(src);if(fixed&&fixed!==src)img.src=fixed});root.querySelectorAll('.avatar').forEach(a=>{if(a.querySelector('img'))return;const host=a.closest('tr,button,.card,.card-flat,#drawer-content');if(!host)return;let name='';const candidates=host.querySelectorAll('.font-bold,.font-extrabold,.section-title');for(const el of candidates){const t=String(el.textContent||'').trim();if(t&&t.length>2&&t.length<90){name=t;break}}const p=photoForName(name);if(p)a.innerHTML=`<img src="${p}" alt="${String(name).replace(/"/g,'&quot;')}" loading="lazy" referrerpolicy="no-referrer">`})}
function wrapApi(){if(!window.etosAPI||window.etosAPI.__mediaWrapped)return;const original=window.etosAPI.call.bind(window.etosAPI);window.etosAPI.call=async function(name,params){const r=await original(name,params);if(r&&r.success!==false&&(name==='getAwardeeProfile'||name==='getAwardee360')){const id=String(typeof params==='string'?params:(params?.id_awardee||params?.id||r.data?.awardee?.legacy_id||'')).trim().toUpperCase();if(r.data&&!r.data.portfolio&&PORTFOLIOS[id])r.data.portfolio={...PORTFOLIOS[id]};if(r.data?.awardee){const u=r.data.awardee.photo_url||r.data.awardee.foto;if(u)r.data.awardee.photo_url=photoUrl(u)}}return r};window.etosAPI.__mediaWrapped=true}
function wrapDrawer(){const original=window.renderAwardeeDrawer;if(typeof original!=='function'||original.__mediaWrapped)return;const fn=function(data,id){if(data?.awardee){const u=data.awardee.photo_url||data.awardee.foto;if(u)data.awardee.photo_url=photoUrl(u);if(!data.portfolio&&PORTFOLIOS[String(id||data.awardee.legacy_id||'').toUpperCase()])data.portfolio={...PORTFOLIOS[String(id||data.awardee.legacy_id||'').toUpperCase()]}}const out=original(data,id);setTimeout(()=>{const drawer=document.getElementById('drawer-content');if(!drawer)return;const aw=data?.awardee||data?.profile||{};const u=photoUrl(aw.photo_url||aw.foto);const av=drawer.querySelector('.avatar');if(av&&u)av.innerHTML=`<img src="${u}" alt="${String(aw.name||aw.nama||'Awardee').replace(/"/g,'&quot;')}" loading="lazy" referrerpolicy="no-referrer">`;repairAvatars(drawer)},0);return out};fn.__mediaWrapped=true;window.renderAwardeeDrawer=fn}
async function autoSync(force=false){try{if(!window.etosAuth||(!force&&localStorage.getItem(SYNC_KEY)==='ok'))return;const x=await etosAuth.getSession();const session=x?.data?.session;if(!session?.access_token)return;const r=await fetch('/api/media-sync',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+session.access_token},body:JSON.stringify({action:'sync'})});const body=await r.json().catch(()=>({}));const failed=Number(body?.data?.failed||0);if(r.ok&&body.success&&failed===0){localStorage.setItem(SYNC_KEY,'ok');const st=appState();if(st)st.cache={};if(typeof toast==='function')toast(`Media Awardee tersinkron ke Supabase: ${body.data?.uploaded||0} file.`)}else if(r.ok&&body.success){console.warn('[ETOS media sync] partial',body.data);if(typeof toast==='function')toast(`Sinkron media berjalan; ${failed} item masih perlu retry.`,'warn')}else{console.warn('[ETOS media sync]',body.error||r.status);if(typeof toast==='function'&&force)toast(body.error||'Migrasi media belum berhasil.','warn')}}catch(e){console.warn('[ETOS media sync]',e);if(typeof toast==='function'&&force)toast('Migrasi media gagal dijalankan.','warn')}}
window.etosMigrateMedia=()=>autoSync(true);
function init(){brand();wrapApi();setTimeout(wrapDrawer,160);repairAvatars();const ob=new MutationObserver(m=>{for(const x of m){for(const n of x.addedNodes){if(n&&n.nodeType===1)repairAvatars(n)}}});ob.observe(document.body,{childList:true,subtree:true});if(window.etosAuth&&etosAuth.onChange)etosAuth.onChange((_event,session)=>{if(session?.access_token)setTimeout(()=>autoSync(true),500)});setTimeout(autoSync,1800);setTimeout(()=>{wrapDrawer();repairAvatars();autoSync()},5000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();