(function(){
'use strict';
const badge=(v,cls='pill-gray')=>`<span class="pill ${cls}">${esc(v??'—')}</span>`;
const safeArr=v=>Array.isArray(v)?v:[];
const section=(title,icon,body,count)=>`<details class="card mt-3" open><summary class="p-4 flex items-center gap-3 cursor-pointer list-none"><div class="w-8 h-8 rounded-xl bg-[#e8f1ed] text-[#0f6248] flex items-center justify-center"><i data-lucide="${icon}" class="w-4 h-4"></i></div><div class="font-extrabold text-[12px]">${esc(title)}</div>${count!==undefined?`<span class="pill pill-gray ml-auto">${count}</span>`:''}<i data-lucide="chevron-down" class="w-4 h-4 text-[#8a968f] ml-2"></i></summary><div class="px-4 pb-4">${body}</div></details>`;
const empty=msg=>`<div class="text-[11px] text-[#8a968f] py-3">${esc(msg)}</div>`;
function photoHtml(a){const u=a.photo_url||a.foto||a.foto_url||'';if(u)return`<div class="avatar !w-14 !h-14 !rounded-[18px] overflow-hidden bg-[#edf2ef]"><img src="${esc(u)}" alt="${esc(a.name||a.nama||'Awardee')}" class="w-full h-full object-cover" onerror="this.style.display='none';this.parentElement.textContent='${esc((a.name||a.nama||'A').charAt(0))}'"></div>`;return`<div class="avatar !w-14 !h-14 !rounded-[18px]">${esc((a.name||a.nama||'A').charAt(0))}</div>`}
function latestIpk(academic,sum){if(sum.latest_ipk!=null&&sum.latest_ipk!=='')return Number(sum.latest_ipk);const rows=safeArr(academic).filter(x=>x&&x.ipk!=null&&x.ipk!=='');if(!rows.length)return null;rows.sort((a,b)=>Number(a.semester||0)-Number(b.semester||0));return Number(rows[rows.length-1].ipk)}
function render360(data,id){const c=document.getElementById('drawer-content');if(!c)return;const a=data?.awardee||{},sum=data?.summary||{},academic=safeArr(data?.academic||data?.akademik),attendance=data?.attendance||{},coaching=safeArr(data?.coaching),ass=safeArr(data?.assessments),ach=safeArr(data?.achievements||data?.prestasi),org=safeArr(data?.organizations||data?.organisasi),refl=safeArr(data?.reflections),comp=safeArr(data?.competencies),cases=safeArr(data?.cases),anal=safeArr(data?.analyses),network=safeArr(data?.networking),spiritual=safeArr(data?.spiritual),portfolio=data?.portfolio,idp=data?.idp;
 const lipk=latestIpk(academic,sum);document.getElementById('drawer-title').textContent=a.name||a.nama||id;
 const top=`<div class="card p-5"><div class="flex items-start gap-4">${photoHtml(a)}<div class="min-w-0"><h3 class="section-title text-[22px]">${esc(a.name||a.nama||'Awardee')}</h3><div class="text-[11px] text-[#7d8a83] mt-1">${esc(a.jurusan||'—')} • ${esc(String(a.angkatan||'—').replace(/\.0$/,''))}</div><div class="text-[10px] text-[#8a968f] mt-1">${esc(a.kampus||'Universitas Tadulako')}</div><div class="mt-3">${badge(a.status,String(a.status).toLowerCase()==='aktif'?'pill-green':'pill-gray')}</div></div></div>${a.motto?`<div class="mt-5 pt-5 border-t border-[#edf1ef] text-[12px] leading-6 text-[#5f6d65]">“${esc(a.motto)}”</div>`:''}${a.profile_source?`<div class="text-[9px] text-[#97a39d] mt-2">Sumber profil: ${esc(a.profile_source)}</div>`:''}</div>`;
 const metrics=`<div class="grid grid-cols-2 sm:grid-cols-4 gap-2 mt-3"><div class="card-flat p-3"><div class="eyebrow">IPK terakhir</div><div class="metric-number text-[22px] font-extrabold mt-3">${lipk!=null&&Number.isFinite(lipk)?lipk.toFixed(2):'—'}</div></div><div class="card-flat p-3"><div class="eyebrow">Kehadiran</div><div class="metric-number text-[22px] font-extrabold mt-3">${sum.attendance_pct!=null?sum.attendance_pct+'%':'—'}</div></div><div class="card-flat p-3"><div class="eyebrow">Asesmen</div><div class="metric-number text-[22px] font-extrabold mt-3">${sum.assessment_completed||0}</div></div><div class="card-flat p-3"><div class="eyebrow">Open Case</div><div class="metric-number text-[22px] font-extrabold mt-3">${sum.open_cases||0}</div></div></div>`;
 const academicHtml=academic.length?`<div class="space-y-2">${academic.slice().sort((a,b)=>Number(b.semester||0)-Number(a.semester||0)).slice(0,8).map(x=>`<div class="card-flat p-3 flex justify-between gap-3"><span class="text-[11px] font-bold">Semester ${esc(x.semester)}</span><span class="font-extrabold">${x.ipk!=null?Number(x.ipk).toFixed(2):'—'}</span></div>`).join('')}</div>`:empty('Belum ada data akademik.');
 const attendanceHtml=attendance.total?`<div class="grid grid-cols-2 sm:grid-cols-5 gap-2">${[['Hadir',attendance.hadir],['Izin',attendance.izin],['Sakit',attendance.sakit],['Alpa',attendance.alpa],['Persentase',attendance.pct!=null?attendance.pct+'%':'—']].map(([l,v])=>`<div class="card-flat p-3"><div class="text-[9px] uppercase tracking-[.1em] text-[#88958e] font-bold">${l}</div><div class="font-extrabold mt-2">${v??0}</div></div>`).join('')}</div>`:empty('Belum ada transaksi absensi.');
 const idpPayload=idp?.payload||{};const idpHtml=idp?`<div class="card-flat p-4"><div class="flex justify-between gap-3"><div><div class="font-extrabold text-[12px]">${esc(idp.source_sheet_name||'Snapshot IDP')}</div><div class="text-[10px] text-[#849189] mt-1">${esc(idp.idp_external_sources?.source_name||'IDP Tim Pusat')}</div></div>${badge('Terhubung','pill-green')}</div><div class="text-[10px] text-[#849189] mt-3">Snapshot: ${esc(idp.captured_at||'—')} • ${Array.isArray(idpPayload.values)?idpPayload.values.length:0} baris</div></div>`:empty('Snapshot IDP pusat belum tersedia di Supabase.');
 const assessmentHtml=ass.length?ass.map(x=>`<div class="card-flat p-3 mb-2"><div class="flex justify-between gap-3"><b class="text-[11px]">${esc(x.assessment_code)}</b>${badge(x.status,String(x.status).toUpperCase()==='SELESAI'?'pill-green':'pill-gray')}</div><div class="text-[10px] text-[#849189] mt-2">${x.needs_checkin?'Perlu check-in fasilitator':'Tidak ada flag check-in'}</div></div>`).join(''):empty('Belum ada asesmen.');
 const achievementHtml=ach.length?ach.slice(0,12).map(x=>`<div class="card-flat p-3 mb-2"><div class="font-bold text-[11px]">${esc(x.achievement_name||x.prestasi)}</div><div class="text-[10px] text-[#849189] mt-1">${esc(x.year||'—')} • ${esc(x.level||x.tingkat||'—')} • ${esc(x.organizer||'')}</div></div>`).join(''):empty('Belum ada prestasi.');
 const orgHtml=org.length?org.map(x=>`<div class="card-flat p-3 mb-2"><div class="font-bold text-[11px]">${esc(x.organization_name||x.nama_organisasi)}</div><div class="text-[10px] text-[#849189] mt-1">${esc(x.position||x.jabatan||'—')} • ${esc(x.start_year||'')}–${esc(x.end_year_text||'')}</div></div>`).join(''):empty('Belum ada riwayat organisasi substantif.');
 const portfolioHtml=portfolio?`<div class="space-y-2 text-[11px]"><div class="card-flat p-3"><b>Kontribusi</b><div class="text-[#718078] mt-1">${esc(portfolio.contribution||'—')}</div></div>${portfolio.cv_url?`<a class="btn btn-soft" target="_blank" rel="noopener" href="${esc(portfolio.cv_url)}">Buka CV<i data-lucide="external-link" class="w-3.5 h-3.5"></i></a>`:''}${portfolio.evidence_drive_url?`<a class="btn btn-soft" target="_blank" rel="noopener" href="${esc(portfolio.evidence_drive_url)}">Evidence<i data-lucide="external-link" class="w-3.5 h-3.5"></i></a>`:''}${portfolio.linkedin_url?`<a class="btn btn-soft" target="_blank" rel="noopener" href="${esc(portfolio.linkedin_url)}">LinkedIn<i data-lucide="external-link" class="w-3.5 h-3.5"></i></a>`:''}</div>`:empty('Portfolio belum tersedia.');
 const reflectionHtml=refl.length?refl.slice(0,6).map(x=>`<div class="card-flat p-3 mb-2"><div class="text-[10px] text-[#849189]">${esc(x.agenda_name_snapshot||'Refleksi')} • ${esc(x.submitted_at||'')}</div><div class="text-[11px] leading-5 mt-2">${esc(x.awareness_finding||x.personal_reflection||x.memorable_fact||'—')}</div>${x.support_needed?`<div class="mt-2">${badge(x.support_needed,/belum membutuhkan/i.test(x.support_needed)?'pill-gray':'pill-gold')}</div>`:''}</div>`).join(''):empty('Belum ada refleksi kajian.');
 const compHtml=comp.length?comp.map(x=>`<div class="card-flat p-3 mb-2"><div class="flex justify-between"><b class="text-[11px]">${esc(x.competency)}</b>${badge('Level '+(x.level??'—'),Number(x.level)>=3?'pill-green':'pill-gray')}</div><div class="text-[10px] text-[#718078] mt-2">${esc(x.evidence||'—')}</div></div>`).join(''):empty('Evidence kompetensi belum ada.');
 const coachingHtml=coaching.length?coaching.slice(0,8).map(x=>`<div class="card-flat p-3 mb-2"><div class="text-[10px] text-[#849189]">${esc(x.session_date||'—')}</div><div class="font-bold text-[11px] mt-1">${esc(x.topic_problem||'Coaching')}</div><div class="text-[10px] text-[#718078] mt-2">RTL: ${esc(x.follow_up_plan||'Belum ditetapkan')}</div></div>`).join(''):empty('Belum ada coaching substantif.');
 const casesHtml=cases.length?cases.map(x=>`<div class="card-flat p-3 mb-2"><div class="flex justify-between gap-3"><b class="text-[11px]">${esc(x.title||'Case')}</b>${badge(x.priority||'—',String(x.priority).toLowerCase()==='tinggi'?'pill-gold':'pill-gray')}</div><div class="text-[10px] text-[#849189] mt-1">${esc(x.status||'—')} • deadline ${esc(x.deadline||'—')}</div></div>`).join(''):empty('Belum ada case pendampingan.');
 const extraHtml=(network.length||spiritual.length)?`<div class="space-y-2">${network.map(x=>`<div class="card-flat p-3"><b class="text-[11px]">${esc(x.partner_name)}</b><div class="text-[10px] text-[#849189] mt-1">${esc(x.institution||'')} • ${esc(x.contact_date||'')}</div><div class="text-[10px] mt-2">${esc(x.outcome||'')}</div></div>`).join('')}${spiritual.map(x=>`<div class="card-flat p-3"><b class="text-[11px]">${esc(x.month_label||'Spiritual')}</b><div class="text-[10px] text-[#718078] mt-2">Kajian: ${esc(x.kajian_attendance||'—')} • Tahsin: ${esc(x.tahsin_progress||'—')}</div></div>`).join('')}</div>`:empty('Networking dan rekam spiritual belum tersedia.');
 const analysisHtml=anal.length?anal.slice(0,5).map(x=>`<div class="card-flat p-3 mb-2"><div class="flex justify-between gap-3"><b class="text-[10px]">${esc(x.engine_version)}</b>${badge(x.result?.tingkat_perhatian||'—',x.result?.tingkat_perhatian==='Tinggi'?'pill-gold':'pill-gray')}</div><div class="text-[11px] leading-5 text-[#5f6d65] mt-2">${esc(x.result?.ringkasan||'Analisis tersimpan.')}</div><div class="text-[9px] text-[#8a968f] mt-2">${esc(x.analyzed_at||'')}</div></div>`).join(''):empty('Belum ada analisis otomatis.');
 c.innerHTML=top+metrics+section('Akademik','chart-no-axes-combined',academicHtml,academic.length)+section('Absensi','calendar-check-2',attendanceHtml,attendance.total||0)+section('Individual Development Plan','route',idpHtml,idp?1:0)+section('Asesmen','scan-heart',assessmentHtml,ass.length)+section('Prestasi','trophy',achievementHtml,ach.length)+section('Organisasi','briefcase-business',orgHtml,org.length)+section('Portfolio','folder-kanban',portfolioHtml,portfolio?1:0)+section('Refleksi Kajian','book-open-check',reflectionHtml,refl.length)+section('Kompetensi','badge-check',compHtml,comp.length)+section('Coaching','messages-square',coachingHtml,coaching.length)+section('Mentoring Case','radar',casesHtml,cases.length)+section('Networking & Spiritual','network',extraHtml,network.length+spiritual.length)+section('Riwayat Analisis','sparkles',analysisHtml,anal.length);
 if(state.auth){const action=document.createElement('div');action.className='grid sm:grid-cols-2 gap-2 mt-4';action.innerHTML=`<button class="analysis-action btn btn-primary" onclick="runRuleAnalysis('${esc(id)}')"><i data-lucide="sparkles" class="w-4 h-4"></i>Analisis Terbaru</button><button class="btn btn-soft" onclick="archiveAwardee('${esc(id)}','${esc(a.name||a.nama||'Awardee')}')"><i data-lucide="archive" class="w-4 h-4"></i>Arsipkan</button>`;c.appendChild(action)}
 lucide.createIcons();
}
function init(){if(typeof window.renderAwardeeDrawer!=='function'||window.__full360)return;window.renderAwardeeDrawer=function(data,id){render360(data,id)};window.__full360=true}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,80));else setTimeout(init,80);
})();