(function(){
'use strict';
const SYNC_KEY='etos-media-sync-audited-v1';
const PIN_VIEWS=new Set(['coaching','mentoring','profile','system','datacenter','settings']);
function fileId(url){const s=String(url||'');const m=s.match(/\/d\/([A-Za-z0-9_-]+)/)||s.match(/[?&]id=([A-Za-z0-9_-]+)/);return m?m[1]:''}
function photoUrl(url){const s=String(url||'').trim();if(!s)return'';if(/supabase\.co\/storage\/v1\/object\//i.test(s))return s;const id=fileId(s);if(id&&/drive\.google\.com/i.test(s))return `https://drive.google.com/thumbnail?id=${encodeURIComponent(id)}&sz=w700`;return s}
window.etosMedia={fileId,photoUrl};
function appState(){try{return typeof state!=='undefined'?state:null}catch{return null}}
function pinReady(){return appState()?.session?.kind==='pin'}
function requestPin(next){if(pinReady())return true;const st=appState();if(st)st.afterAuth=typeof next==='function'?next:null;if(typeof window.openPinAccess==='function')window.openPinAccess();else window.openLogin?.();return false}
function showAttendanceNav(){const b=document.querySelector('.nav-btn[data-view="attendance"]');if(b){b.style.display='';b.setAttribute('aria-hidden','false')}}
async function openAttendancePublic(force=false){const st=appState();if(!st)return;st.view='attendance';document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById('view-attendance')?.classList.add('active');document.querySelectorAll('.nav-btn[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view==='attendance'));const title=document.getElementById('page-title');if(title)title.textContent='Absensi Pembinaan';window.toggleSidebar?.(false);await window.loadView?.('attendance',force)}
function wrapPinAction(name){const base=window[name];if(typeof base!=='function'||base.__etosPinGuard)return;const guarded=function(){const args=arguments;if(!requestPin(()=>guarded.apply(this,args)))return;return base.apply(this,args)};guarded.__etosPinGuard=true;window[name]=guarded}
function wrapPinForm(name){const base=window[name];if(typeof base!=='function'||base.__etosPinGuard)return;const guarded=function(ev){ev?.preventDefault?.();const args=arguments;if(!requestPin(()=>guarded.apply(this,args)))return;return base.apply(this,args)};guarded.__etosPinGuard=true;window[name]=guarded}
function installAccessPolicy(){if(window.ETOS_PIN_POLICY_V361)return;window.ETOS_PIN_POLICY_V361=true;try{secureViews.delete('attendance')}catch(_){}
 const baseGo=window.goView;
 if(typeof baseGo==='function')window.goView=async function(view,force=false){view=String(view||'').trim();if(!view)return;if(view==='attendance')return openAttendancePublic(force);if(PIN_VIEWS.has(view)&&!pinReady()){requestPin(()=>window.goView(view,force));return}return baseGo.call(this,view,force)};
 const baseUpdate=window.updateAuthUI;
 if(typeof baseUpdate==='function')window.updateAuthUI=function(){const r=baseUpdate.apply(this,arguments);showAttendanceNav();return r};
 const baseLogout=window.logout;
 if(typeof baseLogout==='function')window.logout=async function(){const wasAttendance=appState()?.view==='attendance';const r=await baseLogout.apply(this,arguments);showAttendanceNav();if(wasAttendance)await openAttendancePublic(true);return r};
 for(const n of ['openAttendanceEntry','openAttendancePeriodSettings','deleteAttendancePeriodSetting','openAttendanceAgendaSettings','deleteAttendanceAgendaSetting'])wrapPinAction(n);
 for(const n of ['saveAttendance','saveAttendancePeriodForm','saveAttendanceAgendaForm'])wrapPinForm(n);
 showAttendanceNav();
}
function css(){if(document.getElementById('etos-polish-style'))return;const s=document.createElement('style');s.id='etos-polish-style';s.textContent=`
.brand-production,.brand-head{padding:22px 22px 17px!important;background:transparent!important}.brand-production-card,.brand-logo-card{height:auto!important;width:100%!important;background:transparent!important;border:0!important;border-radius:0!important;box-shadow:none!important;padding:0!important;display:flex!important;align-items:center!important;justify-content:flex-start!important;overflow:visible!important}.brand-production-card img,.brand-logo-card img{width:172px!important;max-width:82%!important;height:auto!important;max-height:none!important;object-fit:contain!important;filter:drop-shadow(0 7px 15px rgba(0,0,0,.10))}.etos-location{display:flex;align-items:center;gap:9px;margin-top:4px;color:#fff;font:800 13px/1 Manrope,Inter,sans-serif;letter-spacing:.20em;text-transform:uppercase}.etos-location:before{content:"";width:21px;height:2px;border-radius:99px;background:#5cc72a;box-shadow:0 0 0 3px rgba(92,199,42,.08)}.etos-brand-sub{margin-top:7px;color:rgba(255,255,255,.36);font-size:8px;font-weight:700;letter-spacing:.16em;text-transform:uppercase}.avatar img{width:100%!important;height:100%!important;object-fit:cover!important;display:block!important}@media(max-width:960px){.brand-production-card img,.brand-logo-card img{width:158px!important}}`;document.head.appendChild(s)}
function brand(){css();const side=document.getElementById('sidebar');if(!side||!side.firstElementChild)return;const head=side.firstElementChild;head.className='brand-production';head.innerHTML=`<div style="position:relative"><div class="brand-production-card"><img src="/brand-etos.svg?v=36" alt="ETOS ID"></div><div class="etos-location"><span>PALU</span></div><div class="etos-brand-sub">Awardee Development Intelligence</div><button class="mobile-only absolute right-0 top-0 w-9 h-9 rounded-xl bg-white/5 text-white items-center justify-center" onclick="toggleSidebar(false)"><i data-lucide="x" class="w-4 h-4"></i></button></div>`;if(window.lucide)lucide.createIcons()}
function normalize(v){return String(v||'').trim().toLowerCase()}
function photoForName(name){const st=appState();const list=st&&Array.isArray(st.directory)?st.directory:[];const n=normalize(name);const a=list.find(x=>normalize(x.nama||x.name)===n);return a?photoUrl(a.photo_url||a.foto):''}
function repairAvatars(root=document){if(!root.querySelectorAll)return;root.querySelectorAll('img').forEach(img=>{const src=img.getAttribute('src')||'';const fixed=photoUrl(src);if(fixed&&fixed!==src)img.src=fixed});root.querySelectorAll('.avatar').forEach(a=>{if(a.querySelector('img'))return;const host=a.closest('tr,button,.card,.card-flat,#drawer-content');if(!host)return;let name='';for(const el of host.querySelectorAll('.font-bold,.font-extrabold,.section-title')){const t=String(el.textContent||'').trim();if(t&&t.length>2&&t.length<90){name=t;break}}const p=photoForName(name);if(p)a.innerHTML=`<img src="${p}" alt="${String(name).replace(/"/g,'&quot;')}" loading="lazy" referrerpolicy="no-referrer">`})}
function wrapApi(){if(!window.etosAPI||window.etosAPI.__mediaSafe)return;const original=window.etosAPI.call.bind(window.etosAPI);window.etosAPI.call=async function(name,params){const r=await original(name,params);if(r?.data?.awardee){const u=r.data.awardee.photo_url||r.data.awardee.foto;if(u)r.data.awardee.photo_url=photoUrl(u)}return r};window.etosAPI.__mediaSafe=true}
function wrapDrawer(){const original=window.renderAwardeeDrawer;if(typeof original!=='function'||original.__mediaSafe)return;const fn=function(data,id){if(data?.awardee){const u=data.awardee.photo_url||data.awardee.foto;if(u)data.awardee.photo_url=photoUrl(u)}const out=original(data,id);setTimeout(()=>{const drawer=document.getElementById('drawer-content');if(!drawer)return;const aw=data?.awardee||data?.profile||{};const u=photoUrl(aw.photo_url||aw.foto);const av=drawer.querySelector('.avatar');if(av&&u)av.innerHTML=`<img src="${u}" alt="${String(aw.name||aw.nama||'Awardee').replace(/"/g,'&quot;')}" loading="lazy" referrerpolicy="no-referrer">`;repairAvatars(drawer)},0);return out};fn.__mediaSafe=true;window.renderAwardeeDrawer=fn}
window.etosMigrateMedia=async()=>{if(typeof toast==='function')toast('Migrasi media sedang memakai hasil audit sumber. Jalankan setelah akses operator aktif.','warn')};
function loadMentoringJournal(){if(window.ETOS_FACILITATOR_JOURNAL_READY||window.ETOS_MENTORING_JOURNAL_READY||document.querySelector('script[data-etos-mentoring-journal]'))return;const s=document.createElement('script');s.src='/app-mentoring-journal.js?v=36';s.async=true;s.dataset.etosMentoringJournal='1';s.onerror=()=>console.warn('[ETOS] Jurnal Pendampingan gagal dimuat.');document.head.appendChild(s)}
function init(){brand();wrapApi();installAccessPolicy();setTimeout(wrapDrawer,160);repairAvatars();loadMentoringJournal();const ob=new MutationObserver(m=>{showAttendanceNav();for(const x of m)for(const n of x.addedNodes)if(n&&n.nodeType===1)repairAvatars(n)});ob.observe(document.body,{childList:true,subtree:true});setTimeout(()=>{wrapDrawer();repairAvatars();showAttendanceNav()},1500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();