(function(){
'use strict';
const forms={
 awardee:{title:'Data Awardee',subtitle:'Identitas dan kontak utama',fields:[['nama','Nama lengkap','text',1],['kampus','Kampus','text',1],['jurusan','Jurusan / Program Studi','text',1],['angkatan','Angkatan','text',1],['status','Status','select:Aktif|Lulus|Arsip',1],['whatsapp','WhatsApp','tel',0],['email','Email','email',0],['motto','Motto / headline','textarea',0]]},
 academic:{title:'Rekam Akademik',subtitle:'Tambahkan IPK per semester',fields:[['id_awardee','Awardee','awardee',1],['semester','Semester','number',1],['ipk','IPK','number',1]]},
 achievement:{title:'Prestasi Awardee',subtitle:'Catat capaian dan pengakuan',fields:[['id_awardee','Awardee','awardee',1],['prestasi','Nama prestasi','text',1],['penyelenggara','Penyelenggara','text',0],['tahun','Tahun','number',0],['tingkat','Tingkat','select:Internal|Program Studi|Fakultas|Kampus|Daerah|Provinsi|Nasional|Internasional',0],['kategori','Kategori','text',0]]},
 organization:{title:'Riwayat Organisasi',subtitle:'Kepemimpinan dan pengalaman organisasi',fields:[['id_awardee','Awardee','awardee',1],['nama_organisasi','Nama organisasi','text',1],['jabatan','Jabatan','text',0],['tahun_mulai','Tahun mulai','number',0],['tahun_selesai','Tahun selesai','text',0],['tingkat','Tingkat','text',0]]},
 portfolio:{title:'Portfolio Awardee',subtitle:'Dokumen dan kontribusi profesional',fields:[['id_awardee','Awardee','awardee',1],['link_cv','Link CV','url',0],['kontribusi','Kontribusi / aktivitas utama','textarea',0],['link_gdrive','Link evidence / Google Drive','url',0],['linkedin_url','LinkedIn','url',0]]},
 period:{title:'Periode Pembinaan',subtitle:'Buat rentang periode untuk absensi, refleksi, dan monitoring',fields:[['nama','Nama periode','text',1],['mulai','Tanggal mulai','date',1],['selesai','Tanggal selesai','date',1],['status','Status','select:Aktif|Arsip',1]]},
 competency:{title:'Kompetensi Awardee',subtitle:'Evidence kompetensi yang dapat diverifikasi fasilitator',fields:[['id_awardee','Awardee','awardee',1],['kompetensi','Kompetensi','text',1],['level','Level','select:1|2|3|4',1],['evidence','Evidence','textarea',1],['status_verifikasi','Status verifikasi','select:Belum diverifikasi|Terverifikasi',1],['catatan','Catatan','textarea',0]]},
 networking:{title:'Networking Awardee',subtitle:'Catat relasi tokoh, mitra, dan outcome',fields:[['id_awardee','Awardee','awardee',1],['nama_mitra','Nama tokoh / mitra','text',1],['instansi','Instansi','text',0],['outcome','Outcome','textarea',0],['tanggal','Tanggal kontak','date',0]]},
 spiritual:{title:'Rekam Spiritual',subtitle:'Catatan pembinaan spiritual periodik',fields:[['id_awardee','Awardee','awardee',1],['bulan','Bulan / periode','text',1],['kehadiran_kajian','Kehadiran kajian','text',0],['progres_tahsin','Progres tahsin','textarea',0],['capaian_tilawah','Capaian tilawah','textarea',0]]},
 facilitator:{title:'Profil Fasilitator',subtitle:'Perbarui profil pendamping',fields:[['nama','Nama','text',1],['email','Email','email',0],['no_wa','WhatsApp','tel',0],['wilayah','Wilayah','text',0],['bio','Bio','textarea',0]]}
};
function sessionToken(){return etosSupabase?.auth?.getSession().then(r=>r.data?.session?.access_token||'')}
async function manageCall(fn,params){const t=await sessionToken();if(!t)throw new Error('Masukkan PIN akses terlebih dahulu.');const r=await fetch('/api/manage',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+t},body:JSON.stringify({function:fn,params})});const b=await r.json().catch(()=>({}));if(!r.ok||b.success===false)throw new Error(b.error||'Permintaan gagal.');return b.data}
function awardeeOptions(){const rows=(state.directory||[]).filter(x=>String(x.status||'').toLowerCase()!=='arsip');return '<option value="">Pilih Awardee</option>'+rows.map(x=>`<option value="${esc(x.id||x.legacy_id)}">${esc(x.nama||x.name)} — ${esc(String(x.angkatan||''))}</option>`).join('')}
function fieldHtml(f){const[name,label,type,req]=f,required=req?'required':'';if(type==='awardee')return`<label class="block sm:col-span-2"><span class="text-[10px] uppercase tracking-[.12em] font-bold text-[#7e8b84]">${label}</span><select name="${name}" class="input select mt-2" ${required}>${awardeeOptions()}</select></label>`;if(type.startsWith('select:'))return`<label class="block"><span class="text-[10px] uppercase tracking-[.12em] font-bold text-[#7e8b84]">${label}</span><select name="${name}" class="input select mt-2" ${required}>${type.slice(7).split('|').map(v=>`<option>${v}</option>`).join('')}</select></label>`;if(type==='textarea')return`<label class="block sm:col-span-2"><span class="text-[10px] uppercase tracking-[.12em] font-bold text-[#7e8b84]">${label}</span><textarea name="${name}" class="input min-h-[88px] mt-2" ${required}></textarea></label>`;return`<label class="block"><span class="text-[10px] uppercase tracking-[.12em] font-bold text-[#7e8b84]">${label}</span><input name="${name}" type="${type}" class="input mt-2" ${name==='ipk'?'min="0" max="4" step="0.01"':''} ${name==='semester'?'min="1" max="14"':''} ${required}></label>`}
function ensureModal(){if(document.getElementById('data-center-modal'))return;const d=document.createElement('div');d.id='data-center-modal';d.className='modal';d.innerHTML='<div class="modal-card p-6"><div class="flex items-start justify-between"><div><div class="eyebrow">Data Center</div><h2 id="dc-title" class="section-title text-[23px] mt-2">Tambah Data</h2><p id="dc-subtitle" class="text-[11px] text-[#7b8981] mt-2"></p></div><button class="btn btn-ghost !p-2" onclick="closeModal(\'data-center-modal\')"><i data-lucide="x" class="w-4 h-4"></i></button></div><form id="dc-form" class="grid sm:grid-cols-2 gap-3 mt-6"></form></div>';document.body.appendChild(d)}
function ensureHub(){if(document.getElementById('data-center-hub'))return;const d=document.createElement('div');d.id='data-center-hub';d.className='modal';const cards=[['awardee','user-round-plus','Awardee'],['academic','chart-no-axes-combined','Akademik'],['achievement','trophy','Prestasi'],['organization','briefcase-business','Organisasi'],['portfolio','folder-kanban','Portfolio'],['period','calendar-range','Periode'],['competency','badge-check','Kompetensi'],['networking','network','Networking'],['spiritual','book-heart','Spiritual'],['facilitator','user-round-cog','Fasilitator']];d.innerHTML=`<div class="modal-card p-6 max-w-[720px]"><div class="flex items-start justify-between"><div><div class="eyebrow">ETOS Data Center</div><h2 class="section-title text-[24px] mt-2">Kelola data dari satu tempat</h2><p class="text-[11px] text-[#7b8981] mt-2">Semua perubahan ditulis langsung ke Supabase dan mengikuti RLS.</p></div><button class="btn btn-ghost !p-2" onclick="closeModal('data-center-hub')"><i data-lucide="x" class="w-4 h-4"></i></button></div><div class="grid sm:grid-cols-2 lg:grid-cols-3 gap-3 mt-6">${cards.map(([t,i,l])=>`<button class="card-flat p-4 text-left hover:border-[#9bb9aa] transition" onclick="closeModal('data-center-hub');openDataModal('${t}')"><div class="w-9 h-9 rounded-xl bg-[#e8f1ed] text-[#0f6248] flex items-center justify-center"><i data-lucide="${i}" class="w-4 h-4"></i></div><div class="font-extrabold text-[12px] mt-4">${l}</div><div class="text-[9px] text-[#849189] mt-1">Tambah / perbarui data</div></button>`).join('')}</div></div>`;document.body.appendChild(d)}
window.openDataCenterHub=function(){if(!state.auth){openLogin();return}ensureHub();openModal('data-center-hub')};
window.openDataModal=async function(type){if(!state.auth){openLogin();return}if(!state.directory.length){try{await loadDirectory()}catch(_){}}ensureModal();const cfg=forms[type];if(!cfg)return;document.getElementById('dc-title').textContent=cfg.title;document.getElementById('dc-subtitle').textContent=cfg.subtitle;const f=document.getElementById('dc-form');f.dataset.type=type;f.innerHTML=cfg.fields.map(fieldHtml).join('')+'<div class="sm:col-span-2 pt-2 flex justify-end gap-2"><button type="button" class="btn btn-soft" onclick="closeModal(\'data-center-modal\')">Batal</button><button class="btn btn-green" type="submit"><i data-lucide="save" class="w-4 h-4"></i>Simpan</button></div>';f.onsubmit=saveDataCenter;openModal('data-center-modal')};
async function saveDataCenter(e){e.preventDefault();const f=e.currentTarget,type=f.dataset.type,data=Object.fromEntries(new FormData(f).entries());const map={awardee:'saveAwardee',academic:'saveAkademik',achievement:'savePrestasi',organization:'saveOrganisasi',portfolio:'savePortfolio',period:'savePeriode',competency:'saveKompetensi',networking:'saveNetworking',spiritual:'saveSpiritual',facilitator:'saveFasilitatorProfile'};const btn=f.querySelector('button[type=submit]');btn.disabled=true;btn.textContent='Menyimpan...';try{await manageCall(map[type],data);closeModal('data-center-modal');state.cache={};toast('Data berhasil disimpan.');if(type==='awardee')await loadDirectory(true);else if(type==='academic')await loadAcademic(true);else if(type==='achievement')await loadAchievements(true);else if(type==='facilitator')await loadProfile(true);else if(type==='period'&&state.view==='attendance')await loadAttendance(true);else await loadView(state.view,true)}catch(err){toast(err.message,'error')}finally{btn.disabled=false;btn.innerHTML='<i data-lucide="save" class="w-4 h-4"></i>Simpan';lucide.createIcons()}}
window.runRuleAnalysis=async function(id){if(!state.auth){openLogin();return}try{showLoader(true);const r=await manageCall('runRuleAnalysis',{id_awardee:id});toast('Analisis perkembangan diperbarui.');state.cache={};await openAwardee(id);return r}catch(e){toast(e.message,'error')}finally{showLoader(false)}};
window.archiveAwardee=async function(id,name){if(!state.auth){openLogin();return}if(!confirm(`Arsipkan ${name||id}? Data historis tetap disimpan.`))return;try{await manageCall('archiveAwardee',{id_awardee:id});state.cache={};closeDrawer();toast('Awardee diarsipkan.');await loadDirectory(true)}catch(e){toast(e.message,'error')}};
function actionButton(label,icon,type){const b=document.createElement('button');b.className='btn btn-green';b.innerHTML=`<i data-lucide="${icon}" class="w-4 h-4"></i>${label}`;b.onclick=()=>openDataModal(type);return b}
function injectActions(){
 const configs=[['view-directory','Tambah Awardee','user-plus','awardee'],['view-academic','Tambah Akademik','plus','academic'],['view-achievements','Tambah Prestasi','plus','achievement']];configs.forEach(([id,label,icon,type])=>{const view=document.getElementById(id);if(!view||view.querySelector('.dc-action'))return;const header=view.firstElementChild;if(!header)return;const b=actionButton(label,icon,type);b.classList.add('dc-action');header.appendChild(b)});
 const profile=document.getElementById('view-profile');if(profile&&!profile.querySelector('.dc-action')){const b=actionButton('Edit Profil','pencil','facilitator');b.classList.add('dc-action','mb-4');profile.insertBefore(b,profile.children[1])}
 const coach=document.getElementById('view-coaching');if(coach&&!document.getElementById('more-data-actions')){const box=document.createElement('div');box.id='more-data-actions';box.className='flex flex-wrap gap-2 mb-4';box.innerHTML='<button class="btn btn-soft" onclick="openDataModal(\'organization\')"><i data-lucide="briefcase-business" class="w-4 h-4"></i>Organisasi</button><button class="btn btn-soft" onclick="openDataModal(\'portfolio\')"><i data-lucide="folder-kanban" class="w-4 h-4"></i>Portfolio</button><button class="btn btn-soft" onclick="openDataModal(\'competency\')"><i data-lucide="badge-check" class="w-4 h-4"></i>Kompetensi</button>';coach.insertBefore(box,coach.children[1])}
 const nav=document.querySelector('#sidebar nav');if(nav&&!document.getElementById('data-center-nav')){const b=document.createElement('button');b.id='data-center-nav';b.className='nav-btn mt-1';b.innerHTML='<i data-lucide="database" class="w-4 h-4"></i>Data Center<span class="secure-lock">PIN</span><span class="nav-dot"></span>';b.onclick=openDataCenterHub;nav.appendChild(b)}
 lucide.createIcons();
}
function wrapDrawer(){if(typeof window.renderAwardeeDrawer!=='function'||window.__drawerWrapped)return;const base=window.renderAwardeeDrawer;window.renderAwardeeDrawer=function(data,id){base(data,id);const c=document.getElementById('drawer-content'),a=data?.awardee||data?.profile||data||{};if(c&&!c.querySelector('.analysis-action')){const action=document.createElement('div');action.className='grid sm:grid-cols-2 gap-2 mt-4';action.innerHTML=`<button class="analysis-action btn btn-primary" onclick="runRuleAnalysis('${esc(id)}')"><i data-lucide="sparkles" class="w-4 h-4"></i>Analisis Terbaru</button><button class="btn btn-soft" onclick="archiveAwardee('${esc(id)}','${esc(a.name||a.nama||'Awardee')}')"><i data-lucide="archive" class="w-4 h-4"></i>Arsipkan</button>`;c.appendChild(action);lucide.createIcons()}};window.__drawerWrapped=true}
function init(){ensureModal();ensureHub();injectActions();wrapDrawer()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,30));else setTimeout(init,30);
})();
