(function(){
'use strict';
if(window.ETOS_SYSTEM_CENTER_V36)return;window.ETOS_SYSTEM_CENTER_V36=true;
let healthData=null,auditRows=[];
const e=v=>typeof esc==='function'?esc(v):String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function inject(){try{titles.system='System Center';secureViews.add('system')}catch(_){}const nav=document.querySelector('#sidebar nav');if(nav&&!nav.querySelector('[data-view="system"]')){const b=document.createElement('button');b.id='system-nav';b.className='nav-btn';b.dataset.view='system';b.innerHTML='<i data-lucide="database-zap" class="w-4 h-4"></i>System Center<span class="nav-dot"></span>';b.addEventListener('click',()=>goView('system'));nav.appendChild(b)}const host=document.querySelector('.content-pad');if(host&&!document.getElementById('view-system')){const s=document.createElement('section');s.id='view-system';s.className='view';s.innerHTML=`<div class="flex flex-col lg:flex-row lg:items-end justify-between gap-4 mb-5"><div><div class="eyebrow">Supabase Operations</div><h2 class="section-title text-[28px] mt-2">System Center</h2><p class="text-[11px] text-[#7b8981] mt-2 max-w-[760px]">Health, audit, dan backup aplikasi. Database utama hanya Supabase PostgreSQL; IDP live adalah satu-satunya sumber eksternal.</p></div><div class="flex gap-2"><button class="btn btn-soft" onclick="loadSystemCenter(true)"><i data-lucide="refresh-cw" class="w-4 h-4"></i>Perbarui</button><button class="btn btn-primary" onclick="exportSupabaseBackup()"><i data-lucide="download" class="w-4 h-4"></i>Backup JSON</button></div></div><div id="system-kpis" class="grid grid-cols-2 xl:grid-cols-4 gap-3 mb-4"></div><div class="grid xl:grid-cols-[1.2fr_.8fr] gap-4"><section class="card overflow-hidden"><div class="p-5 border-b border-[#e8eeea]"><div class="eyebrow">Database Inventory</div><h3 class="section-title text-[19px] mt-2">Supabase PostgreSQL</h3></div><div id="system-table-counts" class="p-5 grid sm:grid-cols-2 gap-2"><div class="empty sm:col-span-2">Memuat health…</div></div></section><section class="card overflow-hidden"><div class="p-5 border-b border-[#e8eeea]"><div class="eyebrow">Governance</div><h3 class="section-title text-[19px] mt-2">Audit terbaru</h3></div><div id="system-audit" class="divide-y divide-[#edf1ef]"><div class="empty">Memuat audit…</div></div></section></div><div class="card p-5 mt-4"><div class="flex items-center gap-2"><i data-lucide="shield-check" class="w-4 h-4 text-[#0f6248]"></i><b class="text-[11px]">Kebijakan sumber data v36</b></div><div class="text-[10px] text-[#68776f] leading-5 mt-2">Tidak ada sinkronisasi spreadsheet pada login, refresh, System Center, atau proses background aplikasi. Data non-IDP berasal dari Supabase. IDP hanya dibaca live melalui integrasi read-only.</div></div>`;host.appendChild(s)}window.lucide?.createIcons?.()}
async function call(fn,retry=1){try{const r=await fetch('/api/system',{method:'POST',credentials:'include',headers:{'Content-Type':'application/json'},body:JSON.stringify({function:fn})}),b=await r.json().catch(()=>({}));if(!r.ok||b.success===false)throw new Error(b.error||'System Center gagal memproses permintaan.');return b.data}catch(err){if(retry>0&&/batas waktu|timeout|abort|network|fetch/i.test(String(err?.message||err))){await wait(280);return call(fn,retry-1)}throw err}}
function kpi(label,value,note,tone=''){return`<div class="card-flat p-4"><div class="text-[9px] uppercase tracking-[.12em] font-bold text-[#87948d]">${e(label)}</div><div class="metric-number text-[24px] font-extrabold mt-2 ${tone}">${e(value)}</div><div class="text-[9px] text-[#929d97] mt-1">${e(note)}</div></div>`}
function render(){inject();const counts=healthData?.counts||{},available=Object.values(counts).filter(v=>v!==null).length,total=Object.values(counts).filter(v=>Number.isFinite(Number(v))).reduce((a,b)=>a+Number(b),0),unavailable=healthData?.unavailable||[];document.getElementById('system-kpis').innerHTML=[kpi('Database','Supabase','sumber utama','text-[#0f6248]'),kpi('Tabel Terbaca',available,Object.keys(counts).length+' tabel dipantau'),kpi('Total Record',total,'lintas tabel operasional'),kpi('Health',unavailable.length?'Perlu cek':'Healthy',unavailable.length?unavailable.length+' tabel tidak terbaca':'semua tabel terbaca',unavailable.length?'text-[#9a6b24]':'text-[#0f6248]')].join('');document.getElementById('system-table-counts').innerHTML=Object.keys(counts).length?Object.entries(counts).map(([name,n])=>`<div class="card-flat p-3 flex items-center justify-between gap-3"><span class="text-[10px] font-semibold">${e(name.replaceAll('_',' '))}</span><span class="pill ${n===null?'pill-gold':'pill-gray'}">${n===null?'N/A':e(n)}</span></div>`).join(''):'<div class="empty sm:col-span-2">Belum ada data health.</div>';document.getElementById('system-audit').innerHTML=auditRows.length?auditRows.slice(0,12).map(x=>`<div class="p-4"><div class="text-[10px] font-bold">${e(x.action||x.event||x.table_name||'Aktivitas')}</div><div class="text-[9px] text-[#87948d] mt-1">${e(x.created_at||x.at||'')}</div></div>`).join(''):'<div class="empty">Belum ada audit log.</div>';window.lucide?.createIcons?.()}
window.loadSystemCenter=async function(){inject();try{window.showLoader?.(true);const [h,a]=await Promise.all([call('health'),call('audit').catch(()=>[])]);healthData=h;auditRows=Array.isArray(a)?a:[];render();return h}catch(err){const box=document.getElementById('system-table-counts');if(box)box.innerHTML=`<div class="empty sm:col-span-2">Data belum berhasil dimuat. Klik Perbarui untuk mencoba lagi.</div>`;window.toast?.('System Center belum berhasil memuat data. Silakan coba Perbarui.','warn')}finally{window.showLoader?.(false)}};
window.exportSupabaseBackup=async function(){try{window.showLoader?.(true);const data=await call('backup'),blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='etos-id-palu-supabase-backup-'+new Date().toISOString().slice(0,10)+'.json';document.body.appendChild(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},0);window.toast?.('Backup Supabase berhasil dibuat.','success')}catch(err){window.toast?.(err.message||String(err),'error')}finally{window.showLoader?.(false)}};
inject();
})();
