async function openCoachingModal(){const s=document.getElementById('coaching-awardee');if(s)s.innerHTML=state.activeAwardees.map(x=>`<option value="${esc(x.id||x.legacy_id)}">${esc(x.nama||x.name)}</option>`).join('');const d=document.getElementById('coaching-date');if(d)d.value=new Date().toISOString().slice(0,10);const f=document.getElementById('coaching-facilitator');if(f){f.innerHTML='<option value="">Memuat fasilitator…</option>';try{const r=await etosAPI.call('getCoachingFacilitators',{});if(r?.success===false)throw new Error(r.error);const rows=Array.isArray(r?.data)?r.data:[];f.innerHTML='<option value="">Pilih fasilitator</option>'+rows.map(x=>`<option value="${esc(x.id)}">${esc(x.name)}</option>`).join('')}catch(_){f.innerHTML='<option value="">Fasilitator belum tersedia</option>'}}openModal('coaching-modal')}
async function saveCoaching(e){e.preventDefault();const btn=e.currentTarget?.querySelector('button[type=submit]')||document.getElementById('coaching-save-btn');if(btn?.dataset.etosBusy==='1')return;const p={id_awardee:document.getElementById('coaching-awardee').value,facilitator_id:document.getElementById('coaching-facilitator').value,tgl:document.getElementById('coaching-date').value,topik:document.getElementById('coaching-topic').value,solusi:document.getElementById('coaching-solution').value,rtl:document.getElementById('coaching-rtl').value};window.etosButtonBusy?.(btn,true,'Menyimpan Coaching');try{const r=await etosAPI.call('saveCoaching',p);if(r.success===false)throw new Error(r.error);closeModal('coaching-modal');state.cache={};toast('Coaching berhasil disimpan.','success');setTimeout(()=>loadCoaching(true).catch(()=>{}),40)}catch(err){toast(err.message,'error')}finally{window.etosButtonBusy?.(btn,false)}}
async function loadMentoring(force=false){const rows=await api('getMentoringCases',{},force);const arr=Array.isArray(rows)?rows:(rows?.items||[]),open=arr.filter(x=>!['selesai','closed','done'].includes(String(x.status||'').toLowerCase())),high=open.filter(x=>String(x.prioritas||x.priority||'').toLowerCase()==='tinggi'),over=open.filter(x=>x.deadline&&new Date(x.deadline)<new Date());const k=document.getElementById('mentoring-kpis');if(k)k.innerHTML=[['Total Case',arr.length],['Case Terbuka',open.length],['Prioritas Tinggi',high.length],['Lewat Deadline',over.length]].map(([l,v])=>`<div class="card-flat p-4"><div class="text-[9px] uppercase tracking-[.12em] font-bold text-[#88958e]">${l}</div><div class="metric-number text-[25px] font-extrabold mt-2">${v}</div></div>`).join('');const b=document.getElementById('mentoring-body');if(b)b.innerHTML=arr.length?arr.map(x=>`<tr><td class="font-semibold">${esc(x.nama||'—')}</td><td>${esc(x.judul||x.title||'—')}</td><td>${esc(x.kategori||x.category||'—')}</td><td><span class="pill ${String(x.prioritas||x.priority).toLowerCase()==='tinggi'?'pill-gold':'pill-gray'}">${esc(x.prioritas||x.priority||'—')}</span></td><td>${esc(x.deadline||'—')}</td><td>${esc(x.status||'—')}</td></tr>`).join(''):'<tr><td colspan="6" class="empty">Belum ada case pendampingan.</td></tr>'}
function openCaseModal(){if(!state.activeAwardees.length)state.activeAwardees=state.directory.filter(x=>String(x.status||'').toLowerCase()!=='lulus');document.getElementById('case-awardee').innerHTML=state.activeAwardees.map(x=>`<option value="${esc(x.id||x.legacy_id)}">${esc(x.nama||x.name)}</option>`).join('');openModal('case-modal')}
async function saveCase(e){e.preventDefault();const btn=e.currentTarget?.querySelector('button[type=submit]');if(btn?.dataset.etosBusy==='1')return;const p={id_awardee:document.getElementById('case-awardee').value,judul:document.getElementById('case-title').value,kategori:document.getElementById('case-category').value,prioritas:document.getElementById('case-priority').value,aksi:document.getElementById('case-action').value,deadline:document.getElementById('case-deadline').value,status:'Open'};window.etosButtonBusy?.(btn,true,'Menyimpan Case');try{const r=await etosAPI.call('saveMentoringCase',p);if(r.success===false)throw new Error(r.error);closeModal('case-modal');state.cache={};toast('Case pendampingan berhasil dibuat.','success');setTimeout(()=>loadMentoring(true).catch(()=>{}),40)}catch(err){toast(err.message,'error')}finally{window.etosButtonBusy?.(btn,false)}}
async function loadProfile(force=false){const p=await api('getFasilitatorProfile',{},force);document.getElementById('profile-name').textContent=p?.name||p?.nama||p?.full_name||'Fasilitator ETOS Palu';document.getElementById('profile-region').textContent=p?.wilayah||p?.region||'Palu';document.getElementById('profile-bio').textContent=p?.bio||'Profil fasilitator belum dilengkapi.';document.getElementById('profile-email').textContent=p?.email||'—';document.getElementById('profile-wa').textContent=p?.whatsapp||p?.no_wa||'—'}
function _a360date(v){if(!v)return'—';try{return new Intl.DateTimeFormat('id-ID',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(String(v).slice(0,10)+'T00:00:00+08:00'))}catch{return String(v)}}
function _a360status(v){const s=String(v||'').toLowerCase();return '<span class="pill '+(s==='hadir'||s==='aktif'?'pill-green':s==='sakit'||s==='izin'?'pill-gold':'pill-gray')+'">'+esc(v||'—')+'</span>'}
function _a360empty(t='Belum ada data.'){return '<div class="empty">'+esc(t)+'</div>'}
function _a360section(title,note,body,open=false){return '<details class="card mt-4 group" '+(open?'open':'')+'><summary class="p-5 cursor-pointer list-none flex items-center justify-between gap-3"><div><div class="eyebrow">Awardee 360</div><div class="section-title text-[16px] mt-1">'+esc(title)+'</div>'+(note?'<div class="text-[9px] text-[#87948d] mt-1">'+esc(note)+'</div>':'')+'</div><i data-lucide="chevron-down" class="w-4 h-4 text-[#819087]"></i></summary><div class="px-5 pb-5 border-t border-[#edf1ef] pt-4">'+body+'</div></details>'}
async function openAwardee(id){
 if(!id)return;
 if(state?.session?.kind!=='pin'){
   state.afterAuth=()=>openAwardee(id);
   if(typeof window.openPinAccess==='function')window.openPinAccess();else openLogin();
   return;
 }
 document.getElementById('drawer-title').textContent='Memuat Awardee 360°...';
 document.getElementById('drawer-content').innerHTML='<div class="empty">Menggabungkan profil, absensi, coaching, refleksi, IDP, dan data perkembangan…</div>';
 document.getElementById('awardee-drawer').classList.add('open');
 try{
   const r=await etosAPI.call('getAwardee360',{id_awardee:id});
   if(!r||r.success===false)throw new Error(r?.error||'Awardee 360° belum dapat dibuka.');
   renderAwardeeDrawer(r.data,id);
 }catch(e){
   document.getElementById('drawer-content').innerHTML='<div class="empty">'+esc(e.message||String(e))+'</div>';
 }
}
function renderAwardeeDrawer(data,id){
 const a=data?.awardee||{},contact=data?.contact||{},academic=data?.academic||[],achievements=data?.achievements||[],organizations=data?.organizations||[],coaching=data?.coaching||[],cases=data?.cases||[],reflections=data?.reflections||[],journal=data?.journal||[],attendance=data?.attendance||{},idp=data?.idp||{},analysis=data?.automaticAnalysis||{},summary=data?.summary||{};
 document.getElementById('drawer-title').textContent=(a.name||a.nama||id)+' · 360°';
 const photo=a.photo_url||a.foto||'';
 const avatar=photo?'<img src="'+esc(photo)+'" class="w-full h-full object-cover" onerror="this.remove()">':esc((a.name||a.nama||'A').charAt(0));
 const profile=`<div class="card p-5">
   <div class="flex items-start gap-4">
    <div class="avatar !w-16 !h-16 !rounded-[20px] overflow-hidden">${avatar}</div>
    <div class="min-w-0 flex-1"><h3 class="section-title text-[22px]">${esc(a.name||a.nama||'Awardee')}</h3>
     <div class="text-[10px] text-[#7d8a83] mt-1">${esc(a.legacy_id||'—')} · Angkatan ${esc(String(a.angkatan||'—').replace(/\.0$/,''))}</div>
     <div class="text-[11px] font-semibold mt-2">${esc(a.kampus||'—')}</div><div class="text-[10px] text-[#849189] mt-1">${esc(a.jurusan||'—')}</div>
     <div class="mt-3">${_a360status(a.status)}</div>
    </div>
   </div>
   <div class="grid sm:grid-cols-2 gap-2 mt-5 pt-4 border-t border-[#edf1ef] text-[10px]">
    <div><span class="text-[#87948d]">WhatsApp</span><div class="font-bold mt-1">${esc(contact.whatsapp||'—')}</div></div>
    <div><span class="text-[#87948d]">Email</span><div class="font-bold mt-1 break-all">${esc(contact.email||'—')}</div></div>
   </div>
  </div>`;
 const kpis=`<div class="grid grid-cols-2 md:grid-cols-3 gap-3 mt-4">
  <div class="card-flat p-4"><div class="eyebrow">IPK terbaru</div><div class="metric-number text-[23px] font-extrabold mt-2">${summary.latest_ipk!=null?Number(summary.latest_ipk).toFixed(2):'—'}</div><div class="text-[9px] text-[#87948d] mt-1">${esc(summary.latest_ipk_label||'Belum ada catatan')}</div></div>
  <div class="card-flat p-4"><div class="eyebrow">Kehadiran</div><div class="metric-number text-[23px] font-extrabold mt-2">${summary.attendance_pct!=null?summary.attendance_pct+'%':'—'}</div><div class="text-[9px] text-[#87948d] mt-1">${Number(attendance.total||0)} catatan</div></div>
  <div class="card-flat p-4"><div class="eyebrow">Coaching</div><div class="metric-number text-[23px] font-extrabold mt-2">${Number(summary.coaching_count||0)}</div><div class="text-[9px] text-[#87948d] mt-1">sesi tercatat</div></div>
  <div class="card-flat p-4"><div class="eyebrow">Refleksi</div><div class="metric-number text-[23px] font-extrabold mt-2">${Number(summary.reflection_count||0)}</div><div class="text-[9px] text-[#87948d] mt-1">jawaban tersimpan</div></div>
  <div class="card-flat p-4"><div class="eyebrow">Prestasi</div><div class="metric-number text-[23px] font-extrabold mt-2">${Number(summary.achievement_count||0)}</div><div class="text-[9px] text-[#87948d] mt-1">capaian</div></div>
  <div class="card-flat p-4"><div class="eyebrow">IDP</div><div class="metric-number text-[18px] font-extrabold mt-2">${summary.idp_connected?'Terhubung':'Belum'}</div><div class="text-[9px] text-[#87948d] mt-1">workbook aktif</div></div>
 </div>`;
 const notes=(analysis.notes||[]).map(x=>'<div class="card-flat p-3"><div class="text-[10px] font-extrabold">'+esc(x.area||'Temuan')+'</div><div class="text-[10px] leading-5 text-[#65736b] mt-1">'+esc(x.summary||'')+'</div><div class="text-[8px] text-[#98a29d] mt-2">Sumber: '+esc(x.source||'data tersimpan')+'</div></div>').join('');
 const themes=(analysis.reflectionThemes||[]).map(x=>'<span class="pill pill-gray">'+esc(x.name)+' · '+Number(x.count||0)+'</span>').join('');
 const analysisHtml=`<div class="card p-5 mt-4"><div class="flex items-start justify-between gap-3"><div><div class="eyebrow">Analisis Otomatis 360°</div><h3 class="section-title text-[18px] mt-2">Ringkasan lintas data</h3></div><span class="pill pill-green">PIN</span></div><p class="text-[9px] leading-5 text-[#7d8a83] mt-3">${esc(analysis.disclaimer||'Ringkasan otomatis berdasarkan data tersimpan.')}</p><div class="space-y-2 mt-4">${notes||_a360empty('Belum cukup data untuk membuat ringkasan.')}</div>${themes?'<div class="flex flex-wrap gap-2 mt-4">'+themes+'</div>':''}</div>`;
 const attendanceRows=(attendance.records||[]).map(r=>{const s=Array.isArray(r.attendance_sessions)?r.attendance_sessions[0]:r.attendance_sessions||{};return '<tr><td>'+esc(_a360date(s.activity_date))+'</td><td class="font-semibold">'+esc(s.activity_name||'—')+'</td><td>'+_a360status(r.status)+'</td><td>'+esc(r.notes||'—')+'</td></tr>'}).join('');
 const attendanceHtml=`<div class="grid grid-cols-4 gap-2 mb-4 text-center"><div class="card-flat p-3"><b>${Number(attendance.hadir||0)}</b><div class="text-[8px] text-[#829087] mt-1">Hadir</div></div><div class="card-flat p-3"><b>${Number(attendance.izin||0)}</b><div class="text-[8px] text-[#829087] mt-1">Izin</div></div><div class="card-flat p-3"><b>${Number(attendance.sakit||0)}</b><div class="text-[8px] text-[#829087] mt-1">Sakit</div></div><div class="card-flat p-3"><b>${Number(attendance.alpa||0)}</b><div class="text-[8px] text-[#829087] mt-1">Alpa</div></div></div>${attendanceRows?'<div class="table-wrap"><table class="data-table"><thead><tr><th>Tanggal</th><th>Agenda</th><th>Status</th><th>Catatan</th></tr></thead><tbody>'+attendanceRows+'</tbody></table></div>':_a360empty('Belum ada riwayat absensi.')}`;
 const academicHtml=academic.length?'<div class="table-wrap"><table class="data-table"><thead><tr><th>Semester</th><th>IPK</th><th>Catatan</th></tr></thead><tbody>'+academic.map(x=>'<tr><td>'+esc(x.semester_label||x.semester||'—')+'</td><td class="font-extrabold">'+(x.ipk!=null?Number(x.ipk).toFixed(2):'—')+'</td><td>'+esc(x.notes||x.source_note||'—')+'</td></tr>').join('')+'</tbody></table></div>':_a360empty('Belum ada data akademik.');
 const coachingHtml=coaching.length?coaching.map(x=>'<div class="card-flat p-4 mb-2"><div class="flex justify-between gap-3"><b class="text-[11px]">'+esc(x.topic_problem||'Coaching')+'</b><span class="text-[9px] text-[#87948d]">'+esc(_a360date(x.session_date))+'</span></div><div class="text-[9px] uppercase tracking-[.1em] text-[#8a968f] mt-3">Solusi</div><div class="text-[10px] leading-5 mt-1">'+esc(x.solution||'—')+'</div><div class="text-[9px] uppercase tracking-[.1em] text-[#8a968f] mt-3">Tindak lanjut</div><div class="text-[10px] leading-5 mt-1">'+esc(x.follow_up_plan||'—')+'</div></div>').join(''):_a360empty('Belum ada catatan coaching.');
 const reflectionHtml=reflections.length?reflections.map(x=>'<details class="card-flat p-4 mb-2"><summary class="cursor-pointer list-none"><div class="flex justify-between gap-3"><b class="text-[11px]">'+esc(x.agenda_name_snapshot||'Refleksi')+'</b><span class="text-[9px] text-[#87948d]">'+esc(_a360date(x.agenda_date||x.submitted_at))+'</span></div><div class="text-[10px] text-[#65736b] mt-2">'+esc(x.awareness_finding||x.personal_reflection||'Klik untuk melihat jawaban')+'</div></summary><div class="mt-4 pt-4 border-t border-[#e6ece8] space-y-3 text-[10px] leading-5"><div><b>Fakta:</b> '+esc(x.event_facts||'—')+'</div><div><b>Membekas:</b> '+esc(x.memorable_fact||'—')+'</div><div><b>Perasaan:</b> '+esc(x.feeling||'—')+'</div><div><b>Temuan:</b> '+esc(x.awareness_finding||'—')+'</div><div><b>Rencana:</b> '+esc(x.action_plan||'—')+'</div><div><b>Dukungan:</b> '+esc(x.support_needed||'—')+'</div></div></details>').join(''):_a360empty('Belum ada refleksi.');
 const idpHtml=idp?.connected?`<div class="card-flat p-4"><div class="flex items-center justify-between gap-3"><div><b class="text-[11px]">${esc(idp.sheetName||a.name||'IDP')}</b><div class="text-[9px] text-[#87948d] mt-1">${Number(idp.summary?.filledRows||0)} baris · ${Number(idp.summary?.filledCells||0)} sel terisi</div></div><span class="pill pill-green">Terhubung</span></div>${typeof window.openRestoredIDPDetail==='function'?'<button class="btn btn-primary w-full mt-4" onclick="openRestoredIDPDetail(decodeURIComponent(\''+encodeURIComponent(String(a.name||''))+'\'))">Lihat Detail IDP</button>':''}</div>`:_a360empty(idp?.error||'IDP belum terhubung.');
 const achievementHtml=(achievements.length||organizations.length)?'<div class="space-y-3">'+(achievements.length?'<div><div class="eyebrow mb-2">Prestasi</div>'+achievements.map(x=>'<div class="card-flat p-3 mb-2"><b class="text-[10px]">'+esc(x.achievement_name||'—')+'</b><div class="text-[9px] text-[#87948d] mt-1">'+esc(x.level||'—')+' · '+esc(x.year||'—')+'</div></div>').join('')+'</div>':'')+(organizations.length?'<div><div class="eyebrow mb-2 mt-4">Organisasi</div>'+organizations.map(x=>'<div class="card-flat p-3 mb-2"><b class="text-[10px]">'+esc(x.organization_name||'—')+'</b><div class="text-[9px] text-[#87948d] mt-1">'+esc(x.position||'—')+' · '+esc(x.start_year||'—')+'</div></div>').join('')+'</div>':'')+'</div>':_a360empty('Belum ada prestasi atau organisasi.');
 const mentoringHtml=(cases.length||journal.length)?'<div class="space-y-3">'+cases.map(x=>'<div class="card-flat p-3"><div class="flex justify-between gap-2"><b class="text-[10px]">'+esc(x.title||x.category||'Case')+'</b>'+_a360status(x.status)+'</div><div class="text-[9px] text-[#65736b] mt-2">'+esc(x.action_plan||x.outcome||'—')+'</div></div>').join('')+journal.map(x=>'<div class="card-flat p-3"><div class="flex justify-between gap-2"><b class="text-[10px]">'+esc(x.entry_type||'Jurnal')+'</b><span class="text-[9px] text-[#87948d]">'+esc(_a360date(x.observed_at))+'</span></div><div class="text-[9px] leading-5 text-[#65736b] mt-2">'+esc(x.note||'—')+'</div><div class="text-[9px] mt-2"><b>Tindak lanjut:</b> '+esc(x.follow_up||'—')+'</div></div>').join('')+'</div>':_a360empty('Belum ada case atau jurnal pendampingan.');
 document.getElementById('drawer-content').innerHTML=profile+kpis+analysisHtml+
   _a360section('Absensi','Riwayat per agenda',attendanceHtml,true)+
   _a360section('Akademik','Semester dan perkembangan IPK',academicHtml)+
   _a360section('Coaching','Topik, solusi, dan tindak lanjut',coachingHtml)+
   _a360section('Refleksi','Jawaban refleksi per kajian',reflectionHtml)+
   _a360section('IDP','Workbook IDP unggahan aktif',idpHtml)+
   _a360section('Prestasi & Organisasi','Capaian dan pengalaman',achievementHtml)+
   _a360section('Pendampingan & Jurnal','Case dan catatan fasilitator',mentoringHtml);
 window.lucide?.createIcons?.();
}
async function initReflectionIfNeeded(){const m=location.pathname.match(/^\/r\/([A-Za-z0-9]+)/);if(!m)return false;document.getElementById('main-app').style.display='none';document.body.innerHTML=`<div class="min-h-screen bg-[#edf1ef] p-4 md:p-8 flex items-center justify-center"><div class="card w-full max-w-2xl p-6 md:p-8"><div class="eyebrow">Kajian Reflection</div><h1 class="section-title text-[28px] mt-2">Refleksi Setelah Kajian</h1><div id="public-reflection" class="mt-6"><div class="empty">Memuat formulir...</div></div></div></div>`;try{const r=await etosAPI.call('getPublicKajianReflectionForm',m[1]);if(r.success===false)throw new Error(r.error);const f=r.data;document.getElementById('public-reflection').innerHTML=`<div class="card-flat p-4 mb-4"><div class="text-[10px] text-[#849189] uppercase tracking-[.12em] font-bold">Agenda</div><div class="font-extrabold mt-2">${esc(f.agenda)}</div><div class="text-[11px] text-[#849189] mt-1">${esc(f.tanggal)}</div></div><form onsubmit="verifyReflection(event,'${esc(m[1])}')" class="space-y-3"><select id="rf-awardee" class="input select" required><option value="">Pilih nama</option>${(f.awardees||[]).map(a=>`<option value="${esc(a.id)}">${esc(a.nama)} — ${esc(a.angkatan)}</option>`).join('')}</select><input id="rf-wa" class="input" inputmode="numeric" maxlength="4" placeholder="4 digit terakhir WhatsApp" required><button class="btn btn-green w-full" type="submit">Lanjutkan Refleksi</button></form>`}catch(e){document.getElementById('public-reflection').innerHTML='<div class="empty">'+esc(e.message)+'</div>'}return true}
async function verifyReflection(e,token){e.preventDefault();const p={formToken:token,awardeeId:document.getElementById('rf-awardee').value,waLast4:document.getElementById('rf-wa').value};const r=await etosAPI.call('verifyKajianReflectionParticipant',p);if(r.success===false){toast(r.error,'error');return}const x=r.data,old=x.existing||{};document.getElementById('public-reflection').innerHTML=`<div class="mb-5"><div class="text-[11px] text-[#849189]">Refleksi untuk</div><div class="font-extrabold mt-1">${esc(x.participant.nama)}</div></div><form class="space-y-3" onsubmit="submitReflection(event,'${esc(token)}','${esc(x.participant.id)}')"><textarea id="rf-event" class="input min-h-[90px]" required placeholder="Apa fakta yang benar-benar terjadi?">${esc(old.faktaKejadian||'')}</textarea><textarea id="rf-fact" class="input min-h-[90px]" required placeholder="Bagian apa yang paling membekas?">${esc(old.fakta||'')}</textarea><textarea id="rf-feel" class="input min-h-[90px]" required placeholder="Apa perasaan yang muncul?">${esc(old.perasaan||'')}</textarea><textarea id="rf-aware" class="input min-h-[90px]" required placeholder="Apa hal baru yang kamu sadari?">${esc(old.temuan||'')}</textarea><textarea id="rf-plan" class="input min-h-[90px]" required placeholder="Langkah apa yang ingin dilakukan?">${esc(old.rencanaTindakan||'')}</textarea><select id="rf-support" class="input select" required><option>Untuk sekarang, saya belum membutuhkan dukungan</option><option>Saya perlu sesekali diingatkan</option><option>Saya perlu teman untuk saling mendampingi</option><option>Saya ingin berdiskusi dengan fasilitator</option><option>Saya membutuhkan penjelasan atau materi tambahan</option><option>Dukungan lainnya</option></select><textarea id="rf-support-note" class="input min-h-[70px]" placeholder="Catatan dukungan (opsional)">${esc(old.catatanDukungan||'')}</textarea><button class="btn btn-green w-full" type="submit">Simpan Refleksi</button></form>`}
async function submitReflection(e,token,id){e.preventDefault();const p={formToken:token,awardeeId:id,waLast4:document.getElementById('rf-wa')?.value||'',faktaKejadian:document.getElementById('rf-event').value,fakta:document.getElementById('rf-fact').value,perasaan:document.getElementById('rf-feel').value,temuan:document.getElementById('rf-aware').value,rencanaTindakan:document.getElementById('rf-plan').value,dukungan:document.getElementById('rf-support').value,catatanDukungan:document.getElementById('rf-support-note').value};const r=await etosAPI.call('submitKajianReflection',p);if(r.success===false){toast(r.error,'error');return}document.getElementById('public-reflection').innerHTML='<div class="py-12 text-center"><div class="w-14 h-14 rounded-full bg-etos-50 text-etos-600 mx-auto flex items-center justify-center"><i data-lucide="check" class="w-6 h-6"></i></div><h2 class="section-title text-[22px] mt-5">Refleksi tersimpan</h2><p class="text-[12px] text-[#718078] mt-2">Terima kasih sudah mengisi dengan jujur dan reflektif.</p></div>';window.lucide?.createIcons?.()}
async function boot(){if(await initReflectionIfNeeded())return;document.querySelectorAll('.nav-btn').forEach(b=>b.addEventListener('click',()=>goView(b.dataset.view)));await checkAuth();await loadDashboard();window.lucide?.createIcons?.();if(etosAuth.onChange)etosAuth.onChange((_event,session)=>{state.auth=!!session;window.updateAuthUI?.()})}
document.addEventListener('DOMContentLoaded',boot);
