(function(){'use strict';
function hidePinLabels(root=document){if(!root.querySelectorAll)return;root.querySelectorAll('.secure-lock').forEach(x=>x.remove());const side=document.getElementById('sidebar');if(side)side.querySelectorAll('span,small').forEach(x=>{if(String(x.textContent||'').trim().toUpperCase()==='PIN')x.remove()})}
async function sessionToken(){try{const x=await window.etosAuth?.getSession?.();return x?.data?.session?.access_token||''}catch{return''}}
function wrapApi(){if(!window.etosAPI||window.etosAPI.__accessWrapped)return;const original=window.etosAPI.call.bind(window.etosAPI);window.etosAPI.call=async function(name,params){if(name==='getAbsensiList'){const r=await fetch('/api/public-attendance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({params:params||null})});return r.json().catch(()=>({success:false,error:'Absensi tidak dapat dibaca.'}))}if(name==='getIDPOverview'||name==='getIDPDetail'){const token=await sessionToken();if(!token)return{success:false,error:'Akses operasional diperlukan untuk IDP.'};const r=await fetch('/api/idp-live',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify({function:name,params:params||null})});return r.json().catch(()=>({success:false,error:'Koneksi IDP pusat gagal.'}))}return original(name,params)};window.etosAPI.__accessWrapped=true}
async function runAttendanceCutover(){if(sessionStorage.getItem('etos-attendance-cutover-v1')==='ok')return;const token=await sessionToken();if(!token)return;try{const r=await fetch('/api/attendance-cutover',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:'{}'});const b=await r.json().catch(()=>({}));if(r.ok&&b.success)sessionStorage.setItem('etos-attendance-cutover-v1','ok');else console.warn('[ETOS attendance cutover]',b.detail||b.error||'belum selesai')}catch(e){console.warn('[ETOS attendance cutover]',e)}}
function protectAttendance(){const original=window.openAttendanceEntry;if(typeof original!=='function'||original.__etosProtected)return;const fn=function(){const args=arguments,ctx=this;const open=async()=>{await runAttendanceCutover();return original.apply(ctx,args)};return window.requireAuth?requireAuth(open):(window.state?.auth?open():openLogin())};fn.__etosProtected=true;window.openAttendanceEntry=fn}
function script(id,src){if(document.getElementById(id))return;const s=document.createElement('script');s.id=id;s.src=src;s.async=false;s.onerror=()=>console.warn('[ETOS] Modul gagal dimuat:',src);document.body.appendChild(s)}
function loadSettingsModules(){script('etos-data-center-script','/app-data-center.js?v=2');script('etos-migration-script','/app-migration-action.js?v=2')}
function init(){hidePinLabels();wrapApi();protectAttendance();loadSettingsModules();const o=new MutationObserver(()=>{hidePinLabels();protectAttendance()});o.observe(document.body,{childList:true,subtree:true});setTimeout(()=>{wrapApi();protectAttendance();hidePinLabels()},900)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
