(function(){'use strict';
function hidePinLabels(root=document){if(!root.querySelectorAll)return;root.querySelectorAll('.secure-lock').forEach(x=>x.remove());const side=document.getElementById('sidebar');if(side)side.querySelectorAll('span,small').forEach(x=>{if(String(x.textContent||'').trim().toUpperCase()==='PIN')x.remove()})}
async function sessionToken(){try{const x=await window.etosAuth?.getSession?.();return x?.data?.session?.access_token||''}catch{return''}}
function wrapApi(){if(!window.etosAPI||window.etosAPI.__accessWrapped)return;const original=window.etosAPI.call.bind(window.etosAPI);window.etosAPI.call=async function(name,params){if(name==='getAbsensiList'){const r=await fetch('/api/public-attendance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({params:params||null})});return r.json().catch(()=>({success:false,error:'Absensi tidak dapat dibaca.'}))}if(name==='getIDPOverview'||name==='getIDPDetail'){const token=await sessionToken();if(!token)return{success:false,error:'Akses operasional diperlukan untuk IDP.'};const r=await fetch('/api/idp-live',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:JSON.stringify({function:name,params:params||null})});return r.json().catch(()=>({success:false,error:'Koneksi IDP pusat gagal.'}))}return original(name,params)};window.etosAPI.__accessWrapped=true}
async function runAcademicCutover(){const key='etos-academic-2023-cutover-v1';if(localStorage.getItem(key)==='ok')return;try{const r=await fetch('/api/sync-academic-2023-cutover',{cache:'no-store'});const b=await r.json().catch(()=>({}));if(r.ok&&b.success&&Number(b.verified)===9){localStorage.setItem(key,'ok');try{if(window.state)state.cache={}}catch(_){}console.info('[ETOS academic cutover] 9/9 verified')}else console.warn('[ETOS academic cutover]',b.error||'belum selesai')}catch(e){console.warn('[ETOS academic cutover]',e)}}
async function runAttendanceCutover(){if(sessionStorage.getItem('etos-attendance-cutover-v1')==='ok')return;const token=await sessionToken();if(!token)return;try{const r=await fetch('/api/attendance-cutover',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},body:'{}'});const b=await r.json().catch(()=>({}));if(r.ok&&b.success){sessionStorage.setItem('etos-attendance-cutover-v1','ok')}else console.warn('[ETOS attendance cutover]',b.detail||b.error||'belum selesai')}catch(e){console.warn('[ETOS attendance cutover]',e)}}
function protectAttendance(){const original=window.openAttendanceEntry;if(typeof original!=='function'||original.__etosProtected)return;const fn=function(){const args=arguments,ctx=this;const open=async()=>{await runAttendanceCutover();return original.apply(ctx,args)};return window.requireAuth?requireAuth(open):(window.state?.auth?open():openLogin())};fn.__etosProtected=true;window.openAttendanceEntry=fn}
function loadSettingsModule(){if(document.getElementById('etos-data-center-script'))return;const s=document.createElement('script');s.id='etos-data-center-script';s.src='/app-data-center.js?v=1';s.async=false;s.onerror=()=>console.warn('[ETOS] Data Center module gagal dimuat.');document.body.appendChild(s)}
function init(){hidePinLabels();wrapApi();protectAttendance();loadSettingsModule();setTimeout(runAcademicCutover,900);const o=new MutationObserver(()=>{hidePinLabels();protectAttendance()});o.observe(document.body,{childList:true,subtree:true});setTimeout(()=>{wrapApi();protectAttendance();hidePinLabels();runAcademicCutover()},1200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
