const crypto=require('crypto');
const session=require('./server-session');
function out(res,status,body){res.status(status).setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(body))}
function cred(req){return session.credential(req)}
async function q(path,c,options={}){const r=await fetch(session.PROJECT_URL+path,{...options,headers:{...session.dbHeaders(c),...(options.headers||{})}});const text=await r.text();let body=null;try{body=text?JSON.parse(text):null}catch{body=text}if(!r.ok)throw new Error(body?.message||body?.error||body?.hint||`Supabase ${r.status}`);return body}
async function awardeeId(ref,c){const v=String(ref||'').trim();if(!v)return null;const rows=/^AWD-/i.test(v)?await q(`/rest/v1/awardees?legacy_id=eq.${encodeURIComponent(v.toUpperCase())}&select=id`,c):await q(`/rest/v1/awardees?id=eq.${encodeURIComponent(v)}&select=id`,c);return rows?.[0]?.id||null}
async function nextLegacy(table,prefix,c){const rows=await q(`/rest/v1/${table}?select=legacy_id&legacy_id=like.${encodeURIComponent(prefix+'-*')}`,c);let n=0;(rows||[]).forEach(x=>{const m=String(x.legacy_id||'').match(/(\d+)$/);if(m)n=Math.max(n,Number(m[1]))});return`${prefix}-${String(n+1).padStart(4,'0')}`}
async function insert(table,data,c,select='*'){return q(`/rest/v1/${table}?select=${encodeURIComponent(select)}`,c,{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify([data])})}
async function patch(table,filter,data,c,select='*'){return q(`/rest/v1/${table}?${filter}&select=${encodeURIComponent(select)}`,c,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(data)})}
const clean=v=>String(v??'').trim();
module.exports=async function(req,res){if(req.method!=='POST')return out(res,405,{success:false,error:'Method not allowed'});try{const c=cred(req);if(!c?.server)return out(res,401,{success:false,error:'Session PIN operasional diperlukan.'});const fn=String(req.body?.function||''),p=req.body?.params||{};
 if(fn==='saveAwardee'){const legacy=clean(p.id_awardee||p.legacy_id).toUpperCase(),d={name:clean(p.nama||p.name),kampus:clean(p.kampus)||null,jurusan:clean(p.jurusan)||null,angkatan:clean(p.angkatan)||null,status:clean(p.status)||'Aktif',motto:clean(p.motto)||null,photo_url:clean(p.photo_url||p.foto)||null};if(!d.name)throw new Error('Nama Awardee wajib diisi.');let row;if(legacy)row=(await patch('awardees',`legacy_id=eq.${encodeURIComponent(legacy)}`,d,c))?.[0];else{d.legacy_id=await nextLegacy('awardees','AWD',c);row=(await insert('awardees',d,c))?.[0]}if(!row)throw new Error('Awardee gagal disimpan.');if(clean(p.whatsapp)||clean(p.email))await q('/rest/v1/awardee_contacts?on_conflict=awardee_id',c,{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify([{awardee_id:row.id,whatsapp:clean(p.whatsapp)||null,email:clean(p.email)||null}])});return out(res,200,{success:true,data:{id:row.legacy_id||row.id}})}
 if(fn==='saveAkademik'){const aid=await awardeeId(p.id_awardee,c);if(!aid)throw new Error('Awardee tidak ditemukan.');const semRaw=clean(p.semester),recap=semRaw==='1-8',sem=recap?8:Number(semRaw),ipk=p.ipk===''||p.ipk==null?null:Number(String(p.ipk).replace(',','.'));if(!recap&&!(sem>=1&&sem<=14))throw new Error('Semester harus 1–14 atau 1-8 untuk rekap.');if(ipk!=null&&!(ipk>=0&&ipk<=4))throw new Error('IPK harus 0–4.');const ex=await q(`/rest/v1/academic_records?awardee_id=eq.${aid}&semester=eq.${sem}&select=id,legacy_id`,c);const d={semester:sem,ipk,semester_label:recap?'1-8':String(sem),record_type:recap?'rekap_1_8':'semester',is_summary:recap,semester_from:recap?1:sem,semester_to:recap?8:sem};let row;if(ex?.[0])row=(await patch('academic_records',`id=eq.${ex[0].id}`,d,c))?.[0];else{d.legacy_id=await nextLegacy('academic_records','AKD',c);d.awardee_id=aid;row=(await insert('academic_records',d,c))?.[0]}return out(res,200,{success:true,data:row})}
 if(fn==='savePrestasi'){const aid=await awardeeId(p.id_awardee,c);if(!aid)throw new Error('Awardee tidak ditemukan.');const row=(await insert('achievements',{legacy_id:await nextLegacy('achievements','PRS',c),awardee_id:aid,achievement_name:clean(p.prestasi),organizer:clean(p.penyelenggara)||null,year:p.tahun?Number(p.tahun):null,level:clean(p.tingkat)||null,category:clean(p.kategori)||null},c))?.[0];return out(res,200,{success:true,data:row})}
 if(fn==='saveOrganisasi'){const aid=await awardeeId(p.id_awardee,c);if(!aid)throw new Error('Awardee tidak ditemukan.');const row=(await insert('organization_records',{legacy_id:await nextLegacy('organization_records','ORG',c),awardee_id:aid,organization_name:clean(p.nama_organisasi),position:clean(p.jabatan)||null,start_year:p.tahun_mulai?Number(p.tahun_mulai):null,end_year_text:clean(p.tahun_selesai)||null,level:clean(p.tingkat)||null},c))?.[0];return out(res,200,{success:true,data:row})}
 if(fn==='savePortfolio'){const aid=await awardeeId(p.id_awardee,c);if(!aid)throw new Error('Awardee tidak ditemukan.');const ex=await q(`/rest/v1/portfolios?awardee_id=eq.${aid}&select=id,legacy_id`,c),d={cv_url:clean(p.link_cv)||null,contribution:clean(p.kontribusi)||null,evidence_drive_url:clean(p.link_gdrive)||null,linkedin_url:clean(p.linkedin_url)||null};let row;if(ex?.[0])row=(await patch('portfolios',`id=eq.${ex[0].id}`,d,c))?.[0];else{d.legacy_id=await nextLegacy('portfolios','PRT',c);d.awardee_id=aid;row=(await insert('portfolios',d,c))?.[0]}return out(res,200,{success:true,data:row})}
 if(fn==='savePeriode'){if(clean(p.status).toLowerCase()==='aktif')try{await patch('development_periods',`status=ilike.${encodeURIComponent('Aktif')}`,{status:'Arsip'},c)}catch{}const row=(await insert('development_periods',{legacy_id:await nextLegacy('development_periods','PRD',c),name:clean(p.nama),start_date:p.mulai||null,end_date:p.selesai||null,status:clean(p.status)||'Aktif'},c))?.[0];return out(res,200,{success:true,data:row})}
 if(fn==='saveKompetensi'){const aid=await awardeeId(p.id_awardee,c);if(!aid)throw new Error('Awardee tidak ditemukan.');const row=(await insert('competencies',{legacy_id:await nextLegacy('competencies','KMP',c),awardee_id:aid,competency:clean(p.kompetensi),level:Number(p.level),evidence:clean(p.evidence),source:'manual',verification_status:clean(p.status_verifikasi)||'Belum diverifikasi',assessed_by:'ETOS ID Palu Administrator',assessed_at:new Date().toISOString().slice(0,10),notes:clean(p.catatan)||null},c))?.[0];return out(res,200,{success:true,data:row})}
 if(fn==='saveNetworking'){const aid=await awardeeId(p.id_awardee,c);if(!aid)throw new Error('Awardee tidak ditemukan.');const row=(await insert('networking_records',{legacy_id:await nextLegacy('networking_records','NET',c),awardee_id:aid,partner_name:clean(p.nama_mitra),institution:clean(p.instansi)||null,outcome:clean(p.outcome)||null,contact_date:p.tanggal||null},c))?.[0];return out(res,200,{success:true,data:row})}
 if(fn==='saveSpiritual'){const aid=await awardeeId(p.id_awardee,c);if(!aid)throw new Error('Awardee tidak ditemukan.');const row=(await insert('spiritual_records',{legacy_id:await nextLegacy('spiritual_records','SPR',c),awardee_id:aid,month_label:clean(p.bulan),kajian_attendance:clean(p.kehadiran_kajian)||null,tahsin_progress:clean(p.progres_tahsin)||null,tilawah_achievement:clean(p.capaian_tilawah)||null},c))?.[0];return out(res,200,{success:true,data:row})}
 if(fn==='saveFasilitatorProfile'){const rows=await q('/rest/v1/facilitators?select=id&limit=1',c),d={name:clean(p.nama||p.name)||'Fasilitator ETOS',email:clean(p.email)||null,whatsapp:clean(p.no_wa||p.whatsapp)||null,wilayah:clean(p.wilayah)||'Palu',bio:clean(p.bio)||null};const row=rows?.[0]?(await patch('facilitators',`id=eq.${rows[0].id}`,d,c))?.[0]:(await insert('facilitators',d,c))?.[0];return out(res,200,{success:true,data:row})}
 if(fn==='archiveAwardee'){const legacy=clean(p.id_awardee).toUpperCase();const row=(await patch('awardees',`legacy_id=eq.${encodeURIComponent(legacy)}`,{status:'Arsip'},c))?.[0];return out(res,200,{success:true,data:row})}
 if(fn==='runRuleAnalysis'){const aid=await awardeeId(p.id_awardee,c);if(!aid)throw new Error('Awardee tidak ditemukan.');const [a,ak,att,co,ass,ach,org]=await Promise.all([q(`/rest/v1/awardees?id=eq.${aid}&select=legacy_id,name`,c),q(`/rest/v1/academic_records?awardee_id=eq.${aid}&select=semester,ipk,legacy_id&order=semester.desc.nullslast`,c),q(`/rest/v1/attendance_records?awardee_id=eq.${aid}&select=status`,c),q(`/rest/v1/coaching_sessions?awardee_id=eq.${aid}&select=session_date&order=session_date.desc.nullslast&limit=1`,c),q(`/rest/v1/assessments?awardee_id=eq.${aid}&select=needs_checkin,status`,c),q(`/rest/v1/achievements?awardee_id=eq.${aid}&select=id`,c),q(`/rest/v1/organization_records?awardee_id=eq.${aid}&select=id`,c)]);const latest=ak?.[0]||null,prev=ak?.[1]||null,delta=latest&&prev&&latest.ipk!=null&&prev.ipk!=null?Number((Number(latest.ipk)-Number(prev.ipk)).toFixed(2)):null,total=att?.length||0,hadir=(att||[]).filter(x=>x.status==='Hadir').length,pct=total?Math.round(hadir/total*100):null,attention=[];if(latest?.ipk!=null&&Number(latest.ipk)<3)attention.push('IPK di bawah 3.00');if(delta!=null&&delta<=-.25)attention.push('Tren IPK menurun');if(pct!=null&&pct<75)attention.push('Kehadiran perlu perhatian');if((ass||[]).some(x=>x.needs_checkin))attention.push('Asesmen meminta check-in');const result={ringkasan:attention.length?`Perlu tindak lanjut pada ${attention.length} sinyal perkembangan.`:'Belum ada sinyal risiko utama dari data yang tersedia.',academic:{latest_ipk:latest?.ipk??null,delta},attendance:{percentage:pct,total},achievements:(ach||[]).length,organizations:(org||[]).length,attention,recommendations:attention.length?['Verifikasi kondisi terbaru bersama Awardee','Tetapkan tindak lanjut yang spesifik dan terukur']:['Pertahankan monitoring berkala']};const fingerprint=crypto.createHash('sha256').update(JSON.stringify({ak,att,co,ass,ach,org})).digest('hex'),legacy='ANL-'+Date.now(),row=(await insert('rule_analyses',{legacy_id:legacy,awardee_id:aid,awardee_name:a?.[0]?.name||null,analyzed_at:new Date().toISOString(),engine:'ETOS-RULES-V2',data_fingerprint:fingerprint,result,review_status:'Belum ditinjau'},c))?.[0];return out(res,200,{success:true,data:row||{result}})}
 return out(res,404,{success:false,error:`Fungsi ${fn} tidak tersedia.`})}catch(e){console.error('[manage-cookie]',e);return out(res,500,{success:false,error:e.message||String(e)})}}
