const SHEET='1TEIvSxhSPQsvEO8tMM_Ym2ZDmZ3rb8c__L4HYSKPGm4';
const URL='https://weklmapqizeldfdalbgs.supabase.co';
const KEY='sb_publishable_cFm2Jvj2jvFyKcxbGniVWw_PL2SL7HC';
const AUTH=require('./awardee-authority.json');
function h(token,extra={}){return{apikey:KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json',...extra}}
async function sreq(path,token,options={}){const r=await fetch(URL+path,{...options,headers:{...h(token),...(options.headers||{})}});const text=await r.text();let body=null;try{body=text?JSON.parse(text):null}catch{body=text}if(!r.ok)throw new Error(body?.message||body?.error||body?.hint||`Supabase ${r.status}`);return body}
function csv(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(q){if(c==='"'&&n==='"'){cell+='"';i++}else if(c==='"')q=false;else cell+=c}else if(c==='"')q=true;else if(c===','){row.push(cell);cell=''}else if(c==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell=''}else cell+=c}if(cell||row.length){row.push(cell.replace(/\r$/,''));rows.push(row)}return rows}
async function tab(name){const u=`https://docs.google.com/spreadsheets/d/${SHEET}/gviz/tq?tqx=out:csv&sheet=${encodeURIComponent(name)}`;const r=await fetch(u,{redirect:'follow'});if(!r.ok)throw new Error(`Sheet ${name} HTTP ${r.status}`);const rows=csv(await r.text());if(!rows.length)return[];const head=rows[0].map(x=>String(x||'').trim());return rows.slice(1).filter(r=>r.some(x=>String(x||'').trim())).map(r=>Object.fromEntries(head.map((k,i)=>[k,String(r[i]??'').trim()]))) }
async function schema(token){const r=await fetch(URL+'/rest/v1/',{headers:{apikey:KEY,Authorization:`Bearer ${token}`,Accept:'application/openapi+json'}});if(!r.ok)return{};const x=await r.json();return x.definitions||x.components?.schemas||{}}
function cols(defs,table){const d=defs?.[table];return new Set(Object.keys(d?.properties||{}))}
function pick(obj,set){if(!set?.size)return obj;const x={};for(const[k,v]of Object.entries(obj))if(set.has(k)&&v!==undefined)x[k]=v;return x}
function num(v){const n=Number(String(v||'').replace(',','.'));return Number.isFinite(n)?n:null}
function iso(v){v=String(v||'').trim();if(!v)return null;if(/^\d{4}-\d{2}-\d{2}/.test(v))return v;const m=v.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})(?:\s+(\d{1,2}):(\d{2})(?::(\d{2}))?)?/);if(!m)return null;return`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}T${(m[4]||'00').padStart(2,'0')}:${m[5]||'00'}:${m[6]||'00'}+08:00`}
function j(v,fb=null){try{return JSON.parse(v)}catch{return fb}}
async function upsert(table,rows,token,defs,conflict='legacy_id'){if(!rows.length)return 0;const c=cols(defs,table);const clean=rows.map(x=>pick(x,c)).filter(x=>Object.keys(x).length);if(!clean.length)return 0;const suffix=c.has(conflict)?`?on_conflict=${encodeURIComponent(conflict)}`:'';await sreq(`/rest/v1/${table}${suffix}`,token,{method:'POST',headers:{Prefer:c.has(conflict)?'resolution=merge-duplicates,return=minimal':'return=minimal'},body:JSON.stringify(clean)});return clean.length}
async function awardeeMap(token){const rows=await sreq('/rest/v1/awardees?select=id,legacy_id',token);return new Map((rows||[]).map(x=>[x.legacy_id,x.id]))}
async function clearAttendance(token){try{await sreq('/rest/v1/attendance_records?id=not.is.null',token,{method:'DELETE',headers:{Prefer:'return=minimal'}})}catch{}try{await sreq('/rest/v1/attendance_sessions?id=not.is.null',token,{method:'DELETE',headers:{Prefer:'return=minimal'}})}catch{}}
module.exports=async function migrateSource(token,userId){const defs=await schema(token);const issues=[];const counts={};const [awardee,academic,org,ach,assessment,analysis,form,fac,portfolio]=await Promise.all(['Awardee','Akademik','Organisasi','Prestasi','Asesmen_Awardee','Analisis_Otomatis','Form_Refleksi_Kajian','Fasilitator','Portfolio'].map(tab));
 const awRows=awardee.map(r=>{const a=AUTH[String(r.ID_Awardee||'').toUpperCase()]||{};return{legacy_id:r.ID_Awardee,name:r.Nama,kampus:r.Kampus||null,jurusan:a.jurusan||r.Jurusan||null,angkatan:r.Angkatan||null,status:r.Status||null,motto:a.vision??(r.Motto||null),photo_url:r.Foto_URL||null,created_by:userId,updated_by:userId}});counts.awardees=await upsert('awardees',awRows,token,defs);
 const amap=await awardeeMap(token);
 const contacts=awardee.filter(r=>r.No_WA||r.Email).map(r=>({awardee_id:amap.get(r.ID_Awardee),whatsapp:r.No_WA||null,email:r.Email||null,updated_by:userId})).filter(x=>x.awardee_id);counts.awardee_contacts=await upsert('awardee_contacts',contacts,token,defs,'awardee_id');
 const ar=[];for(const r of academic){const sem=Number(r.Semester);const ipk=num(r.IPK);if(!Number.isInteger(sem)||sem<1||sem>14){issues.push({source_sheet:'Akademik',legacy_id:r.ID_Akademik,issue_type:'invalid_semester',severity:'warning',detail:`Semester ${r.Semester||'-'} dikarantina.`});continue}if(ipk==null){issues.push({source_sheet:'Akademik',legacy_id:r.ID_Akademik,issue_type:'missing_ipk',severity:'warning',detail:'IPK kosong.'});continue}const aid=amap.get(r.ID_Awardee);if(aid)ar.push({legacy_id:r.ID_Akademik,awardee_id:aid,semester:sem,ipk,created_by:userId,updated_by:userId})}counts.academic_records=await upsert('academic_records',ar,token,defs);
 const or=[];for(const r of org){if(!r.Nama_Organisasi){if(r.ID_Org)issues.push({source_sheet:'Organisasi',legacy_id:r.ID_Org,issue_type:'placeholder_row',severity:'info',detail:'Row ID/FK tanpa isi organisasi.'});continue}const aid=amap.get(r.ID_Awardee);if(aid)or.push({legacy_id:r.ID_Org,awardee_id:aid,organization_name:r.Nama_Organisasi,position:r.Jabatan||null,start_year:num(r.Tahun_Mulai),end_year_text:r.Tahun_Selesai||null,level:r.Tingkat||null,created_by:userId,updated_by:userId})}counts.organization_records=await upsert('organization_records',or,token,defs);
 const pr=[];for(const r of ach){if(!r.Nama_Prestasi||!r.ID_Awardee){if(r.ID_Prestasi)issues.push({source_sheet:'Prestasi',legacy_id:r.ID_Prestasi,issue_type:'placeholder_row',severity:'info',detail:'Row prestasi tidak substantif.'});continue}const aid=amap.get(r.ID_Awardee);if(aid)pr.push({legacy_id:r.ID_Prestasi,awardee_id:aid,achievement_name:r.Nama_Prestasi,organizer:r.Penyelenggara||null,year:num(r.Tahun),level:r.Tingkat||null,category:r.Kategori||null,created_by:userId,updated_by:userId})}counts.achievements=await upsert('achievements',pr,token,defs);
 const as=[];for(const r of assessment){const aid=amap.get(r.ID_Awardee);if(!aid)continue;as.push({legacy_id:r.ID_Asesmen,awardee_id:aid,assessment_code:r.Kode_Asesmen,status:r.Status,answers:j(r.Jawaban_JSON,[]),result:j(r.Hasil_JSON,{}),needs_checkin:/^(true|1|ya)$/i.test(r.Perlu_Checkin),updated_at:iso(r.Diperbarui_Pada),created_by:userId,updated_by:userId})}counts.assessments=await upsert('assessments',as,token,defs);
 const ra=[];for(const r of analysis){const aid=amap.get(r.ID_Awardee);if(!aid)continue;ra.push({legacy_id:r.ID_Analisis,awardee_id:aid,awardee_name:r.Nama_Awardee,analyzed_at:iso(r.Waktu_Analisis),engine:r.Mesin_Aturan,data_fingerprint:r.Fingerprint_Data,result:j(r.Hasil_JSON,{}),review_status:r.Status_Review||null,created_by:userId})}counts.rule_analyses=await upsert('rule_analyses',ra,token,defs);
 let periodMap=new Map();if(form.some(x=>x.ID_Periode)){const pids=[...new Set(form.map(x=>x.ID_Periode).filter(Boolean))];for(const pid of pids){let rows=[];try{rows=await sreq(`/rest/v1/development_periods?legacy_id=eq.${encodeURIComponent(pid)}&select=id,legacy_id`,token)}catch{}if(!rows?.[0]){issues.push({source_sheet:'Periode_Pembinaan',legacy_id:pid,issue_type:'missing_referenced_period',severity:'warning',detail:'Form refleksi mereferensikan periode yang tidak ada di source; dibuat compatibility row Arsip.'});try{await upsert('development_periods',[{legacy_id:pid,name:`Referensi Legacy ${pid}`,status:'Arsip',created_by:userId,updated_by:userId}],token,defs)}catch{}}try{rows=await sreq(`/rest/v1/development_periods?legacy_id=eq.${encodeURIComponent(pid)}&select=id,legacy_id`,token);if(rows?.[0])periodMap.set(pid,rows[0].id)}catch{}}}
 const rf=[];for(const r of form){rf.push({legacy_id:r.ID_Form,token:r.Token_Form,form_token:r.Token_Form,period_id:periodMap.get(r.ID_Periode)||null,agenda_name:r.Nama_Agenda,agenda_date:r.Tanggal_Agenda||null,target_cohort:r.Target_Angkatan||null,attendance_row:num(r.Baris_Absensi),status:r.Status||null,created_at:iso(r.Dibuat_Pada),public_link:r.Link_Publik||null,short_code:r.Kode_Pendek||null,created_by:userId,updated_by:userId})}counts.reflection_forms=await upsert('reflection_forms',rf,token,defs);
 const fr=fac.map(r=>({name:r.Nama,email:r.Email||null,whatsapp:r.No_WA||null,wilayah:r.Wilayah||null,bio:r.Bio||null}));if(fr.length){const c=cols(defs,'facilitators');for(const row of fr){const d=pick(row,c);let ex=[];if(d.email)try{ex=await sreq(`/rest/v1/facilitators?email=eq.${encodeURIComponent(d.email)}&select=id`,token)}catch{}if(ex?.[0])await sreq(`/rest/v1/facilitators?id=eq.${encodeURIComponent(ex[0].id)}`,token,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(d)});else await sreq('/rest/v1/facilitators',token,{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify([d])})}counts.facilitators=fr.length}else counts.facilitators=0;
 const po=[];for(const r of portfolio){if(r.ID_Porto==='PRT-0NaN'){issues.push({source_sheet:'Portfolio',legacy_id:r.ID_Porto,issue_type:'misassigned_artifact',severity:'warning',detail:'AWD-0009 dikarantina; dokumen tidak terverifikasi sebagai portfolio Awardee.'});continue}if(!r.ID_Awardee){if(r.Link_CV)issues.push({source_sheet:'Portfolio',legacy_id:null,issue_type:'unlinked_url',severity:'info',detail:'URL tanpa ID Awardee tidak dimigrasi sebagai portfolio.'});continue}const aid=amap.get(r.ID_Awardee);if(!aid)continue;let cv=r.Link_CV||null,evidence=r.Link_GDrive||null;if(r.ID_Awardee==='AWD-0006'){cv=r.Link_GDrive||null;evidence=r.Link_CV||null}po.push({legacy_id:r.ID_Porto,awardee_id:aid,cv_url:cv,contribution:r.Kontribusi||null,evidence_drive_url:evidence,updated_by:userId,created_by:userId})}counts.portfolios=await upsert('portfolios',po,token,defs);
 await clearAttendance(token);counts.attendance_sessions=0;counts.attendance_records=0;
 const issueCols=cols(defs,'migration_issues');if(issueCols.size){for(const x of issues){try{await sreq('/rest/v1/migration_issues',token,{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify([pick({...x,created_at:new Date().toISOString()},issueCols)])})}catch{}}}
 return{source:'DASHBOARD AWARDEE ETOS ID PALU',migratedAt:new Date().toISOString(),counts,issues,normalized:true};}
