const session=require('./server-session');
function json(res,status,body){res.status(status).setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(body))}
function bad(message,status=400){const e=new Error(message);e.status=status;throw e}
async function supa(path,c,options={}){const r=await fetch(session.PROJECT_URL+path,{...options,headers:{...session.dbHeaders(c),...(options.headers||{})}});const text=await r.text();let body=null;try{body=text?JSON.parse(text):null}catch{body=text}if(!r.ok){const e=new Error(body?.message||body?.error_description||body?.error||`Supabase ${r.status}`);e.status=r.status;throw e}return body}
async function profileFor(c){if(c?.server)return{user:{id:null},profile:{full_name:'ETOS ID Palu Superadmin',email:null,role:'superadmin',is_active:true}};const user=await supa('/auth/v1/user',c),rows=await supa(`/rest/v1/profiles?id=eq.${encodeURIComponent(user.id)}&select=id,full_name,email,role,is_active`,c),profile=rows?.[0];if(!profile?.is_active)bad('Akun belum aktif atau tidak memiliki akses.',403);return{user,profile}}
async function awardeeUuid(ref,c){const id=String(ref||'').trim();if(!id)return null;const path=/^AWD-/i.test(id)?`/rest/v1/awardees?legacy_id=eq.${encodeURIComponent(id.toUpperCase())}&select=id`:`/rest/v1/awardees?id=eq.${encodeURIComponent(id)}&select=id`;return(await supa(path,c))?.[0]?.id||null}
const ROLES={all:new Set(['superadmin','admin','facilitator','operator','viewer']),development:new Set(['superadmin','admin','facilitator'])};
function roleOf(p){return String(p?.role||'').toLowerCase()}function allow(set,role,label){if(!set.has(role))bad(`Role ${role||'tidak dikenal'} tidak memiliki izin untuk ${label}.`,403)}
module.exports=async function handler(req,res){if(req.method!=='POST')return json(res,405,{success:false,error:'Method not allowed'});try{const c=session.credential(req);if(!c)return json(res,401,{success:false,error:'Akses autentikasi diperlukan.'});const{user,profile}=await profileFor(c),fn=String(req.body?.function||''),p=req.body?.params??null,role=roleOf(profile);allow(ROLES.all,role,'modul operasional');
 if(fn==='verifyFacilitatorAccess'||fn==='verifyAbsensiAdminPin')return json(res,200,{success:true,data:{session:true,profile}});
 if(fn==='getFasilitatorProfile'){allow(ROLES.development,role,'profil fasilitator');const rows=c.server?await supa('/rest/v1/facilitators?select=*&limit=1',c):await supa(`/rest/v1/facilitators?user_id=eq.${encodeURIComponent(user.id)}&select=*`,c);return json(res,200,{success:true,data:rows?.[0]||{name:profile.full_name,email:profile.email,role}})}
 if(fn==='getCoachingList'){allow(ROLES.development,role,'data coaching');const rows=await supa('/rest/v1/coaching_sessions?select=legacy_id,session_date,topic_problem,solution,follow_up_plan,awardees!inner(legacy_id,name)&order=session_date.desc.nullslast',c);return json(res,200,{success:true,data:(rows||[]).map(x=>({id:x.legacy_id,awdId:x.awardees?.legacy_id,nama:x.awardees?.name||'Unknown',tgl:x.session_date||'-',topik:x.topic_problem||'-',solusi:x.solution||'-',rtl:x.follow_up_plan||'-'}))})}
 if(fn==='saveCoaching'){allow(ROLES.development,role,'menyimpan coaching');const aid=await awardeeUuid(p?.id_awardee,c);if(!aid)return json(res,404,{success:false,error:'Awardee tidak ditemukan.'});const row={awardee_id:aid,facilitator_name_legacy:profile.full_name||profile.email,session_date:p?.tgl||null,topic_problem:p?.topik||null,solution:p?.solusi||null,follow_up_plan:p?.rtl||null},data=await supa('/rest/v1/coaching_sessions?select=id',c,{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify([row])});return json(res,200,{success:true,data:data?.[0]})}
 if(fn==='getMentoringCases'){allow(ROLES.development,role,'data mentoring');const rows=await supa('/rest/v1/mentoring_cases?select=*,awardees!inner(legacy_id,name)&order=created_at.desc',c);return json(res,200,{success:true,data:(rows||[]).map(x=>({id:x.legacy_id||x.id,awardeeId:x.awardees?.legacy_id,nama:x.awardees?.name,kategori:x.category,judul:x.title,sumber:x.signal_source,prioritas:x.priority,pic:x.pic,aksi:x.action_plan,deadline:x.deadline,status:x.status,outcome:x.outcome}))})}
 if(fn==='saveMentoringCase'){allow(ROLES.development,role,'menyimpan mentoring');const aid=await awardeeUuid(p?.id_awardee||p?.awardeeId,c);if(!aid)return json(res,404,{success:false,error:'Awardee tidak ditemukan.'});const data=await supa('/rest/v1/mentoring_cases?select=id',c,{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify([{awardee_id:aid,category:p?.kategori||null,title:p?.judul||null,signal_source:p?.sumber||null,priority:p?.prioritas||null,pic:p?.pic||null,action_plan:p?.aksi||null,deadline:p?.deadline||null,status:p?.status||'Open',outcome:p?.outcome||null}])});return json(res,200,{success:true,data:data?.[0]})}
 if(fn==='getLatestAwardeeRuleAnalysis'){allow(ROLES.development,role,'analisis awardee');const aid=await awardeeUuid(p?.id_awardee||p,c);if(!aid)return json(res,404,{success:false,error:'Awardee tidak ditemukan.'});const rows=await supa(`/rest/v1/rule_analyses?awardee_id=eq.${aid}&select=*&order=analyzed_at.desc&limit=1`,c);return json(res,200,{success:true,data:rows?.[0]||null})}
 return json(res,404,{success:false,error:`Fungsi ${fn} belum tersedia pada secure API.`});
}catch(err){console.error('[secure-cookie]',err);return json(res,err?.status||500,{success:false,error:err?.message||String(err)})}}
