const session=require('./server-session');
function json(res,status,body){res.status(status).setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(body))}
function cred(req){return session.credential(req)}
async function supa(path,c,options={}){const r=await fetch(session.PROJECT_URL+path,{...options,headers:{...session.dbHeaders(c),...(options.headers||{})}});const text=await r.text();let body=null;try{body=text?JSON.parse(text):null}catch{body=text}if(!r.ok)throw new Error(body?.message||body?.error_description||body?.error||`Supabase ${r.status}`);return body}
async function profileFor(c){if(c?.server)return{user:{id:null},profile:{full_name:'ETOS ID Palu Administrator',email:null,role:'admin',is_active:true}};const user=await supa('/auth/v1/user',c);const rows=await supa(`/rest/v1/profiles?id=eq.${encodeURIComponent(user.id)}&select=id,full_name,email,role,is_active`,c);const profile=rows?.[0];if(!profile?.is_active)throw new Error('Akun belum aktif atau tidak memiliki akses.');return{user,profile}}
async function awardeeUuid(ref,c){const id=String(ref||'').trim();if(!id)return null;const path=/^AWD-/i.test(id)?`/rest/v1/awardees?legacy_id=eq.${encodeURIComponent(id.toUpperCase())}&select=id`:`/rest/v1/awardees?id=eq.${encodeURIComponent(id)}&select=id`;const rows=await supa(path,c);return rows?.[0]?.id||null}
const writable=r=>['superadmin','admin','facilitator','operator'].includes(String(r));const admin=r=>['superadmin','admin'].includes(String(r));
module.exports=async function handler(req,res){if(req.method!=='POST')return json(res,405,{success:false,error:'Method not allowed'});try{const c=cred(req);if(!c)return json(res,401,{success:false,error:'Sesi PIN operasional diperlukan.'});const{user,profile}=await profileFor(c),fn=String(req.body?.function||''),p=req.body?.params??null,role=profile.role;
 if(fn==='verifyFacilitatorAccess'||fn==='verifyAbsensiAdminPin')return json(res,200,{success:true,data:{session:true,profile}});
 if(fn==='getFasilitatorProfile'){const rows=c.server?await supa('/rest/v1/facilitators?select=*&limit=1',c):await supa(`/rest/v1/facilitators?user_id=eq.${encodeURIComponent(user.id)}&select=*`,c);return json(res,200,{success:true,data:rows?.[0]||{name:profile.full_name,email:profile.email,role}})}
 if(fn==='getCoachingList'){const rows=await supa('/rest/v1/coaching_sessions?select=legacy_id,session_date,topic_problem,solution,follow_up_plan,awardees!inner(legacy_id,name)&order=session_date.desc.nullslast',c);return json(res,200,{success:true,data:(rows||[]).map(x=>({id:x.legacy_id,awdId:x.awardees?.legacy_id,nama:x.awardees?.name||'Unknown',tgl:x.session_date||'-',topik:x.topic_problem||'-',solusi:x.solution||'-',rtl:x.follow_up_plan||'-'}))})}
 if(fn==='saveCoaching'){if(!writable(role))return json(res,403,{success:false,error:'Role tidak memiliki izin menulis.'});const aid=await awardeeUuid(p?.id_awardee,c);if(!aid)return json(res,404,{success:false,error:'Awardee tidak ditemukan.'});const row={awardee_id:aid,facilitator_name_legacy:profile.full_name||profile.email,session_date:p?.tgl||null,topic_problem:p?.topik||null,solution:p?.solusi||null,follow_up_plan:p?.rtl||null};const data=await supa('/rest/v1/coaching_sessions?select=id',c,{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify([row])});return json(res,200,{success:true,data:data?.[0]})}
 if(fn==='getAbsensiEntryOptions'){const[periods,awards,sessions]=await Promise.all([supa('/rest/v1/development_periods?select=id,legacy_id,name,start_date,end_date,status&order=start_date.desc.nullslast',c),supa('/rest/v1/awardees?status=neq.Lulus&select=legacy_id,name,angkatan,status&order=name.asc',c),supa('/rest/v1/attendance_sessions?select=activity_name&order=activity_date.desc.nullslast',c)]);const pp=(periods||[]).map(x=>({id:x.legacy_id||x.id,uuid:x.id,nama:x.name,mulai:x.start_date||'',selesai:x.end_date||'',status:x.status})),requested=String(p?.periodeId||''),selectedPeriod=pp.find(x=>x.id===requested)||pp.find(x=>String(x.status).toLowerCase()==='aktif')||pp[0]||null;return json(res,200,{success:true,data:{periods:pp,selectedPeriod,awardees:(awards||[]).map(x=>({id:x.legacy_id,nama:x.name,angkatan:x.angkatan,status:x.status})),cohorts:[...new Set((awards||[]).map(x=>String(x.angkatan||'')).filter(Boolean))].sort(),agendas:[...new Set((sessions||[]).map(x=>String(x.activity_name||'')).filter(Boolean))].sort()}})}
 if(fn==='savePeriodePembinaan'){if(!admin(role))return json(res,403,{success:false,error:'Hanya admin yang dapat membuat periode.'});const legacyId='PRD-'+String(Date.now()).slice(-6),body=[{legacy_id:legacyId,name:String(p?.nama||'').trim(),start_date:p?.mulai||null,end_date:p?.selesai||null,status:p?.status||'Aktif'}];const data=await supa('/rest/v1/development_periods?select=id,legacy_id,name,start_date,end_date,status',c,{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify(body)}),x=data?.[0];return json(res,200,{success:true,data:{id:x?.legacy_id||x?.id,nama:x?.name,mulai:x?.start_date,selesai:x?.end_date,status:x?.status}})}
 if(fn==='getAbsensiList'){const periods=await supa('/rest/v1/development_periods?select=id,legacy_id,name,start_date,end_date,status&order=start_date.desc.nullslast',c),pp=(periods||[]).map(x=>({id:x.legacy_id||x.id,uuid:x.id,nama:x.name,mulai:x.start_date||'',selesai:x.end_date||'',status:x.status})),requested=typeof p==='string'?p:String(p?.periodeId||''),selected=pp.find(x=>x.id===requested)||pp.find(x=>String(x.status).toLowerCase()==='aktif')||pp[0]||null;if(!selected)return json(res,200,{success:true,data:{items:[],periods:[],selectedPeriod:null,legacyMode:false,unresolvedTahsin:0}});const sessions=await supa(`/rest/v1/attendance_sessions?period_id=eq.${encodeURIComponent(selected.uuid)}&select=id`,c),ids=(sessions||[]).map(x=>x.id);if(!ids.length)return json(res,200,{success:true,data:{items:[],periods:pp,selectedPeriod:selected,legacyMode:false,unresolvedTahsin:0}});const records=await supa(`/rest/v1/attendance_records?session_id=in.(${ids.map(encodeURIComponent).join(',')})&select=status,awardees!inner(legacy_id,name,angkatan)`,c),map=new Map();for(const r of records||[]){const a=r.awardees,k=a.legacy_id;if(!map.has(k))map.set(k,{id:k,nama:a.name,angkatan:a.angkatan,h:0,i:0,s:0,a:0,total:0});const x=map.get(k);x.total++;const st=String(r.status||'').toLowerCase();if(st==='hadir')x.h++;else if(st==='izin')x.i++;else if(st==='sakit')x.s++;else if(st==='alpa')x.a++}const items=[...map.values()].map(x=>({...x,pct:x.total?Math.round(x.h/x.total*100):0}));return json(res,200,{success:true,data:{items,periods:pp,selectedPeriod:selected,legacyMode:false,unresolvedTahsin:0}})}
 if(fn==='saveAbsensiEntry'){if(!writable(role))return json(res,403,{success:false,error:'Role tidak memiliki izin absensi.'});const periodLegacy=String(p?.periodeId||'');let prs=await supa(`/rest/v1/development_periods?legacy_id=eq.${encodeURIComponent(periodLegacy)}&select=id`,c);if(!prs?.length)prs=await supa(`/rest/v1/development_periods?id=eq.${encodeURIComponent(periodLegacy)}&select=id`,c);const period=prs?.[0];if(!period)return json(res,404,{success:false,error:'Periode tidak ditemukan.'});const activity=String(p?.namaKegiatan||'').trim(),date=String(p?.tanggal||'').trim();const dup=await supa(`/rest/v1/attendance_sessions?period_id=eq.${period.id}&activity_name=eq.${encodeURIComponent(activity)}&activity_date=eq.${date}&select=id`,c);if(dup?.length)return json(res,409,{success:false,error:'Absensi untuk agenda dan tanggal tersebut sudah ada.'});const sess=await supa('/rest/v1/attendance_sessions?select=id',c,{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify([{period_id:period.id,activity_name:activity,activity_date:date,target_cohort:p?.targetAngkatan||'Umum'}])}),statuses=p?.statuses||{},ids=Object.keys(statuses).map(x=>String(x).trim().toUpperCase()).filter(Boolean),awards=await supa(`/rest/v1/awardees?legacy_id=in.(${ids.map(x=>encodeURIComponent(x)).join(',')})&select=id,legacy_id`,c),amap=new Map((awards||[]).map(x=>[x.legacy_id,x.id])),rows=ids.map(id=>({session_id:sess[0].id,awardee_id:amap.get(id),status:String(statuses[id]||'').replace(/^Tidak Hadir$/i,'Alpa'),checked_at:new Date().toISOString()})).filter(x=>x.awardee_id&&['Hadir','Izin','Sakit','Alpa'].includes(x.status));await supa('/rest/v1/attendance_records',c,{method:'POST',body:JSON.stringify(rows)});return json(res,200,{success:true,data:{row:sess[0].id,totalDiisi:rows.length}})}
 if(fn==='getMentoringCases'){const rows=await supa('/rest/v1/mentoring_cases?select=*,awardees!inner(legacy_id,name)&order=created_at.desc',c);return json(res,200,{success:true,data:(rows||[]).map(x=>({id:x.legacy_id||x.id,awardeeId:x.awardees?.legacy_id,nama:x.awardees?.name,kategori:x.category,judul:x.title,sumber:x.signal_source,prioritas:x.priority,pic:x.pic,aksi:x.action_plan,deadline:x.deadline,status:x.status,outcome:x.outcome}))})}
 if(fn==='saveMentoringCase'){if(!writable(role))return json(res,403,{success:false,error:'Role tidak memiliki izin menulis.'});const aid=await awardeeUuid(p?.id_awardee||p?.awardeeId,c);if(!aid)return json(res,404,{success:false,error:'Awardee tidak ditemukan.'});const data=await supa('/rest/v1/mentoring_cases?select=id',c,{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify([{awardee_id:aid,category:p?.kategori||null,title:p?.judul||null,signal_source:p?.sumber||null,priority:p?.prioritas||null,pic:p?.pic||null,action_plan:p?.aksi||null,deadline:p?.deadline||null,status:p?.status||'Open',outcome:p?.outcome||null}])});return json(res,200,{success:true,data:data?.[0]})}
 if(fn==='getFacilitatorAssessmentHub'){const[awards,ass]=await Promise.all([supa('/rest/v1/awardees?status=neq.Lulus&select=id,legacy_id,name,angkatan&order=name.asc',c),supa('/rest/v1/assessments?select=awardee_id,assessment_code,status,needs_checkin',c)]),g=new Map();for(const a of ass||[]){if(!g.has(a.awardee_id))g.set(a.awardee_id,[]);g.get(a.awardee_id).push(a)}return json(res,200,{success:true,data:{awardees:(awards||[]).map(a=>{const rs=g.get(a.id)||[];return{id:a.legacy_id,nama:a.name,angkatan:a.angkatan,completed:rs.filter(x=>String(x.status).toUpperCase()==='SELESAI').length,needCheckin:rs.some(x=>x.needs_checkin)}})}})}
 if(fn==='getFacilitatorAssessmentReport'){const aid=await awardeeUuid(p?.id_awardee||p,c);if(!aid)return json(res,404,{success:false,error:'Awardee tidak ditemukan.'});const records=await supa(`/rest/v1/assessments?awardee_id=eq.${aid}&select=assessment_code,status,answers,result,needs_checkin,updated_at`,c);return json(res,200,{success:true,data:{records:records||[]}})}
 if(fn==='getLatestAwardeeRuleAnalysis'){const aid=await awardeeUuid(p?.id_awardee||p,c);if(!aid)return json(res,404,{success:false,error:'Awardee tidak ditemukan.'});const rows=await supa(`/rest/v1/rule_analyses?awardee_id=eq.${aid}&select=*&order=analyzed_at.desc&limit=1`,c);return json(res,200,{success:true,data:rows?.[0]||null})}
 if(fn==='getAwardee360'){const aid=await awardeeUuid(p?.id_awardee,c);if(!aid)return json(res,404,{success:false,error:'Awardee tidak ditemukan.'});const[a,ct,ak,o,pr,co,ass,mc,ra,po]=await Promise.all([supa(`/rest/v1/awardees?id=eq.${aid}&select=*`,c),supa(`/rest/v1/awardee_contacts?awardee_id=eq.${aid}&select=whatsapp,email`,c),supa(`/rest/v1/academic_records?awardee_id=eq.${aid}&select=*&order=semester.asc`,c),supa(`/rest/v1/organization_records?awardee_id=eq.${aid}&select=*`,c),supa(`/rest/v1/achievements?awardee_id=eq.${aid}&select=*&order=year.desc`,c),supa(`/rest/v1/coaching_sessions?awardee_id=eq.${aid}&select=*&order=session_date.desc`,c),supa(`/rest/v1/assessments?awardee_id=eq.${aid}&select=*`,c),supa(`/rest/v1/mentoring_cases?awardee_id=eq.${aid}&select=*&order=created_at.desc`,c),supa(`/rest/v1/rule_analyses?awardee_id=eq.${aid}&select=*&order=analyzed_at.desc&limit=5`,c),supa(`/rest/v1/portfolios?awardee_id=eq.${aid}&select=*`,c)]);return json(res,200,{success:true,data:{awardee:a?.[0],contact:ct?.[0],akademik:ak||[],organisasi:o||[],prestasi:pr||[],coaching:co||[],assessments:ass||[],cases:mc||[],analyses:ra||[],portfolio:po?.[0]||null}})}
 return json(res,404,{success:false,error:`Fungsi ${fn} belum tersedia pada secure API.`})
}catch(err){console.error('[secure-cookie]',err);return json(res,500,{success:false,error:err?.message||String(err)})}}
