(function(){
'use strict';
const PROJECT_URL='https://weklmapqizeldfdalbgs.supabase.co';
const PUBLISHABLE_KEY='sb_publishable_cFm2Jvj2jvFyKcxbGniVWw_PL2SL7HC';
const FUNCTIONS_URL=PROJECT_URL+'/functions/v1';
const sb=window.supabase&&window.supabase.createClient?window.supabase.createClient(PROJECT_URL,PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}):null;
window.etosSupabase=sb;
async function fetchJson(url,options){options=options||{};options.headers=Object.assign({'Content-Type':'application/json','apikey':PUBLISHABLE_KEY},options.headers||{});const response=await fetch(url,options);let body={};try{body=await response.json()}catch(_){}if(!response.ok&&!body.error)body.error='HTTP '+response.status;return body}
function publicCall(name,params){return fetchJson(FUNCTIONS_URL+'/public-api',{method:'POST',body:JSON.stringify({function:name,params:params==null?null:params})})}
function reflectionCall(name,params){const action=name==='getPublicKajianReflectionForm'?'form':name==='verifyKajianReflectionParticipant'?'verify':'submit';const payload=Object.assign({},params||{},{action});if(name==='getPublicKajianReflectionForm')payload.formToken=params;return fetchJson(FUNCTIONS_URL+'/public-reflection',{method:'POST',body:JSON.stringify(payload)})}
async function secureCall(name,params){if(!sb)return{success:false,error:'Supabase client tidak tersedia.'};const{data}=await sb.auth.getSession();const token=data&&data.session?data.session.access_token:'';if(!token)return{success:false,error:'PIN akses diperlukan untuk fitur operasional.'};const endpoint=name==='getAwardee360'?'/api/awardee360':'/api/secure';return fetchJson(endpoint,{method:'POST',headers:{Authorization:'Bearer '+token},body:JSON.stringify({function:name,params:params==null?null:params})})}
const PUBLIC_FUNCTIONS=new Set(['getDashboardStats','getFeaturedAwardees','getAwardeeList','getAlumniList','getAkademikList','getPrestasiList','getOrganisasiList','getAwardeeProfile','getDropdownOptions']);
const REFLECTION_FUNCTIONS=new Set(['getPublicKajianReflectionForm','verifyKajianReflectionParticipant','submitKajianReflection']);
async function call(name,params){if(REFLECTION_FUNCTIONS.has(name))return reflectionCall(name,params);if(PUBLIC_FUNCTIONS.has(name))return publicCall(name,params);if(name==='logoutAbsensiAdmin'||name==='logoutFacilitatorAccess')return{success:true};return secureCall(name,params)}
async function bootstrapAdmin(){if(!sb)throw new Error('Supabase client tidak tersedia.');const{data}=await sb.auth.getSession();const token=data&&data.session?data.session.access_token:'';if(!token)return null;return fetchJson(FUNCTIONS_URL+'/bootstrap-admin',{method:'POST',headers:{Authorization:'Bearer '+token},body:'{}'})}
async function signInPin(pin){if(!sb)throw new Error('Supabase client tidak tersedia.');pin=String(pin||'').trim();if(!/^\d{6}$/.test(pin))throw new Error('PIN harus terdiri dari 6 digit.');const r=await fetch('/api/pin-login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pin})});let body={};try{body=await r.json()}catch(_){}if(!r.ok||body.success===false)throw new Error(body.error||'PIN tidak sesuai.');const tokens=body.data||{};const result=await sb.auth.setSession({access_token:tokens.access_token,refresh_token:tokens.refresh_token});if(result.error)throw result.error;try{await bootstrapAdmin()}catch(_){}return{session:result.data.session,firstSetup:false}}
function createRunner(){let successHandler=null,failureHandler=null;const target={withSuccessHandler(handler){successHandler=handler;return proxy},withFailureHandler(handler){failureHandler=handler;return proxy}};const proxy=new Proxy(target,{get(obj,prop){if(prop in obj)return obj[prop];return function(){const args=Array.prototype.slice.call(arguments);call(String(prop),args.length?args[0]:null).then(result=>{if(successHandler)successHandler(result)}).catch(error=>{if(failureHandler)failureHandler(error);else console.error('[ETOS Supabase Adapter]',prop,error)});return proxy}}});return proxy}
window.google=window.google||{};window.google.script=window.google.script||{};Object.defineProperty(window.google.script,'run',{configurable:true,get(){return createRunner()}});
window.etosAPI={call,publicCall,secureCall,reflectionCall};
window.etosAuth={signInPin,bootstrapAdmin,getSession(){return sb?sb.auth.getSession():Promise.resolve({data:{session:null}})},signOut(){return sb?sb.auth.signOut():Promise.resolve()},onChange(callback){return sb?sb.auth.onAuthStateChange(callback):null}};
})();
