const session=require('../server-session');
const ROLES=new Set(['superadmin','admin','facilitator','operator','viewer']);
function out(res,status,body){res.status(status);res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(body))}
function bad(message,status=400){const e=new Error(message);e.status=status;throw e}
function uuid(v){return /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(v||''))}
async function q(path,c,options={}){const r=await fetch(session.PROJECT_URL+path,{...options,headers:{...session.dbHeaders(c),...(options.headers||{})}});const text=await r.text();let body=null;try{body=text?JSON.parse(text):null}catch{body=text}if(!r.ok){const e=new Error(body?.message||body?.error_description||body?.error||body?.hint||`Supabase ${r.status}`);e.status=r.status;throw e}return body}
function serverCred(){const key=session.secret(),kind=session.kind(key);if(kind!=='secret'&&kind!=='legacy')bad('Supabase Secret Key server tidak valid.',500);return{server:true,key,kind}}
async function caller(req){const c=session.credential(req);if(!c)bad('Akses autentikasi diperlukan.',401);if(c.server)return{kind:'pin',user:{id:null},profile:{role:'superadmin',is_active:true}};const user=await q('/auth/v1/user',c),rows=await q(`/rest/v1/profiles?id=eq.${encodeURIComponent(user.id)}&select=id,full_name,email,role,is_active`,c),profile=rows?.[0];if(!profile?.is_active)bad('Akun belum aktif.',403);if(String(profile.role)!=='superadmin')bad('Access Control hanya tersedia untuk Superadmin.',403);return{kind:'user',user,profile}}
async function list(c){return q('/rest/v1/profiles?select=id,full_name,email,phone,role,is_active,last_login_at,created_at,updated_at&order=created_at.desc',c)}
async function audit(c,req,actorId,id,oldRow,newRow){const requestId=String(req.headers?.['x-vercel-id']||req.headers?.['x-request-id']||'').slice(0,200)||null;const row={actor_id:actorId||null,action:'access_control_update',table_name:'profiles',record_id:id,old_data:{role:oldRow.role,is_active:oldRow.is_active},new_data:{role:newRow.role,is_active:newRow.is_active},request_id:requestId};try{await q('/rest/v1/audit_logs',c,{method:'POST',body:JSON.stringify([row])})}catch(e){console.warn('[access-control audit]',e.message||String(e))}}
async function update(c,req,actorId,p){const id=String(p?.id||'').trim(),role=String(p?.role||'').trim().toLowerCase(),active=p?.is_active;if(!uuid(id))bad('ID profil tidak valid.');if(!ROLES.has(role))bad('Role tidak valid.');if(typeof active!=='boolean')bad('Status aktif harus berupa boolean.');const rows=await q(`/rest/v1/profiles?id=eq.${encodeURIComponent(id)}&select=id,full_name,email,role,is_active`,c),oldRow=rows?.[0];if(!oldRow)bad('Profil tidak ditemukan.',404);if(oldRow.role==='superadmin'&&oldRow.is_active&&(role!=='superadmin'||active===false)){const admins=await q('/rest/v1/profiles?role=eq.superadmin&is_active=eq.true&select=id',c);if((admins||[]).length<=1)bad('Superadmin aktif terakhir tidak boleh dinonaktifkan atau diturunkan rolenya.',409)}const changed=oldRow.role!==role||oldRow.is_active!==active;if(!changed)return oldRow;const patched=await q(`/rest/v1/profiles?id=eq.${encodeURIComponent(id)}&select=id,full_name,email,phone,role,is_active,last_login_at,created_at,updated_at`,c,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({role,is_active:active})}),next=patched?.[0];if(!next)bad('Profil gagal diperbarui.',500);await audit(c,req,actorId,id,oldRow,next);return next}
module.exports=async function handler(req,res){if(req.method!=='POST')return out(res,405,{success:false,error:'Method not allowed'});try{const who=await caller(req),c=serverCred(),action=String(req.body?.action||'list');if(action==='list'){const rows=await list(c);return out(res,200,{success:true,data:{rows,roles:[...ROLES],caller:{kind:who.kind,role:'superadmin'}}})}if(action==='update'){const row=await update(c,req,who.user?.id||null,req.body?.data||{});return out(res,200,{success:true,data:row})}return out(res,404,{success:false,error:'Aksi Access Control tidak tersedia.'})}catch(e){console.error('[access-control]',e);return out(res,e.status||500,{success:false,error:e.message||String(e)})}}
