const session=require('../server-session');
const CUTOVER='2026-09-07';
function out(res,status,body){res.status(status).setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(body))}
function bad(message,status=400){const e=new Error(message);e.status=status;throw e}
async function q(path,c){const r=await fetch(session.PROJECT_URL+path,{headers:session.dbHeaders(c)});const text=await r.text();let b=null;try{b=text?JSON.parse(text):null}catch{b=text}if(!r.ok){const e=new Error(b?.message||b?.error||`Supabase ${r.status}`);e.status=r.status;throw e}return b}
async function identity(c){if(c?.server)return{role:'superadmin',is_active:true,id:null};const u=await q('/auth/v1/user',c),p=await q(`/rest/v1/profiles?id=eq.${encodeURIComponent(u.id)}&select=id,role,is_active`,c);if(!p?.[0]?.is_active)bad('Akun belum aktif.',403);return p[0]}
function scopes(role){role=String(role||'').toLowerCase();return{general:['viewer','operator','facilitator','admin','superadmin'].includes(role),privateOps:['operator','facilitator','admin','superadmin'].includes(role),development:['facilitator','admin','superadmin'].includes(role)}}
async function resolveAwardee(ref,c){const v=String(ref||'').trim();if(!v)return null;const path=/^AWD-/i.test(v)?`/rest/v1/awardees?legacy_id=eq.${encodeURIComponent(v.toUpperCase())}&select=*`:`/rest/v1/awardees?id=eq.${encodeURIComponent(v)}&select=*`;return(await q(path,c))?.[0]||null}
function nonblank(v){return v!==null&&v!==undefined&&String(v).trim()!==''}
function meaningful(x,fields){return!!x&&fields.some(k=>nonblank(x[k]))}
function validAcademic(rows){return(rows||[]).filter(x=>{if(String(x.record_type||'')==='rekap_1_8'){x.semester_label='1-8';x.is_summary=true;return true}const s=Number(x.semester);return Number.isInteger(s)&&s>=1&&s<=14}).sort((a,b)=>Number(a.semester||0)-Number(b.semester||0))}
const validOrganizations=rows=>(rows||[]).filter(x=>meaningful(x,['organization_name','position','level','start_year','end_year_text']));
const validAchievements=rows=>(rows||[]).filter(x=>meaningful(x,['achievement_name','organizer','year','level','category']));
const validCoaching=rows=>(rows||[]).filter(x=>meaningful(x,['session_date','facilitator','topic_problem','solution','follow_up_plan']));
const validAttendance=rows=>(rows||[]).filter(x=>{const s=Array.isArray(x.attendance_sessions)?x.attendance_sessions[0]:x.attendance_sessions,d=String(s?.activity_date||'');return d&&d>=CUTOVER});
const validAnalyses=rows=>(rows||[]).filter(x=>String(x.analyzed_at||'')>=CUTOVER);
module.exports=async function handler(req,res){if(req.method!=='POST')return out(res,405,{success:false,error:'Method not allowed'});try{const c=session.credential(req);if(!c)return out(res,401,{success:false,error:'Akses autentikasi diperlukan.'});const ident=await identity(c),access=scopes(ident.role);if(!access.general)bad('Role tidak memiliki akses Awardee 360.',403);const a=await resolveAwardee(req.body?.params?.id_awardee||req.body?.params||'',c);if(!a)return out(res,404,{success:false,error:'Awardee tidak ditemukan.'});const id=a.id;
 const general=[q(`/rest/v1/academic_records?awardee_id=eq.${id}&select=*&order=semester.asc.nullslast`,c),q(`/rest/v1/organization_records?awardee_id=eq.${id}&select=*&order=start_year.desc.nullslast`,c),q(`/rest/v1/achievements?awardee_id=eq.${id}&select=*&order=year.desc.nullslast`,c),q(`/rest/v1/portfolios?awardee_id=eq.${id}&select=*&order=updated_at.desc.nullslast&limit=1`,c).catch(()=>[])];
 const privateOps=access.privateOps?[q(`/rest/v1/awardee_contacts?awardee_id=eq.${id}&select=whatsapp,email`,c),q(`/rest/v1/attendance_records?awardee_id=eq.${id}&select=status,notes,checked_at,attendance_sessions(activity_name,activity_date,target_cohort,period_id)&order=checked_at.desc.nullslast`,c)]:[Promise.resolve([]),Promise.resolve([])];
 const dev=access.development?[q(`/rest/v1/coaching_sessions?awardee_id=eq.${id}&select=*&order=session_date.desc`,c),q(`/rest/v1/mentoring_cases?awardee_id=eq.${id}&select=*&order=created_at.desc`,c),q(`/rest/v1/rule_analyses?awardee_id=eq.${id}&select=*&order=analyzed_at.desc&limit=10`,c),q(`/rest/v1/competencies?awardee_id=eq.${id}&select=*&order=assessed_at.desc.nullslast`,c),q(`/rest/v1/reflection_responses?awardee_id=eq.${id}&select=*&order=submitted_at.desc.nullslast`,c),q(`/rest/v1/networking_records?awardee_id=eq.${id}&select=*&order=contact_date.desc.nullslast`,c),q(`/rest/v1/spiritual_records?awardee_id=eq.${id}&select=*&order=created_at.desc`,c)]:Array.from({length:7},()=>Promise.resolve([]));
 const[academicRaw,organizationsRaw,achievementsRaw,portfolioRows,contact,attendanceRaw,coachingRaw,cases,analysesRaw,competencies,reflections,networking,spiritual]=await Promise.all([...general,...privateOps,...dev]);
 const academic=validAcademic(academicRaw),organizations=validOrganizations(organizationsRaw),achievements=validAchievements(achievementsRaw),coaching=validCoaching(coachingRaw),attendance=validAttendance(attendanceRaw),analyses=validAnalyses(analysesRaw),portfolio=portfolioRows?.[0]||null;const att={hadir:0,izin:0,sakit:0,alpa:0,total:0,pct:null,records:attendance};for(const r of attendance){att.total++;const s=String(r.status||'').toLowerCase();if(s==='hadir')att.hadir++;else if(s==='izin')att.izin++;else if(s==='sakit')att.sakit++;else if(s==='alpa')att.alpa++}att.pct=att.total?Math.round(att.hadir/att.total*100):null;const withIpk=academic.filter(x=>x.ipk!==null&&x.ipk!==''),latestAcademic=withIpk.filter(x=>String(x.record_type||'')!=='rekap_1_8').slice(-1)[0]||withIpk.find(x=>String(x.record_type||'')==='rekap_1_8')||null;const hidden=[];if(!access.privateOps)hidden.push('contact','attendance');if(!access.development)hidden.push('coaching','mentoring','analyses','competencies','reflections','networking','spiritual','idp');const response={awardee:a,contact:access.privateOps?(contact?.[0]||null):null,academic,akademik:academic,organizations,organisasi:organizations,achievements,prestasi:achievements,portfolio,coaching:access.development?coaching:[],cases:access.development?(cases||[]):[],analyses:access.development?analyses:[],competencies:access.development?(competencies||[]):[],reflections:access.development?(reflections||[]):[],attendance:access.privateOps?att:{hadir:0,izin:0,sakit:0,alpa:0,total:0,pct:null,records:[]},networking:access.development?(networking||[]):[],spiritual:access.development?(spiritual||[]):[],idp:null,access:{role:String(ident.role),private_ops:access.privateOps,development:access.development,hidden_sections:hidden},data_quality:{source_policy:'supabase-only',legacy_analysis_excluded:access.development?(analysesRaw||[]).length-analyses.length:null,legacy_attendance_excluded:access.privateOps?(attendanceRaw||[]).length-attendance.length:null},summary:{latest_ipk:latestAcademic?.ipk??null,latest_ipk_label:latestAcademic?.record_type==='rekap_1_8'?'Rekap Semester 1-8':latestAcademic?.semester?`Semester ${latestAcademic.semester}`:null,attendance_pct:access.privateOps?att.pct:null,open_cases:access.development?(cases||[]).filter(x=>!['selesai','closed','done'].includes(String(x.status||'').toLowerCase())).length:null,achievement_count:achievements.length,organization_count:organizations.length,reflection_count:access.development?(reflections||[]).length:null,competency_count:access.development?(competencies||[]).length:null}};return out(res,200,{success:true,data:response})}catch(e){console.error('[Awardee360]',e);return out(res,e.status||500,{success:false,error:e.message||String(e)})}}
