const crypto=require('crypto');
const session=require('../server-session');
const migrateSource=require('../migration-source-cookie');
const TOKEN_HASH='46552852a3ffe59f125884116a9b6e393285915fa56d63e73ab725577802a3b0';
const SOURCE_NAME='DASHBOARD AWARDEE ETOS ID PALU';
const SOURCE_FILE_ID='1TEIvSxhSPQsvEO8tMM_Ym2ZDmZ3rb8c__L4HYSKPGm4';
function out(res,status,body){res.status(status);res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(body))}
function authorized(req){const raw=String(req.headers.authorization||'').replace(/^Bearer\s+/i,'').trim();if(!raw)return false;const got=crypto.createHash('sha256').update(raw).digest('hex');return got.length===TOKEN_HASH.length&&crypto.timingSafeEqual(Buffer.from(got),Buffer.from(TOKEN_HASH))}
function serverCred(){const key=session.secret(),kind=session.kind(key);if(!['secret','legacy'].includes(kind))throw new Error('Supabase server credential tidak valid.');return{server:true,key,kind}}
async function q(path,c,options={}){const r=await fetch(session.PROJECT_URL+path,{...options,headers:{...session.dbHeaders(c),...(options.headers||{})}});const text=await r.text();let body=null;try{body=text?JSON.parse(text):null}catch{body=text}if(!r.ok)throw new Error(body?.message||body?.error||body?.hint||`Supabase ${r.status}`);return body}
module.exports=async function handler(req,res){if(!['GET','POST'].includes(req.method))return out(res,405,{success:false,error:'Method not allowed'});if(!authorized(req))return out(res,401,{success:false,error:'Unauthorized'});let batchId=null;try{const c=serverCred(),started=new Date().toISOString();const batch=await q('/rest/v1/migration_batches?select=id',c,{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify([{source_name:SOURCE_NAME,source_file_id:SOURCE_FILE_ID,started_at:started,status:'running'}])});batchId=batch?.[0]?.id||null;const result=await migrateSource();if(batchId)await q(`/rest/v1/migration_batches?id=eq.${encodeURIComponent(batchId)}`,c,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({completed_at:new Date().toISOString(),status:'completed',summary:{trigger:'supabase_cron',migrationVersion:result.migrationVersion,counts:result.counts,issues:(result.issues||[]).length}})});return out(res,200,{success:true,data:{batchId,migrationVersion:result.migrationVersion,counts:result.counts,issues:(result.issues||[]).length}})}catch(e){console.error('[cron-sync]',e);try{if(batchId){const c=serverCred();await q(`/rest/v1/migration_batches?id=eq.${encodeURIComponent(batchId)}`,c,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({completed_at:new Date().toISOString(),status:'failed',summary:{trigger:'supabase_cron',error:e.message||String(e)}})})}}catch(_){}return out(res,500,{success:false,error:e.message||String(e),batchId})}};
