const PROJECT_URL='https://weklmapqizeldfdalbgs.supabase.co';
const KEY='sb_publishable_cFm2Jvj2jvFyKcxbGniVWw_PL2SL7HC';
const TABLES={awardees:{label:'Awardee',write:true},awardee_contacts:{label:'Kontak Awardee',write:true},academic_records:{label:'Akademik',write:true},organization_records:{label:'Organisasi',write:true},achievements:{label:'Prestasi',write:true},coaching_sessions:{label:'Coaching',write:true},spiritual_records:{label:'Spiritual',write:true},networking_records:{label:'Networking',write:true},portfolios:{label:'Portfolio / CV Links',write:true},assessments:{label:'Asesmen',write:true},competencies:{label:'Kompetensi',write:true},mentoring_cases:{label:'Mentoring Case',write:true},rule_analyses:{label:'Analisis Otomatis',write:false},development_periods:{label:'Periode Pembinaan',write:true},attendance_sessions:{label:'Sesi Absensi',write:true},attendance_records:{label:'Detail Absensi',write:true},reflection_forms:{label:'Form Refleksi',write:true},reflection_responses:{label:'Refleksi Awardee',write:true},facilitators:{label:'Fasilitator',write:true},idp_external_sources:{label:'IDP — Sumber Pusat',write:false},idp_snapshots:{label:'IDP — Snapshot',write:false},migration_batches:{label:'Migration Batch',write:false},migration_issues:{label:'Migration Issues',write:false},audit_logs:{label:'Audit Log',write:false}};
const PROTECTED=new Set(['id','created_at','created_by','updated_at']);
function out(res,status,body){res.status(status);res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(body))}
function token(req){return String(req.headers.authorization||'').replace(/^Bearer\s+/i,'').trim()}
function headers(t,extra={}){return{apikey:KEY,Authorization:`Bearer ${t}`,'Content-Type':'application/json',...extra}}
async function q(path,t,options={}){const r=await fetch(PROJECT_URL+path,{...options,headers:{...headers(t),...(options.headers||{})}});const text=await r.text();let body=null;try{body=text?JSON.parse(text):null}catch{body=text}if(!r.ok)throw new Error(body?.message||body?.error||body?.hint||`Supabase ${r.status}`);return body}
async function identity(t){const u=await q('/auth/v1/user',t);const p=await q(`/rest/v1/profiles?id=eq.${encodeURIComponent(u.id)}&select=id,role,is_active`,t);const x=p?.[0];if(!x?.is_active)throw new Error('Akun tidak aktif.');if(!['superadmin','admin','operator','facilitator'].includes(String(x.role||'').toLowerCase()))throw new Error('Role tidak memiliki akses Data Center.');return{user:u,profile:x}}
function clean(input){const x={};for(const[k,v]of Object.entries(input||{})){if(PROTECTED.has(k)||k.startsWith('_'))continue;x[k]=v===''?null:v}return x}
function sortRows(rows){return rows.sort((a,b)=>String(b.updated_at||b.created_at||b.activity_date||b.analyzed_at||'').localeCompare(String(a.updated_at||a.created_at||a.activity_date||a.analyzed_at||'')))}
module.exports=async function handler(req,res){if(req.method!=='POST')return out(res,405,{success:false,error:'Method not allowed'});try{const t=token(req);if(!t)return out(res,401,{success:false,error:'Session PIN diperlukan.'});await identity(t);const action=String(req.body?.action||'catalog'),table=String(req.body?.table||''),cfg=TABLES[table];if(action==='catalog')return out(res,200,{success:true,data:Object.entries(TABLES).map(([name,c])=>({name,label:c.label,write:c.write}))});if(!cfg)return out(res,400,{success:false,error:'Tabel tidak termasuk Data Center ETOS.'});if(action==='list'){const limit=Math.min(1000,Math.max(1,Number(req.body?.limit||500)));let rows=await q(`/rest/v1/${table}?select=*&limit=${limit}`,t);rows=Array.isArray(rows)?sortRows(rows):[];const s=String(req.body?.search||'').trim().toLowerCase();if(s)rows=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(s));return out(res,200,{success:true,data:{table,label:cfg.label,write:cfg.write,total:rows.length,rows}})}if(action==='update'){if(!cfg.write)return out(res,403,{success:false,error:'Tabel ini read-only di Data Center.'});const id=String(req.body?.id||'').trim();if(!id)throw new Error('ID record wajib ada.');const patch=clean(req.body?.data);if(!Object.keys(patch).length)throw new Error('Tidak ada perubahan yang dapat disimpan.');const rows=await q(`/rest/v1/${table}?id=eq.${encodeURIComponent(id)}&select=*`,t,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(patch)});return out(res,200,{success:true,data:rows?.[0]||null})}return out(res,404,{success:false,error:'Aksi Data Center tidak tersedia.'})}catch(e){console.error('[data-center]',e);return out(res,500,{success:false,error:e.message||String(e)})}};
