const crypto=require('crypto'),zlib=require('zlib'),fs=require('fs'),path=require('path');
const session=require('../server-session');
const FILE_ID='15TcqNsc3oLqzJxjZ8whV-cgYX00HM2k9',SOURCE_NAME='Palu-IDP KI.xlsx';let cache=null;
function out(res,s,b){res.status(s).setHeader('Content-Type','application/json');res.setHeader('Cache-Control','private, max-age=0, s-maxage=300');res.end(JSON.stringify(b))}
function bad(message,status=403){const e=new Error(message);e.status=status;throw e}
async function q(path,c){const r=await fetch(session.PROJECT_URL+path,{headers:session.dbHeaders(c)});const text=await r.text();let body=null;try{body=text?JSON.parse(text):null}catch{body=text}if(!r.ok){const e=new Error(body?.message||body?.error_description||body?.error||`Supabase ${r.status}`);e.status=r.status;throw e}return body}
async function authorize(req){const c=session.credential(req);if(!c)bad('Akses autentikasi diperlukan.',401);if(c.server)return{c,role:'superadmin'};const user=await q('/auth/v1/user',c),rows=await q(`/rest/v1/profiles?id=eq.${encodeURIComponent(user.id)}&select=id,role,is_active`,c),p=rows?.[0];if(!p?.is_active)bad('Akun belum aktif.',403);const role=String(p.role||'').toLowerCase();if(!['superadmin','admin','facilitator'].includes(role))bad(`Role ${role||'tidak dikenal'} tidak memiliki akses ke IDP pusat.`,403);return{c,role}}
const b64=x=>Buffer.from(x).toString('base64url');async function googleToken(){const raw=String(process.env.GOOGLE_SERVICE_ACCOUNT_JSON||'').trim();if(!raw)return'';let sa;try{sa=JSON.parse(raw)}catch{try{sa=JSON.parse(Buffer.from(raw,'base64').toString('utf8'))}catch{throw new Error('GOOGLE_SERVICE_ACCOUNT_JSON tidak valid.')}}const now=Math.floor(Date.now()/1000),payload={iss:sa.client_email,scope:'https://www.googleapis.com/auth/drive.readonly',aud:'https://oauth2.googleapis.com/token',iat:now,exp:now+3500},head={alg:'RS256',typ:'JWT'},unsigned=b64(JSON.stringify(head))+'.'+b64(JSON.stringify(payload)),sig=crypto.sign('RSA-SHA256',Buffer.from(unsigned),sa.private_key).toString('base64url');const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:unsigned+'.'+sig})});const j=await r.json();if(!r.ok||!j.access_token)throw new Error('Token Google Drive gagal dibuat.');return j.access_token}
function isXlsx(b){return b&&b.length>4&&b[0]===0x50&&b[1]===0x4b}
async function driveBuffer(){for(const u of [`https://drive.usercontent.google.com/download?id=${FILE_ID}&export=download&confirm=t`,`https://drive.google.com/uc?export=download&id=${FILE_ID}&confirm=t`]){try{const r=await fetch(u,{redirect:'follow'}),b=Buffer.from(await r.arrayBuffer());if(r.ok&&isXlsx(b))return b}catch{}}const tok=await googleToken();if(!tok)throw new Error('Kredensial server Google Drive belum tersedia.');const r=await fetch(`https://www.googleapis.com/drive/v3/files/${FILE_ID}?alt=media&supportsAllDrives=true`,{headers:{Authorization:`Bearer ${tok}`}}),b=Buffer.from(await r.arrayBuffer());if(!r.ok||!isXlsx(b))throw new Error('Workbook IDP pusat tidak dapat diunduh dari Drive.');return b}
function zipMap(buf){let e=-1;for(let i=buf.length-22;i>=Math.max(0,buf.length-66000);i--)if(buf.readUInt32LE(i)===0x06054b50){e=i;break}if(e<0)throw new Error('XLSX ZIP invalid.');let off=buf.readUInt32LE(e+16),count=buf.readUInt16LE(e+10),m=new Map();for(let n=0;n<count;n++){if(buf.readUInt32LE(off)!==0x02014b50)break;const method=buf.readUInt16LE(off+10),cs=buf.readUInt32LE(off+20),nl=buf.readUInt16LE(off+28),xl=buf.readUInt16LE(off+30),cl=buf.readUInt16LE(off+32),lo=buf.readUInt32LE(off+42),name=buf.slice(off+46,off+46+nl).toString();m.set(name,{method,cs,lo});off+=46+nl+xl+cl}return m}
function entry(buf,map,name){const x=map.get(name);if(!x)return null;const lo=x.lo,nl=buf.readUInt16LE(lo+26),el=buf.readUInt16LE(lo+28),start=lo+30+nl+el,d=buf.slice(start,start+x.cs);return x.method===8?zlib.inflateRawSync(d):d}
function dec(s){return String(s||'').replace(/&quot;/g,'"').replace(/&apos;/g,"'").replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&amp;/g,'&')}
function attr(s,k){const m=String(s).match(new RegExp('(?:^|\\s)'+k+'="([^"]*)"'));return m?dec(m[1]):''}
function col(ref){let n=0;for(const c of (String(ref).match(/^[A-Z]+/)||['A'])[0])n=n*26+c.charCodeAt(0)-64;return n}
function parseBook(buf,needValues=false){const zm=zipMap(buf),wb=entry(buf,zm,'xl/workbook.xml').toString(),rels=entry(buf,zm,'xl/_rels/workbook.xml.rels').toString(),rel={};for(const m of rels.matchAll(/<Relationship\b([^>]*)\/?\s*>/g))rel[attr(m[1],'Id')]=attr(m[1],'Target');let shared=[];const ss=entry(buf,zm,'xl/sharedStrings.xml');if(ss){for(const m of ss.toString().matchAll(/<si\b[^>]*>([\s\S]*?)<\/si>/g)){let t='';for(const q of m[1].matchAll(/<t\b[^>]*>([\s\S]*?)<\/t>/g))t+=dec(q[1]);shared.push(t)}}const sheets=[];for(const m of wb.matchAll(/<sheet\b([^>]*)\/?\s*>/g)){const name=attr(m[1],'name'),rid=attr(m[1],'r:id'),target=rel[rid];if(!target)continue;const p='xl/'+target.replace(/^\//,'').replace(/^xl\//,''),raw=entry(buf,zm,p);if(!raw)continue;const xml=raw.toString(),dm=xml.match(/<dimension\b[^>]*ref="(?:[^:"]+:)?([A-Z]+)(\d+)"/),vals=new Map();let maxR=dm?Number(dm[2]):0,maxC=dm?col(dm[1]):0;for(const c of xml.matchAll(/<c\b([^>]*)>([\s\S]*?)<\/c>/g)){const ref=attr(c[1],'r'),r=Number((ref.match(/\d+$/)||['0'])[0]),cc=col(ref),typ=attr(c[1],'t');maxR=Math.max(maxR,r);maxC=Math.max(maxC,cc);if(r>400||cc>40)continue;let v='',vm=c[2].match(/<v[^>]*>([\s\S]*?)<\/v>/);if(typ==='s'&&vm)v=shared[Number(vm[1])]||'';else if(typ==='inlineStr'){for(const q of c[2].matchAll(/<t\b[^>]*>([\s\S]*?)<\/t>/g))v+=dec(q[1])}else if(vm)v=dec(vm[1]);if(String(v).trim())vals.set(r+':'+cc,v)}let fr=0,fc=0;for(let r=1;r<=Math.min(maxR,250);r++){let yes=false;for(let cc=1;cc<=Math.min(maxC,30);cc++)if(vals.has(r+':'+cc)){yes=true;fc++}if(yes)fr++}let values=null;if(needValues){values=[];for(let r=1;r<=Math.min(maxR,400);r++){const row=[];for(let cc=1;cc<=Math.min(maxC,40);cc++)row.push(vals.get(r+':'+cc)||'');values.push(row)}}sheets.push({sheetName:name,filledRows:fr,filledCells:fc,lastRow:maxR,lastColumn:maxC,truncated:maxR>250||maxC>30,values})}return sheets}
function norm(v){return String(v||'').toLowerCase().replace(/\(\s*20\d{2}\s*\)/g,'').replace(/[^a-z0-9]+/g,' ').trim().replace(/\s+/g,' ')}
function fallback(){return JSON.parse(fs.readFileSync(path.join(process.cwd(),'idp-central-snapshot.json'),'utf8')).sheets}
async function source(needValues){if(cache&&Date.now()-cache.t<300000&&!needValues)return{mode:'drive-live',sheets:cache.s};try{const b=await driveBuffer(),s=parseBook(b,needValues);if(!needValues)cache={t:Date.now(),s};return{mode:'drive-live',sheets:s}}catch(e){return{mode:'verified-cache',sheets:fallback(),warning:e.message}}}
async function awards(c){return q('/rest/v1/awardees?status=neq.Lulus&select=legacy_id,name,angkatan,status&order=name.asc',c)}
module.exports=async function handler(req,res){if(req.method!=='POST')return out(res,405,{success:false,error:'Method not allowed'});try{const{c,role}=await authorize(req),fn=String(req.body?.function||'getIDPOverview'),p=req.body?.params||{},need=fn==='getIDPDetail',src=await source(need),aw=await awards(c),usable=(src.sheets||[]).filter(x=>!['definisi umum','nama etoser'].includes(norm(x.sheetName))),idx=new Map();for(const s of usable){const k=norm(s.sheetName);if(!idx.has(k))idx.set(k,[]);idx.get(k).push(s)}const items=aw.map(a=>{const cands=idx.get(norm(a.name))||[],s=cands.length===1?cands[0]:null;return{id:a.legacy_id,nama:a.name,angkatan:a.angkatan,status:a.status,connected:!!s,sheetName:s?.sheetName||'',filledRows:s?.filledRows||0,filledCells:s?.filledCells||0,lastRow:s?.lastRow||0,lastColumn:s?.lastColumn||0,truncated:!!s?.truncated}});if(fn==='getIDPDetail'){const name=String(p.nama||p.name||''),s=(idx.get(norm(name))||[])[0];if(!s)return out(res,404,{success:false,error:'Tab IDP tidak ditemukan.'});return out(res,200,{success:true,data:{nama:name,sheetName:s.sheetName,sourceName:SOURCE_NAME,sourceId:FILE_ID,sourceMode:src.mode,values:s.values||[],summary:{filledRows:s.filledRows,filledCells:s.filledCells,lastRow:s.lastRow,lastColumn:s.lastColumn},accessRole:role},warning:src.warning||null})}return out(res,200,{success:true,data:{sourceName:SOURCE_NAME,sourceId:FILE_ID,sourceMode:src.mode,totalActive:items.length,connected:items.filter(x=>x.connected).length,missing:items.filter(x=>!x.connected).length,items,accessRole:role,warning:src.warning||null}})}catch(e){console.error('[IDP live]',e);return out(res,e.status||500,{success:false,error:e.message||'Koneksi IDP pusat gagal.'})}}
