const crypto=require('crypto');
const PROJECT_URL='https://weklmapqizeldfdalbgs.supabase.co';
const KEY='sb_publishable_cFm2Jvj2jvFyKcxbGniVWw_PL2SL7HC';
function out(res,status,body){res.status(status).setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(body))}
function token(req){return String(req.headers.authorization||'').replace(/^Bearer\s+/i,'').trim()}
function headers(t,extra={}){return{apikey:KEY,Authorization:`Bearer ${t}`,'Content-Type':'application/json',...extra}}
async function q(path,t,options={}){const r=await fetch(PROJECT_URL+path,{...options,headers:{...headers(t),...(options.headers||{})}});const text=await r.text();let body=null;try{body=text?JSON.parse(text):null}catch{body=text}if(!r.ok)throw new Error(body?.message||body?.error||body?.hint||`Supabase ${r.status}`);return body}
async function identity(t){const user=await q('/auth/v1/user',t);const rows=await q(`/rest/v1/profiles?id=eq.${encodeURIComponent(user.id)}&select=id,full_name,email,role,is_active`,t);const p=rows?.[0];if(!p?.is_active)throw new Error('Akun belum aktif.');return{user,profile:p}}
const canWrite=r=>['superadmin','admin','facilitator','operator'].includes(String(r));const canAdmin=r=>['superadmin','admin'].includes(String(r));
async function awardeeId(ref,t){const v=String(ref||'').trim();if(!v)return null;let rows;if(/^AWD-/i.test(v))rows=await q(`/rest/v1/awardees?legacy_id=eq.${encodeURIComponent(v.toUpperCase())}&select=id`,t);else rows=await q(`/rest/v1/awardees?id=eq.${encodeURIComponent(v)}&select=id`,t);return rows?.[0]?.id||null}
async function nextLegacy(table,prefix,t){const rows=await q(`/rest/v1/${table}?select=legacy_id&legacy_id=like.${encodeURIComponent(prefix+'-*')}`,t);let n=0;(rows||[]).forEach(x=>{const m=String(x.legacy_id||'').match(/(\d+)$/);if(m)n=Math.max(n,Number(m[1]))});return`${prefix}-${String(n+1).padStart(4,'0')}`}
async function insert(table,data,t,select='*'){return q(`/rest/v1/${table}?select=${encodeURIComponent(select)}`,t,{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify([data])})}
async function patch(table,filter,data,t,select='*'){return q(`/rest/v1/${table}?${filter}&select=${encodeURIComponent(select)}`,t,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify(data)})}
const clean=v=>String(v??'').trim();const low=v=>clean(v).toLowerCase();
function idpHeuristic(snapshot){const p=snapshot?.payload||{};const values=Array.isArray(p.values)?p.values:[];const text=values.flat(2).map(x=>clean(x)).filter(Boolean).join(' | ').toLowerCase();const dims={target:/target|tujuan|sasaran/.test(text),aksi:/rencana aksi|action plan|langkah/.test(text),waktu:/waktu|deadline|tenggat|timeline/.test(text),indikator:/indikator|ukuran keberhasilan|output/.test(text),progres:/progres|progress|status/.test(text),dukungan:/dukungan|support|resource|sumber daya/.test(text)};const score=Math.round(Object.values(dims).filter(Boolean).length/6*100);return{available:!!values.length,completeness:score,dimensions:dims,source_sheet:snapshot?.source_sheet_name||null,captured_at:snapshot?.captured_at||null}}
function stableFingerprint(obj){return crypto.createHash('sha256').update(JSON.stringify(obj)).digest('hex')}

module.exports=async function handler(req,res){
 if(req.method!=='POST')return out(res,405,{success:false,error:'Method not allowed'});
 try{
  const t=token(req);if(!t)return out(res,401,{success:false,error:'PIN access session diperlukan.'});const{user,profile}=await identity(t);if(!canWrite(profile.role))return out(res,403,{success:false,error:'Role tidak memiliki izin menulis.'});const fn=String(req.body?.function||''),p=req.body?.params||{};
  if(fn==='saveAwardee'){
   const legacy=clean(p.id_awardee||p.legacy_id).toUpperCase();const values={name:clean(p.nama||p.name),kampus:clean(p.kampus)||null,jurusan:clean(p.jurusan)||null,angkatan:clean(p.angkatan)||null,status:clean(p.status)||'Aktif',motto:clean(p.motto)||null,photo_url:clean(p.photo_url||p.foto)||null,updated_by:user.id};if(!values.name)throw new Error('Nama Awardee wajib diisi.');let row;if(legacy){row=(await patch('awardees',`legacy_id=eq.${encodeURIComponent(legacy)}`,values,t))?.[0]}else{values.legacy_id=await nextLegacy('awardees','AWD',t);values.created_by=user.id;row=(await insert('awardees',values,t))?.[0]}if(!row)throw new Error('Awardee gagal disimpan.');if(clean(p.whatsapp)||clean(p.email)){await q('/rest/v1/awardee_contacts?on_conflict=awardee_id',t,{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify([{awardee_id:row.id,whatsapp:clean(p.whatsapp)||null,email:clean(p.email)||null,updated_by:user.id}])})}return out(res,200,{success:true,data:{id:row.legacy_id||row.id}})
  }
  if(fn==='saveAkademik'){
   const aid=await awardeeId(p.id_awardee,t);if(!aid)throw new Error('Awardee tidak ditemukan.');const sem=Number(p.semester),ipk=Number(String(p.ipk||'').replace(',','.'));if(!(sem>=1&&sem<=14))throw new Error('Semester harus 1–14.');if(!(ipk>=0&&ipk<=4))throw new Error('IPK harus 0–4.');const ex=await q(`/rest/v1/academic_records?awardee_id=eq.${aid}&semester=eq.${sem}&select=id`,t);let row;if(ex?.[0])row=(await patch('academic_records',`id=eq.${ex[0].id}`,{ipk,updated_by:user.id},t))?.[0];else row=(await insert('academic_records',{legacy_id:await nextLegacy('academic_records','AKD',t),awardee_id:aid,semester:sem,ipk,created_by:user.id,updated_by:user.id},t))?.[0];return out(res,200,{success:true,data:row})
  }
  if(fn==='savePrestasi'){
   const aid=await awardeeId(p.id_awardee,t);if(!aid)throw new Error('Awardee tidak ditemukan.');if(!clean(p.prestasi))throw new Error('Nama prestasi wajib diisi.');const row=(await insert('achievements',{legacy_id:await nextLegacy('achievements','PRS',t),awardee_id:aid,achievement_name:clean(p.prestasi),organizer:clean(p.penyelenggara)||null,year:p.tahun?Number(p.tahun):null,level:clean(p.tingkat)||null,category:clean(p.kategori)||null,created_by:user.id,updated_by:user.id},t))?.[0];return out(res,200,{success:true,data:row})
  }
  if(fn==='saveOrganisasi'){
   const aid=await awardeeId(p.id_awardee,t);if(!aid)throw new Error('Awardee tidak ditemukan.');if(!clean(p.nama_organisasi))throw new Error('Nama organisasi wajib diisi.');const row=(await insert('organization_records',{legacy_id:await nextLegacy('organization_records','ORG',t),awardee_id:aid,organization_name:clean(p.nama_organisasi),position:clean(p.jabatan)||null,start_year:p.tahun_mulai?Number(p.tahun_mulai):null,end_year_text:clean(p.tahun_selesai)||null,level:clean(p.tingkat)||null,created_by:user.id,updated_by:user.id},t))?.[0];return out(res,200,{success:true,data:row})
  }
  if(fn==='savePortfolio'){
   const aid=await awardeeId(p.id_awardee,t);if(!aid)throw new Error('Awardee tidak ditemukan.');const ex=await q(`/rest/v1/portfolios?awardee_id=eq.${aid}&select=id,legacy_id`,t);const d={cv_url:clean(p.link_cv)||null,contribution:clean(p.kontribusi)||null,evidence_drive_url:clean(p.link_gdrive)||null,linkedin_url:clean(p.linkedin_url)||null,updated_by:user.id};let row;if(ex?.[0])row=(await patch('portfolios',`id=eq.${ex[0].id}`,d,t))?.[0];else{d.legacy_id=await nextLegacy('portfolios','PRT',t);d.awardee_id=aid;d.created_by=user.id;row=(await insert('portfolios',d,t))?.[0]}return out(res,200,{success:true,data:row})
  }
  if(fn==='savePeriode'){
   if(!canAdmin(profile.role))return out(res,403,{success:false,error:'Hanya admin yang dapat mengelola periode.'});if(!clean(p.nama))throw new Error('Nama periode wajib diisi.');if(clean(p.status).toLowerCase()==='aktif')await patch('development_periods',`status=ilike.${encodeURIComponent('Aktif')}`,{status:'Arsip',updated_by:user.id},t);const row=(await insert('development_periods',{legacy_id:await nextLegacy('development_periods','PRD',t),name:clean(p.nama),start_date:p.mulai||null,end_date:p.selesai||null,status:clean(p.status)||'Aktif',created_by:user.id,updated_by:user.id},t))?.[0];return out(res,200,{success:true,data:row})
  }
  if(fn==='saveKompetensi'){
   const aid=await awardeeId(p.id_awardee,t);if(!aid)throw new Error('Awardee tidak ditemukan.');const lvl=Number(p.level);if(!(lvl>=1&&lvl<=4))throw new Error('Level kompetensi harus 1–4.');const row=(await insert('competencies',{legacy_id:await nextLegacy('competencies','KMP',t),awardee_id:aid,competency:clean(p.kompetensi),level:lvl,evidence:clean(p.evidence),source:'manual',verification_status:clean(p.status_verifikasi)||'Belum diverifikasi',assessed_by:profile.full_name||profile.email,assessed_at:new Date().toISOString().slice(0,10),notes:clean(p.catatan)||null,created_by:user.id,updated_by:user.id},t))?.[0];return out(res,200,{success:true,data:row})
  }
  if(fn==='saveNetworking'){
   const aid=await awardeeId(p.id_awardee,t);if(!aid)throw new Error('Awardee tidak ditemukan.');const row=(await insert('networking_records',{legacy_id:await nextLegacy('networking_records','NET',t),awardee_id:aid,partner_name:clean(p.nama_mitra),institution:clean(p.instansi)||null,outcome:clean(p.outcome)||null,contact_date:p.tanggal||null,created_by:user.id,updated_by:user.id},t))?.[0];return out(res,200,{success:true,data:row})
  }
  if(fn==='saveSpiritual'){
   const aid=await awardeeId(p.id_awardee,t);if(!aid)throw new Error('Awardee tidak ditemukan.');const row=(await insert('spiritual_records',{legacy_id:await nextLegacy('spiritual_records','SPR',t),awardee_id:aid,month_label:clean(p.bulan),kajian_attendance:clean(p.kehadiran_kajian)||null,tahsin_progress:clean(p.progres_tahsin)||null,tilawah_achievement:clean(p.capaian_tilawah)||null,created_by:user.id,updated_by:user.id},t))?.[0];return out(res,200,{success:true,data:row})
  }
  if(fn==='saveFasilitatorProfile'){
   const ex=await q(`/rest/v1/facilitators?user_id=eq.${encodeURIComponent(user.id)}&select=id`,t);const d={name:clean(p.nama||p.name)||profile.full_name||'Fasilitator ETOS',email:clean(p.email)||profile.email||null,whatsapp:clean(p.no_wa||p.whatsapp)||null,wilayah:clean(p.wilayah)||'Palu',bio:clean(p.bio)||null,user_id:user.id};let row;if(ex?.[0])row=(await patch('facilitators',`id=eq.${ex[0].id}`,d,t))?.[0];else row=(await insert('facilitators',d,t))?.[0];return out(res,200,{success:true,data:row})
  }
  if(fn==='archiveAwardee'){
   if(!canAdmin(profile.role))return out(res,403,{success:false,error:'Hanya admin yang dapat mengarsipkan Awardee.'});const legacy=clean(p.id_awardee).toUpperCase();const row=(await patch('awardees',`legacy_id=eq.${encodeURIComponent(legacy)}`,{status:'Arsip',updated_by:user.id},t))?.[0];return out(res,200,{success:true,data:row})
  }
  if(fn==='runRuleAnalysis'){
   const aid=await awardeeId(p.id_awardee,t);if(!aid)throw new Error('Awardee tidak ditemukan.');const [awd,academic,attendance,coaching,assessments,achievements,organizations,reflections,idp,competencies,cases,portfolio]=await Promise.all([
    q(`/rest/v1/awardees?id=eq.${aid}&select=legacy_id,name`,t),q(`/rest/v1/academic_records?awardee_id=eq.${aid}&select=semester,ipk&order=semester.desc.nullslast`,t),q(`/rest/v1/attendance_records?awardee_id=eq.${aid}&select=status`,t),q(`/rest/v1/coaching_sessions?awardee_id=eq.${aid}&select=session_date,follow_up_plan,solution&order=session_date.desc.nullslast&limit=1`,t),q(`/rest/v1/assessments?awardee_id=eq.${aid}&select=needs_checkin,status`,t),q(`/rest/v1/achievements?awardee_id=eq.${aid}&select=id`,t),q(`/rest/v1/organization_records?awardee_id=eq.${aid}&select=id`,t),q(`/rest/v1/reflection_responses?awardee_id=eq.${aid}&select=support_needed,feeling,awareness_finding,action_plan,submitted_at&order=submitted_at.desc.nullslast&limit=12`,t),q(`/rest/v1/idp_snapshots?awardee_id=eq.${aid}&select=payload,captured_at,source_sheet_name&order=captured_at.desc&limit=1`,t),q(`/rest/v1/competencies?awardee_id=eq.${aid}&select=competency,level,verification_status`,t),q(`/rest/v1/mentoring_cases?awardee_id=eq.${aid}&select=status,priority,deadline`,t),q(`/rest/v1/portfolios?awardee_id=eq.${aid}&select=cv_url,evidence_drive_url,linkedin_url`,t)
   ]);
   const latest=academic?.[0]||null,prev=academic?.[1]||null,delta=latest&&prev?Number((Number(latest.ipk)-Number(prev.ipk)).toFixed(2)):null;const total=(attendance||[]).length,hadir=(attendance||[]).filter(x=>x.status==='Hadir').length,pct=total?Math.round(hadir/total*100):null;const idpInfo=idpHeuristic(idp?.[0]);const openCases=(cases||[]).filter(x=>!['selesai','closed','done'].includes(low(x.status)));const highCases=openCases.filter(x=>low(x.priority)==='tinggi');const needCheckin=(assessments||[]).some(x=>x.needs_checkin);const lowCompetencies=(competencies||[]).filter(x=>Number(x.level)<=2);const latestReflection=reflections?.[0]||null;let coachingAge=null;if(coaching?.[0]?.session_date)coachingAge=Math.floor((Date.now()-new Date(coaching[0].session_date).getTime())/86400000);
   let score=0;const attention=[],strengths=[],recommendations=[],questions=[],priority=[];
   if(latest&&Number(latest.ipk)<3){score+=3;attention.push(`IPK terbaru ${Number(latest.ipk).toFixed(2)} di bawah 3,00.`);recommendations.push('Susun rencana pemulihan akademik dan cek hambatan belajar.')}
   else if(latest&&Number(latest.ipk)>=3.5)strengths.push(`IPK terbaru kuat (${Number(latest.ipk).toFixed(2)}).`);
   if(delta!==null&&delta<=-.3){score+=2;attention.push(`IPK turun ${Math.abs(delta).toFixed(2)} dari semester sebelumnya.`)}else if(delta!==null&&delta>=.2)strengths.push(`IPK meningkat ${delta.toFixed(2)}.`);
   if(pct!==null&&pct<70){score+=3;attention.push(`Kehadiran ${pct}% di bawah ambang perhatian.`);recommendations.push('Konfirmasi hambatan kehadiran dan sepakati perbaikan terukur.');priority.push('Pulihkan konsistensi kehadiran.')}
   else if(pct!==null&&pct>=85)strengths.push(`Kehadiran pembinaan konsisten (${pct}%).`);
   if(idpInfo.available&&idpInfo.completeness<70){score+=2;attention.push(`Kelengkapan struktur IDP terdeteksi ${idpInfo.completeness}%.`);recommendations.push('Lengkapi target, aksi, waktu, indikator, progres, dan dukungan pada IDP.')}
   else if(idpInfo.available)strengths.push(`IDP terhubung dengan kelengkapan struktur ${idpInfo.completeness}%.`);else attention.push('Snapshot IDP belum tersedia di Supabase.');
   if(needCheckin){score+=2;attention.push('Asesmen menandai kebutuhan check-in fasilitator.');questions.push('Bagian asesmen mana yang paling ingin kamu bahas dalam sesi pendampingan?')}
   if(coachingAge!==null&&coachingAge>90){score+=1;attention.push(`Tidak ada coaching baru selama ${coachingAge} hari.`);recommendations.push('Jadwalkan coaching lanjutan.')}
   if(coaching?.[0]&&!clean(coaching[0].follow_up_plan)){score+=1;attention.push('Coaching terakhir belum memiliki RTL yang jelas.');recommendations.push('Tetapkan RTL spesifik beserta waktu evaluasinya.')}
   if(highCases.length){score+=Math.min(3,highCases.length*2);attention.push(`${highCases.length} case prioritas tinggi masih terbuka.`);priority.push('Tindak lanjuti case prioritas tinggi.')}
   if(lowCompetencies.length)recommendations.push('Gunakan evidence kompetensi level 1–2 untuk menentukan fokus pengembangan berikutnya.');
   if((achievements||[]).length)strengths.push(`${achievements.length} catatan prestasi tersedia.`);if((organizations||[]).length)strengths.push(`${organizations.length} pengalaman organisasi tersedia.`);
   if(latestReflection?.support_needed&&!/belum membutuhkan/i.test(latestReflection.support_needed)){score+=1;attention.push('Refleksi terakhir menyatakan kebutuhan dukungan.');questions.push('Dukungan seperti apa yang paling membantu untuk langkah berikutnya?')}
   const level=score>=7?'Tinggi':score>=3?'Sedang':'Rendah';if(!questions.length)questions.push('Apa satu langkah paling realistis yang ingin kamu tuntaskan sebelum coaching berikutnya?');if(!priority.length&&recommendations.length)priority.push(recommendations[0]);
   const context={academic,attendance,coaching,assessments,achievements:(achievements||[]).length,organizations:(organizations||[]).length,reflections,idp:idpInfo,competencies,cases,portfolio:portfolio?.[0]||null};const fingerprint=stableFingerprint(context);const previous=await q(`/rest/v1/rule_analyses?awardee_id=eq.${aid}&data_fingerprint=eq.${fingerprint}&select=*&order=analyzed_at.desc&limit=1`,t);if(previous?.[0])return out(res,200,{success:true,data:{...previous[0],reused:true}});
   const result={ringkasan:attention.length?`Perhatian ${level.toLowerCase()}: ${attention.slice(0,3).join(' ')}`:'Belum ada sinyal risiko utama dari data yang tersedia.',tingkat_perhatian:level,skor_perhatian:score,alasan_tingkat_perhatian:attention.join(' '),kekuatan:strengths,area_perhatian:attention,rekomendasi_pendampingan:[...new Set(recommendations)],pertanyaan_coaching:[...new Set(questions)],prioritas_aksi:[...new Set(priority)],indikator_aturan:[latest?`IPK terakhir semester ${latest.semester}: ${Number(latest.ipk).toFixed(2)}.`:'IPK belum tersedia.',pct!==null?`Kehadiran: ${pct}% (${hadir}/${total}).`:'Absensi belum tersedia.',idpInfo.available?`Kelengkapan struktur IDP: ${idpInfo.completeness}%.`:'IDP snapshot belum tersedia.',`${openCases.length} case mentoring terbuka.`],academic:{latest:latest?.ipk??null,previous:prev?.ipk??null,delta},attendance:{hadir,total,pct},idp:idpInfo,reflection:{available:!!latestReflection,latest:latestReflection},competencies:{count:(competencies||[]).length,low_level_count:lowCompetencies.length},cases:{open:openCases.length,high:highCases.length},portfolio:{available:!!portfolio?.[0],cv:!!portfolio?.[0]?.cv_url,evidence:!!portfolio?.[0]?.evidence_drive_url},kualitas_data:{data_tersedia:[academic?.length&&`Akademik (${academic.length} semester)`,total&&`Absensi (${total} catatan)`,idpInfo.available&&'IDP',coaching?.length&&'Coaching',assessments?.length&&'Asesmen',reflections?.length&&'Refleksi',achievements?.length&&`Prestasi (${achievements.length})`,organizations?.length&&`Organisasi (${organizations.length})`].filter(Boolean),data_belum_tersedia:[!academic?.length&&'Akademik',!total&&'Absensi',!idpInfo.available&&'IDP',!coaching?.length&&'Coaching',!reflections?.length&&'Refleksi'].filter(Boolean)},catatan_peninjauan:'Hasil dibuat otomatis berdasarkan aturan dan wajib diverifikasi fasilitator. Tidak boleh digunakan sebagai keputusan hukuman, kelulusan, atau pemberhentian secara otomatis.',requires_facilitator_review:true};
   const legacy='ATO-'+new Date().toISOString().replace(/\D/g,'').slice(0,14)+'-'+Math.floor(Math.random()*900+100);const row=(await insert('rule_analyses',{legacy_id:legacy,awardee_id:aid,awardee_name_snapshot:awd?.[0]?.name||null,analyzed_at:new Date().toISOString(),engine_version:'ETOS-RULES-V2-SUPABASE',data_fingerprint:fingerprint,result,review_status:'belum_ditinjau'},t))?.[0];return out(res,200,{success:true,data:row})
  }
  return out(res,404,{success:false,error:`Fungsi ${fn} tidak tersedia.`});
 }catch(e){console.error('[manage2]',e);return out(res,500,{success:false,error:e.message||String(e)})}
};
