const PROJECT_URL='https://weklmapqizeldfdalbgs.supabase.co';
const PUBLISHABLE_KEY='sb_publishable_cFm2Jvj2jvFyKcxbGniVWw_PL2SL7HC';
const BUCKET='awardee-media';
const MAX_FILE_SIZE=104857600;

const PHOTOS={
 'AWD-0001':'https://drive.google.com/file/d/1eKiE0fwa1oxRxNpGEfn57H3AAfQYwn5B/view?usp=sharing',
 'AWD-0002':'https://drive.google.com/file/d/1-uIJizJgVFd_Oy535syz1-y-6n63Tjm6/view?usp=drive_link',
 'AWD-0003':'https://drive.google.com/file/d/1zPF76U1OVhprMTq2_facC8qUpAWvsBnu/view?usp=drive_link',
 'AWD-0004':'https://drive.google.com/file/d/1svCFI0Dk0I12mJXZfeYNL7KtQ3d2QBf1/view?usp=drive_link',
 'AWD-0005':'https://drive.google.com/file/d/1J4wmNCHEDZVyW9QhnMyMqYa8HE6nUUV1/view?usp=drive_link',
 'AWD-0006':'https://drive.google.com/file/d/1zm736nNMd7Nb4Fz412vAi9NbwVqQdy_G/view?usp=sharing',
 'AWD-0007':'https://drive.google.com/file/d/1sW6m7OmyRXCcCQbGeVZ7mMLneNeW8WPI/view?usp=sharing',
 'AWD-0008':'https://drive.google.com/file/d/1CuFAP8c6OXYbc_U9J7nwAXyhPzo1NSmM/view?usp=drivesdk',
 'AWD-0009':'https://drive.google.com/file/d/1W6Ck7Z9BZl-WvhyoBpNDa69pifAXyIYE/view?usp=drivesdk',
 'AWD-0010':'https://drive.google.com/file/d/1GxkIMIHyq7iuc8K23s1cTRVIYaCthaxS/view?usp=drivesdk',
 'AWD-0011':'https://drive.google.com/file/d/1c-fybQvf4MFsx9nzBHNUn93SPMLFtyxz/view?usp=drivesdk',
 'AWD-0012':'https://drive.google.com/file/d/1B4WN_hOZpa2znBWFBwXkVpHKz5FtOZwj/view?usp=drivesdk',
 'AWD-0013':'https://drive.google.com/file/d/1cVaQfE3Y-uh_h_mYZH99c3GxdGU2dI5R/view?usp=drivesdk',
 'AWD-0014':'https://drive.google.com/file/d/1SEC_GRNVVvDIRlbrCFSMFiQ8ZE5RzaLD/view?usp=drivesdk',
 'AWD-0015':'https://drive.google.com/file/d/1igJF4AosnMzK3ymcarttdeYAzjreqvwn/view?usp=drivesdk',
 'AWD-0016':'https://drive.google.com/file/d/1yt3q8qBAHjdA1tL5xX46uLqgU4V2lWEY/view?usp=drivesdk'
};
const PORTFOLIOS={
 'AWD-0009':{legacy_id:'PRT-0NaN',cv_url:'https://docs.google.com/document/d/1MTMyouZjgWOVXZhzIVzIM657YBALhXT2zbCaT1Pgmnk/edit?usp=sharing',contribution:'Kerja di UIN',evidence_drive_url:null},
 'AWD-0006':{legacy_id:'PRT-0001',cv_url:'https://drive.google.com/file/d/1fmYGXA3b58kdQuG1J_81w9MTOzXDbqF1/view?usp=drive_link',contribution:'Dalam Interview Kerja',evidence_drive_url:'https://drive.google.com/file/d/1sFYQkvpymstDeQIaQlsMTbyWpV95pqwG/view?usp=sharing'},
 'AWD-0001':{legacy_id:'PRT-0002',cv_url:'https://drive.google.com/file/d/1Br4kaKSN3vUDHd6-SYL9FLCdGzc_B3IX/view?usp=sharing',contribution:'Mecanhical Engineer PT. Korea Energy Indonesia',evidence_drive_url:null},
 'AWD-0004':{legacy_id:'PRT-0003',cv_url:null,contribution:'Guru SDIT Bina Insan Palu',evidence_drive_url:null}
};

function reply(res,status,body){res.status(status);res.setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(body))}
function bearer(req){return String(req.headers.authorization||'').replace(/^Bearer\s+/i,'').trim()}
function driveId(url){const s=String(url||'');const m=s.match(/\/d\/([A-Za-z0-9_-]+)/)||s.match(/[?&]id=([A-Za-z0-9_-]+)/);return m?m[1]:''}
function roleAllowed(role){return ['superadmin','admin','operator','facilitator'].includes(String(role||'').toLowerCase())}
function extFromType(type,kind){type=String(type||'').toLowerCase();if(type.includes('png'))return'png';if(type.includes('webp'))return'webp';if(type.includes('gif'))return'gif';if(type.includes('pdf'))return'pdf';return kind==='photo'?'jpg':'bin'}
function publicUrl(path){return `${PROJECT_URL}/storage/v1/object/public/${BUCKET}/${path.split('/').map(encodeURIComponent).join('/')}`}
async function api(path,authToken,apiKey=PUBLISHABLE_KEY,options={}){const r=await fetch(PROJECT_URL+path,{...options,headers:{apikey:apiKey,Authorization:`Bearer ${authToken}`,'Content-Type':'application/json',...(options.headers||{})}});const text=await r.text();let body=null;try{body=text?JSON.parse(text):null}catch{body=text}if(!r.ok){const msg=body?.message||body?.error||body?.hint||`Supabase ${r.status}`;const e=new Error(msg);e.status=r.status;throw e}return body}
async function identity(token){const user=await api('/auth/v1/user',token);const rows=await api(`/rest/v1/profiles?id=eq.${encodeURIComponent(user.id)}&select=id,role,is_active`,token);const p=rows?.[0];if(!p?.is_active||!roleAllowed(p.role))throw new Error('Session tidak memiliki izin migrasi media.');return{user,profile:p}}
async function ensureBucket(authToken,apiKey,canCreate){let exists=false;try{const r=await fetch(`${PROJECT_URL}/storage/v1/bucket/${BUCKET}`,{headers:{apikey:apiKey,Authorization:`Bearer ${authToken}`}});exists=r.ok}catch{}if(exists)return true;if(!canCreate)return false;const r=await fetch(`${PROJECT_URL}/storage/v1/bucket`,{method:'POST',headers:{apikey:apiKey,Authorization:`Bearer ${authToken}`,'Content-Type':'application/json'},body:JSON.stringify({id:BUCKET,name:BUCKET,public:true,file_size_limit:MAX_FILE_SIZE})});if(!r.ok){const t=await r.text();throw new Error(`Bucket Supabase gagal dibuat: ${t||r.status}`)}return true}
async function downloadDrive(url,kind){const id=driveId(url);if(!id)throw new Error('ID file Drive tidak ditemukan.');const isDoc=/docs\.google\.com\/document/i.test(url);const targets=isDoc?[`https://docs.google.com/document/d/${id}/export?format=pdf`]:[`https://drive.usercontent.google.com/download?id=${id}&export=download&confirm=t`,`https://drive.google.com/uc?export=download&id=${id}&confirm=t`];let last='';for(const u of targets){try{const r=await fetch(u,{redirect:'follow'});const type=String(r.headers.get('content-type')||'');if(r.ok&&!type.includes('text/html')){const ab=await r.arrayBuffer();if(ab.byteLength>0){if(ab.byteLength>MAX_FILE_SIZE)throw new Error('File melebihi 100 MB.');return{bytes:Buffer.from(ab),type:type||((kind==='photo')?'image/jpeg':'application/octet-stream')}}last=`HTTP ${r.status} ${type}`}catch(e){last=e.message}}throw new Error(`File Drive tidak dapat diunduh (${last||id}).`)}
async function uploadObject(path,file,authToken,apiKey){const r=await fetch(`${PROJECT_URL}/storage/v1/object/${BUCKET}/${path}`,{method:'POST',headers:{apikey:apiKey,Authorization:`Bearer ${authToken}`,'Content-Type':file.type,'x-upsert':'true','Cache-Control':'3600'},body:file.bytes});if(!r.ok){const t=await r.text();throw new Error(`Upload ${path} gagal: ${t||r.status}`)}return publicUrl(path)}
async function awardeeRow(legacy,token,key){const rows=await api(`/rest/v1/awardees?legacy_id=eq.${encodeURIComponent(legacy)}&select=id,legacy_id,photo_url`,token,key);return rows?.[0]||null}
async function patchAwardee(id,data,token,key){return api(`/rest/v1/awardees?id=eq.${encodeURIComponent(id)}`,token,key,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(data)})}
async function upsertPortfolio(awardeeId,legacy,data,token,key){const rows=await api(`/rest/v1/portfolios?awardee_id=eq.${encodeURIComponent(awardeeId)}&select=id`,token,key);if(rows?.[0])return api(`/rest/v1/portfolios?id=eq.${encodeURIComponent(rows[0].id)}`,token,key,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(data)});return api('/rest/v1/portfolios',token,key,{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify([{awardee_id:awardeeId,legacy_id:legacy,...data}])})}

module.exports=async function handler(req,res){if(req.method!=='POST')return reply(res,405,{success:false,error:'Method not allowed'});const caller=bearer(req);if(!caller)return reply(res,401,{success:false,error:'Session PIN diperlukan.'});try{await identity(caller);const service=String(process.env.SUPABASE_SERVICE_ROLE_KEY||'').trim();const authToken=service||caller,apiKey=service||PUBLISHABLE_KEY;const bucketReady=await ensureBucket(authToken,apiKey,!!service);if(!bucketReady)return reply(res,409,{success:false,error:'Bucket awardee-media belum tersedia. Tambahkan service credential server-side atau buat bucket awardee-media sekali di Supabase.'});let uploaded=0,updated=0;const errors=[];for(const [legacy,url] of Object.entries(PHOTOS)){try{const row=await awardeeRow(legacy,authToken,apiKey);if(!row)throw new Error('Awardee belum ada di Supabase.');if(String(row.photo_url||'').includes('/storage/v1/object/public/'+BUCKET+'/'))continue;const file=await downloadDrive(url,'photo');const ext=extFromType(file.type,'photo');const path=`photos/${legacy.toLowerCase()}.${ext}`;const target=await uploadObject(path,file,authToken,apiKey);uploaded++;await patchAwardee(row.id,{photo_url:target},authToken,apiKey);updated++}catch(e){errors.push({item:legacy,type:'photo',error:e.message})}}for(const [legacy,p] of Object.entries(PORTFOLIOS)){try{const row=await awardeeRow(legacy,authToken,apiKey);if(!row)throw new Error('Awardee belum ada di Supabase.');let cv=p.cv_url,evidence=p.evidence_drive_url;if(cv&&!String(cv).includes('/storage/v1/object/public/'+BUCKET+'/')){const f=await downloadDrive(cv,'portfolio');const ext=extFromType(f.type,'portfolio');cv=await uploadObject(`portfolio/${legacy.toLowerCase()}-cv.${ext}`,f,authToken,apiKey);uploaded++}if(evidence&&!String(evidence).includes('/storage/v1/object/public/'+BUCKET+'/')){const f=await downloadDrive(evidence,'portfolio');const ext=extFromType(f.type,'portfolio');evidence=await uploadObject(`portfolio/${legacy.toLowerCase()}-evidence.${ext}`,f,authToken,apiKey);uploaded++}await upsertPortfolio(row.id,p.legacy_id,{cv_url:cv||null,contribution:p.contribution||null,evidence_drive_url:evidence||null},authToken,apiKey);updated++}catch(e){errors.push({item:legacy,type:'portfolio',error:e.message})}}return reply(res,200,{success:true,data:{uploaded,updated,failed:errors.length,errors}})}catch(e){console.error('[media-sync]',e);return reply(res,500,{success:false,error:e.message||'Migrasi media gagal.'})}};