const crypto=require('crypto');
const PROJECT_URL='https://weklmapqizeldfdalbgs.supabase.co';
const PUBLISHABLE_KEY='sb_publishable_cFm2Jvj2jvFyKcxbGniVWw_PL2SL7HC';
const INTERNAL_AUTH_EMAIL=String(process.env.ETOS_INTERNAL_AUTH_EMAIL||'shadiqalfatih2@gmail.com').trim();
const PIN_HASH=String(process.env.ETOS_ACCESS_PIN_HASH||'e811d29b1b60cc0f4ffc2e65ffc4b14c38415da9c7b1cc73f73a97c67725a490').trim();
const buckets=new Map(),WINDOW_MS=15*60*1000,MAX_ATTEMPTS=5;
function reply(res,status,body,extra={}){res.status(status);res.setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');res.setHeader('Pragma','no-cache');Object.entries(extra).forEach(([k,v])=>res.setHeader(k,v));res.end(JSON.stringify(body))}
function clientKey(req){return String(req.headers['x-forwarded-for']||'').split(',')[0].trim()||String(req.headers['x-real-ip']||req.socket?.remoteAddress||'unknown')}
function rateState(key){const now=Date.now();let x=buckets.get(key);if(!x||now-x.startedAt>=WINDOW_MS){x={startedAt:now,count:0};buckets.set(key,x)}return x}
function validPin(pin){const hash=crypto.createHash('sha256').update(String(pin||'')).digest('hex');const a=Buffer.from(hash,'hex'),b=Buffer.from(PIN_HASH,'hex');return a.length===b.length&&crypto.timingSafeEqual(a,b)}
async function request(path,{method='POST',body,key=PUBLISHABLE_KEY,token=key,headers={}}={}){const opts={method,headers:{apikey:key,Authorization:`Bearer ${token}`,'Content-Type':'application/json',...headers}};if(body!==undefined)opts.body=JSON.stringify(body);const r=await fetch(PROJECT_URL+path,opts);const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={message:text}}return{ok:r.ok,status:r.status,data}}
async function passwordGrant(pin){return request('/auth/v1/token?grant_type=password',{body:{email:INTERNAL_AUTH_EMAIL,password:pin},key:PUBLISHABLE_KEY,token:PUBLISHABLE_KEY})}
async function ensureOperationalUser(pin){const service=String(process.env.SUPABASE_SERVICE_ROLE_KEY||'').trim();if(!service)return{ok:false,reason:'service_role_missing'};
 let listed=await request('/auth/v1/admin/users?page=1&per_page=1000',{method:'GET',key:service,token:service});if(!listed.ok)throw new Error('Auth admin tidak dapat membaca user operasional.');
 let users=Array.isArray(listed.data?.users)?listed.data.users:(Array.isArray(listed.data)?listed.data:[]);let user=users.find(u=>String(u.email||'').toLowerCase()===INTERNAL_AUTH_EMAIL.toLowerCase());
 const attrs={email:INTERNAL_AUTH_EMAIL,password:pin,email_confirm:true,user_metadata:{display_name:'ETOS ID Palu'},app_metadata:{role:'operator'}};
 if(!user){const created=await request('/auth/v1/admin/users',{method:'POST',body:attrs,key:service,token:service});if(!created.ok)throw new Error(created.data?.message||created.data?.error||'Akun operasional gagal dibuat.');user=created.data?.user||created.data}else{const updated=await request('/auth/v1/admin/users/'+encodeURIComponent(user.id),{method:'PUT',body:{password:pin,email_confirm:true,app_metadata:{...(user.app_metadata||{}),role:'operator'}},key:service,token:service});if(!updated.ok)throw new Error(updated.data?.message||updated.data?.error||'Akun operasional gagal diaktifkan.');user=updated.data?.user||updated.data||user}
 if(!user?.id)throw new Error('ID akun operasional tidak tersedia.');
 const profile=[{id:user.id,full_name:'ETOS ID Palu Operator',email:INTERNAL_AUTH_EMAIL,role:'operator',is_active:true}];const prof=await request('/rest/v1/profiles?on_conflict=id',{method:'POST',body:profile,key:service,token:service,headers:{Prefer:'resolution=merge-duplicates,return=minimal'}});if(!prof.ok)throw new Error(prof.data?.message||prof.data?.error||'Profil operasional gagal diaktifkan.');return{ok:true,userId:user.id}}
module.exports=async function handler(req,res){if(req.method!=='POST')return reply(res,405,{success:false,error:'Method not allowed'});const key=clientKey(req),rate=rateState(key),now=Date.now();if(rate.count>=MAX_ATTEMPTS){const retry=Math.max(1,Math.ceil((WINDOW_MS-(now-rate.startedAt))/1000));return reply(res,429,{success:false,error:'Terlalu banyak percobaan. Coba lagi beberapa menit.'},{'Retry-After':String(retry)})}const pin=String(req.body?.pin||'').trim();if(!/^\d{6}$/.test(pin)||!validPin(pin)){rate.count++;return reply(res,401,{success:false,error:'PIN tidak sesuai.'})}try{let auth=await passwordGrant(pin);if(!auth.ok||!auth.data?.access_token||!auth.data?.refresh_token){await ensureOperationalUser(pin);auth=await passwordGrant(pin)}if(!auth.ok||!auth.data?.access_token||!auth.data?.refresh_token){rate.count++;return reply(res,503,{success:false,error:'Akses operasional belum dapat dibuka. Konfigurasi Auth server perlu diperiksa.'})}buckets.delete(key);return reply(res,200,{success:true,data:{access_token:auth.data.access_token,refresh_token:auth.data.refresh_token,expires_in:auth.data.expires_in,token_type:auth.data.token_type||'bearer'}})}catch(e){console.error('[PIN login]',e&&e.message?e.message:e);return reply(res,503,{success:false,error:'Layanan akses sedang tidak tersedia.'})}}
