const crypto=require('crypto');
const PROJECT_URL='https://weklmapqizeldfdalbgs.supabase.co';
const PUBLISHABLE_KEY='sb_publishable_cFm2Jvj2jvFyKcxbGniVWw_PL2SL7HC';
const INTERNAL_AUTH_EMAIL=String(process.env.ETOS_INTERNAL_AUTH_EMAIL||'operator@internal.etosidpalu.web.id').trim();
const PIN_HASH=String(process.env.ETOS_ACCESS_PIN_HASH||'e811d29b1b60cc0f4ffc2e65ffc4b14c38415da9c7b1cc73f73a97c67725a490').trim();
const buckets=new Map(),WINDOW_MS=15*60*1000,MAX_ATTEMPTS=5;
function reply(res,status,body,extra={}){res.status(status);res.setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');res.setHeader('Pragma','no-cache');Object.entries(extra).forEach(([k,v])=>res.setHeader(k,v));res.end(JSON.stringify(body))}
function clientKey(req){return String(req.headers['x-forwarded-for']||'').split(',')[0].trim()||String(req.headers['x-real-ip']||req.socket?.remoteAddress||'unknown')}
function rateState(key){const now=Date.now();let x=buckets.get(key);if(!x||now-x.startedAt>=WINDOW_MS){x={startedAt:now,count:0};buckets.set(key,x)}return x}
function validPin(pin){const hash=crypto.createHash('sha256').update(String(pin||'')).digest('hex');const a=Buffer.from(hash,'hex'),b=Buffer.from(PIN_HASH,'hex');return a.length===b.length&&crypto.timingSafeEqual(a,b)}
function isOpaqueKey(v){return /^sb_(secret|publishable)_/i.test(String(v||''))}
function apiHeaders(apiKey,token,extra={}){const h={apikey:apiKey,'Content-Type':'application/json',...extra};if(token&&!isOpaqueKey(token))h.Authorization=`Bearer ${token}`;return h}
async function request(path,{method='POST',body,key=PUBLISHABLE_KEY,token=null,headers={}}={}){const opts={method,headers:apiHeaders(key,token,headers)};if(body!==undefined)opts.body=JSON.stringify(body);const r=await fetch(PROJECT_URL+path,opts);const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={message:text}}return{ok:r.ok,status:r.status,data}}
async function passwordGrant(pin){return request('/auth/v1/token?grant_type=password',{body:{email:INTERNAL_AUTH_EMAIL,password:pin},key:PUBLISHABLE_KEY})}
async function ensureOperationalUser(pin){const service=String(process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY||'').trim();if(!service){const e=new Error('Server credential belum tersedia.');e.code='SERVICE_KEY_MISSING';throw e}
 const legacyToken=isOpaqueKey(service)?null:service;
 const listed=await request('/auth/v1/admin/users?page=1&per_page=1000',{method:'GET',key:service,token:legacyToken});if(!listed.ok){const e=new Error(listed.data?.message||listed.data?.error||`Auth admin HTTP ${listed.status}`);e.code='AUTH_ADMIN_DENIED';throw e}
 const users=Array.isArray(listed.data?.users)?listed.data.users:(Array.isArray(listed.data)?listed.data:[]);let user=users.find(u=>String(u.email||'').toLowerCase()===INTERNAL_AUTH_EMAIL.toLowerCase());
 const attrs={email:INTERNAL_AUTH_EMAIL,password:pin,email_confirm:true,user_metadata:{display_name:'ETOS ID Palu'},app_metadata:{role:'operator'}};
 if(!user){const created=await request('/auth/v1/admin/users',{method:'POST',body:attrs,key:service,token:legacyToken});if(!created.ok){const e=new Error(created.data?.message||created.data?.error||`Create user HTTP ${created.status}`);e.code='AUTH_CREATE_FAILED';throw e}user=created.data?.user||created.data}else{const updated=await request('/auth/v1/admin/users/'+encodeURIComponent(user.id),{method:'PUT',body:{password:pin,email_confirm:true,app_metadata:{...(user.app_metadata||{}),role:'operator'}},key:service,token:legacyToken});if(!updated.ok){const e=new Error(updated.data?.message||updated.data?.error||`Update user HTTP ${updated.status}`);e.code='AUTH_UPDATE_FAILED';throw e}user=updated.data?.user||updated.data||user}
 if(!user?.id){const e=new Error('ID akun operasional tidak tersedia.');e.code='AUTH_USER_ID_MISSING';throw e}
 const profile=[{id:user.id,full_name:'ETOS ID Palu Operator',email:INTERNAL_AUTH_EMAIL,role:'operator',is_active:true}];const prof=await request('/rest/v1/profiles?on_conflict=id',{method:'POST',body:profile,key:service,token:legacyToken,headers:{Prefer:'resolution=merge-duplicates,return=minimal'}});if(!prof.ok){const e=new Error(prof.data?.message||prof.data?.error||`Profile HTTP ${prof.status}`);e.code='PROFILE_UPSERT_FAILED';throw e}return{ok:true,userId:user.id}}
module.exports=async function handler(req,res){if(req.method!=='POST')return reply(res,405,{success:false,error:'Method not allowed'});const key=clientKey(req),rate=rateState(key),now=Date.now();if(rate.count>=MAX_ATTEMPTS){const retry=Math.max(1,Math.ceil((WINDOW_MS-(now-rate.startedAt))/1000));return reply(res,429,{success:false,error:'Terlalu banyak percobaan. Coba lagi beberapa menit.'},{'Retry-After':String(retry)})}const pin=String(req.body?.pin||'').trim();if(!/^\d{6}$/.test(pin)||!validPin(pin)){rate.count++;return reply(res,401,{success:false,error:'PIN tidak sesuai.'})}try{let auth=await passwordGrant(pin);if(!auth.ok||!auth.data?.access_token||!auth.data?.refresh_token){await ensureOperationalUser(pin);auth=await passwordGrant(pin)}if(!auth.ok||!auth.data?.access_token||!auth.data?.refresh_token){rate.count++;return reply(res,503,{success:false,error:'Session operasional belum dapat diterbitkan.',code:'PASSWORD_GRANT_FAILED'})}buckets.delete(key);return reply(res,200,{success:true,data:{access_token:auth.data.access_token,refresh_token:auth.data.refresh_token,expires_in:auth.data.expires_in,token_type:auth.data.token_type||'bearer'}})}catch(e){console.error('[PIN login]',e?.code||'AUTH_ERROR',e&&e.message?e.message:e);const safe={SERVICE_KEY_MISSING:'Credential server belum terbaca oleh deployment.',AUTH_ADMIN_DENIED:'Credential server tidak diterima Supabase Auth.',AUTH_CREATE_FAILED:'Akun operasional gagal dibuat.',AUTH_UPDATE_FAILED:'Akun operasional gagal diaktifkan.',PROFILE_UPSERT_FAILED:'Profil akses operasional gagal disinkronkan.'};return reply(res,503,{success:false,error:safe[e?.code]||'Layanan akses sedang tidak tersedia.',code:e?.code||'AUTH_ERROR'})}}
