const crypto=require('crypto');
const PROJECT_URL='https://weklmapqizeldfdalbgs.supabase.co';
const PUBLISHABLE_KEY='sb_publishable_cFm2Jvj2jvFyKcxbGniVWw_PL2SL7HC';
const INTERNAL_AUTH_EMAIL='shadiqalfatih2@gmail.com';
const PIN_HASH='e811d29b1b60cc0f4ffc2e65ffc4b14c38415da9c7b1cc73f73a97c67725a490';
const buckets=new Map(),WINDOW_MS=15*60*1000,MAX_ATTEMPTS=5;
function reply(res,status,body,extra={}){res.status(status);res.setHeader('Content-Type','application/json');res.setHeader('Cache-Control','no-store');res.setHeader('Pragma','no-cache');Object.entries(extra).forEach(([k,v])=>res.setHeader(k,v));res.end(JSON.stringify(body))}
function clientKey(req){return String(req.headers['x-forwarded-for']||'').split(',')[0].trim()||String(req.headers['x-real-ip']||req.socket?.remoteAddress||'unknown')}
function rateState(key){const now=Date.now();let x=buckets.get(key);if(!x||now-x.startedAt>=WINDOW_MS){x={startedAt:now,count:0};buckets.set(key,x)}return x}
function validPin(pin){const hash=crypto.createHash('sha256').update(String(pin||'')).digest('hex');return crypto.timingSafeEqual(Buffer.from(hash,'hex'),Buffer.from(PIN_HASH,'hex'))}
async function authRequest(path,body){const r=await fetch(PROJECT_URL+path,{method:'POST',headers:{'Content-Type':'application/json',apikey:PUBLISHABLE_KEY},body:JSON.stringify(body)});const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{}return{ok:r.ok,data}}
module.exports=async function handler(req,res){if(req.method!=='POST')return reply(res,405,{success:false,error:'Method not allowed'});const key=clientKey(req),rate=rateState(key),now=Date.now();if(rate.count>=MAX_ATTEMPTS){const retry=Math.max(1,Math.ceil((WINDOW_MS-(now-rate.startedAt))/1000));return reply(res,429,{success:false,error:'Terlalu banyak percobaan. Coba lagi beberapa menit.'},{'Retry-After':String(retry)})}const pin=String(req.body?.pin||'').trim();if(!/^\d{6}$/.test(pin)||!validPin(pin)){rate.count++;return reply(res,401,{success:false,error:'PIN tidak sesuai.'})}try{let auth=await authRequest('/auth/v1/token?grant_type=password',{email:INTERNAL_AUTH_EMAIL,password:pin});if(!auth.ok||!auth.data?.access_token){const signup=await authRequest('/auth/v1/signup',{email:INTERNAL_AUTH_EMAIL,password:pin,data:{display_name:'ETOS ID Palu'}});if(signup.ok&&signup.data?.access_token)auth={ok:true,data:signup.data};else auth=await authRequest('/auth/v1/token?grant_type=password',{email:INTERNAL_AUTH_EMAIL,password:pin})}if(!auth.ok||!auth.data?.access_token||!auth.data?.refresh_token){rate.count++;return reply(res,503,{success:false,error:'PIN 932000 sudah dikenali server, tetapi akun Auth operasional belum menghasilkan session. Periksa aktivasi akun Supabase Auth.'})}buckets.delete(key);return reply(res,200,{success:true,data:{access_token:auth.data.access_token,refresh_token:auth.data.refresh_token,expires_in:auth.data.expires_in,token_type:auth.data.token_type||'bearer'}})}catch(e){console.error('[PIN login]',e);return reply(res,503,{success:false,error:'Layanan akses sedang tidak tersedia.'})}}
