const PROJECT_URL='https://weklmapqizeldfdalbgs.supabase.co';
const KEY='sb_publishable_cFm2Jvj2jvFyKcxbGniVWw_PL2SL7HC';
const SOURCE={name:'DASHBOARD AWARDEE ETOS ID PALU',fileId:'1TEIvSxhSPQsvEO8tMM_Ym2ZDmZ3rb8c__L4HYSKPGm4',modifiedAt:'2026-09-01T10:32:24.000Z'};
const EXPECTED={awardees:16,academic_records:61,organization_records:2,achievements:19,coaching_sessions:0,assessments:1,rule_analyses:3,reflection_forms:1,reflection_responses:0,facilitators:1,competencies:0,mentoring_cases:0,spiritual_records:0,networking_records:0,portfolios:4};
const TABLES=['awardees','awardee_contacts','academic_records','organization_records','achievements','spiritual_records','coaching_sessions','networking_records','portfolios','assessments','competencies','mentoring_cases','rule_analyses','development_periods','attendance_sessions','attendance_records','reflection_forms','reflection_responses','facilitators','idp_external_sources','idp_snapshots'];
function out(res,status,body){res.status(status);res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(body))}
function token(req){return String(req.headers.authorization||'').replace(/^Bearer\s+/i,'').trim()}
function headers(t,extra={}){return{apikey:KEY,Authorization:`Bearer ${t}`,'Content-Type':'application/json',...extra}}
async function raw(path,t,options={}){const r=await fetch(PROJECT_URL+path,{...options,headers:{...headers(t),...(options.headers||{})}});const text=await r.text();let body=null;try{body=text?JSON.parse(text):null}catch{body=text}if(!r.ok)throw new Error(body?.message||body?.error||body?.hint||`Supabase ${r.status}`);return{body,headers:r.headers,status:r.status}}
async function q(path,t,options={}){return(await raw(path,t,options)).body}
async function identity(t){const user=await q('/auth/v1/user',t);const rows=await q(`/rest/v1/profiles?id=eq.${encodeURIComponent(user.id)}&select=id,full_name,email,role,is_active`,t);const p=rows?.[0];if(!p?.is_active)throw new Error('Akun belum aktif.');if(!['superadmin','admin'].includes(String(p.role)))throw new Error('System Center hanya tersedia untuk admin.');return{user,profile:p}}
async function countTable(table,t){const r=await raw(`/rest/v1/${table}?select=id&limit=1`,t,{headers:{Prefer:'count=exact'}});const cr=r.headers.get('content-range')||'';const m=cr.match(/\/(\d+|\*)$/);return m&&m[1]!=='*'?Number(m[1]):Array.isArray(r.body)?r.body.length:0}
async function health(t){const counts={};for(const table of TABLES){try{counts[table]=await countTable(table,t)}catch(e){counts[table]=null}}
 const reconciliation=Object.entries(EXPECTED).map(([table,expected])=>{const actual=counts[table];return{table,expected,actual,ok:actual===expected,note:table==='portfolios'?'4 portfolio terhubung; 1 URL LinkedIn legacy tanpa Awardee disimpan sebagai isu migrasi, bukan record relasional.':table==='coaching_sessions'?'16 row legacy kosong tidak dihitung sebagai sesi coaching substantif.':null}});
 const exactOk=reconciliation.every(x=>x.ok);
 return{generatedAt:new Date().toISOString(),source:SOURCE,counts,reconciliation,normalizedParity:exactOk,notes:['Periode PRD-0002 dapat memiliki satu compatibility row di Supabase karena form refleksi legacy mereferensikannya walau sheet Periode_Pembinaan sumber kosong.','Placeholder legacy tidak dihitung sebagai transaksi substantif.']};}
async function audit(t){try{return await q('/rest/v1/audit_logs?select=id,actor_id,action,table_name,record_id,created_at&order=created_at.desc&limit=100',t)}catch(e){return{unavailable:true,error:e.message,items:[]}}}
async function migration(t){let batches=[],issues=[];try{batches=await q('/rest/v1/migration_batches?select=*&order=started_at.desc&limit=20',t)}catch(e){}try{issues=await q('/rest/v1/migration_issues?select=*&order=created_at.desc&limit=200',t)}catch(e){}return{batches,issues}}
async function backup(t){const data={meta:{app:'ETOS ID Palu',format:'ETOS-JSON-SNAPSHOT-V1',generatedAt:new Date().toISOString(),source:SOURCE},tables:{}};for(const table of TABLES){try{data.tables[table]=await q(`/rest/v1/${table}?select=*`,t)}catch(e){data.tables[table]={_error:e.message}}}return data}
module.exports=async function handler(req,res){if(req.method!=='POST')return out(res,405,{success:false,error:'Method not allowed'});try{const t=token(req);if(!t)return out(res,401,{success:false,error:'Session admin diperlukan.'});await identity(t);const fn=String(req.body?.function||'health');if(fn==='health')return out(res,200,{success:true,data:await health(t)});if(fn==='audit')return out(res,200,{success:true,data:await audit(t)});if(fn==='migration')return out(res,200,{success:true,data:await migration(t)});if(fn==='backup')return out(res,200,{success:true,data:await backup(t)});return out(res,404,{success:false,error:'Fungsi System Center tidak tersedia.'})}catch(e){console.error('[system]',e);return out(res,500,{success:false,error:e.message||String(e)})}}
