const PROJECT_URL='https://weklmapqizeldfdalbgs.supabase.co';
const KEY='sb_publishable_cFm2Jvj2jvFyKcxbGniVWw_PL2SL7HC';
const SOURCE={name:'DASHBOARD AWARDEE ETOS ID PALU',fileId:'1TEIvSxhSPQsvEO8tMM_Ym2ZDmZ3rb8c__L4HYSKPGm4',auditedAt:'2026-09-07T06:55:00+08:00'};
const EXPECTED={awardees:16,academic_records:54,organization_records:2,achievements:19,coaching_sessions:0,assessments:1,rule_analyses:3,reflection_forms:1,reflection_responses:0,facilitators:1,competencies:0,mentoring_cases:0,spiritual_records:0,networking_records:0,portfolios:3,attendance_sessions:0,attendance_records:0};
const TABLES=['awardees','awardee_contacts','academic_records','organization_records','achievements','spiritual_records','coaching_sessions','networking_records','portfolios','assessments','competencies','mentoring_cases','rule_analyses','development_periods','attendance_sessions','attendance_records','reflection_forms','reflection_responses','facilitators','idp_external_sources','idp_snapshots'];
function out(res,status,body){res.status(status);res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(body))}
function token(req){return String(req.headers.authorization||'').replace(/^Bearer\s+/i,'').trim()}
function headers(t,extra={}){return{apikey:KEY,Authorization:`Bearer ${t}`,'Content-Type':'application/json',...extra}}
async function raw(path,t,options={}){const r=await fetch(PROJECT_URL+path,{...options,headers:{...headers(t),...(options.headers||{})}});const text=await r.text();let body=null;try{body=text?JSON.parse(text):null}catch{body=text}if(!r.ok)throw new Error(body?.message||body?.error||body?.hint||`Supabase ${r.status}`);return{body,headers:r.headers,status:r.status}}
async function q(path,t,options={}){return(await raw(path,t,options)).body}
async function identity(t){const user=await q('/auth/v1/user',t);const rows=await q(`/rest/v1/profiles?id=eq.${encodeURIComponent(user.id)}&select=id,full_name,email,role,is_active`,t);const p=rows?.[0];if(!p?.is_active)throw new Error('Akun belum aktif.');if(!['superadmin','admin'].includes(String(p.role)))throw new Error('System Center hanya tersedia untuk admin.');return{user,profile:p}}
async function countTable(table,t){const r=await raw(`/rest/v1/${table}?select=id&limit=1`,t,{headers:{Prefer:'count=exact'}});const cr=r.headers.get('content-range')||'';const m=cr.match(/\/(\d+|\*)$/);return m&&m[1]!=='*'?Number(m[1]):Array.isArray(r.body)?r.body.length:0}
function noteFor(table){if(table==='academic_records')return'54 record akademik valid. AKD-001 s.d. AKD-007 dikarantina karena Semester=46235 adalah serial tanggal, bukan semester.';if(table==='portfolios')return'3 record portfolio dipertahankan: Bagas, Wahyu, Riskawati. Samsudaris PRT-0NaN dikarantina karena artefak tidak terverifikasi sebagai miliknya.';if(table==='coaching_sessions')return'16 row legacy hanya shell ID/FK dan bukan sesi coaching.';if(table==='organization_records')return'2 dari 18 row Organisasi substantif; 16 shell tidak dimigrasi.';if(table==='achievements')return'19 dari 30 row Prestasi substantif; 11 shell tidak dimigrasi.';if(table==='attendance_sessions'||table==='attendance_records')return'Production dimulai 7 September 2026 tanpa absensi legacy/test.';return null}
async function health(t){const counts={};for(const table of TABLES){try{counts[table]=await countTable(table,t)}catch(e){counts[table]=null}}const reconciliation=Object.entries(EXPECTED).map(([table,expected])=>({table,expected,actual:counts[table],ok:counts[table]===expected,note:noteFor(table)}));return{generatedAt:new Date().toISOString(),source:SOURCE,counts,reconciliation,normalizedParity:reconciliation.every(x=>x.ok),quarantine:{academic:['AKD-001','AKD-002','AKD-003','AKD-004','AKD-005','AKD-006','AKD-007'],portfolio:['PRT-0NaN / AWD-0009']},notes:['IDP individual adalah authority untuk visi hidup/jurusan bila eksplisit; template IDP diperlakukan sebagai data kosong.','Periode PRD-0002 hanya boleh menjadi compatibility row karena Form RFK-0001 mereferensikannya sementara source Periode_Pembinaan kosong.','Placeholder legacy tidak dihitung sebagai transaksi substantif.','Absensi lama/test tidak dibawa ke production.']}}
async function audit(t){try{return await q('/rest/v1/audit_logs?select=id,actor_id,action,table_name,record_id,created_at&order=created_at.desc&limit=100',t)}catch(e){return{unavailable:true,error:e.message,items:[]}}}
async function migration(t){let batches=[],issues=[];try{batches=await q('/rest/v1/migration_batches?select=*&order=started_at.desc&limit=20',t)}catch(e){}try{issues=await q('/rest/v1/migration_issues?select=*&order=created_at.desc&limit=200',t)}catch(e){}return{batches,issues}}
async function backup(t){const data={meta:{app:'ETOS ID Palu',format:'ETOS-JSON-SNAPSHOT-V1',generatedAt:new Date().toISOString(),source:SOURCE},tables:{}};for(const table of TABLES){try{data.tables[table]=await q(`/rest/v1/${table}?select=*`,t)}catch(e){data.tables[table]={_error:e.message}}}return data}
module.exports=async function handler(req,res){if(req.method!=='POST')return out(res,405,{success:false,error:'Method not allowed'});try{const t=token(req);if(!t)return out(res,401,{success:false,error:'Session admin diperlukan.'});await identity(t);const fn=String(req.body?.function||'health');if(fn==='health')return out(res,200,{success:true,data:await health(t)});if(fn==='audit')return out(res,200,{success:true,data:await audit(t)});if(fn==='migration')return out(res,200,{success:true,data:await migration(t)});if(fn==='backup')return out(res,200,{success:true,data:await backup(t)});return out(res,404,{success:false,error:'Fungsi System Center tidak tersedia.'})}catch(e){console.error('[system]',e);return out(res,500,{success:false,error:e.message||String(e)})}}
