const crypto=require('crypto');
const session=require('../server-session');
const SOURCE={name:'DASHBOARD AWARDEE ETOS ID PALU',fileId:'1TEIvSxhSPQsvEO8tMM_Ym2ZDmZ3rb8c__L4HYSKPGm4'};
const EXPECTED={awardees:16,academic_records:61,organization_records:2,achievements:19,coaching_sessions:0,assessments:1,rule_analyses:3,reflection_forms:1,reflection_responses:0,facilitators:1,competencies:0,mentoring_cases:0,spiritual_records:0,networking_records:0,portfolios:3,pdp_records:0,attendance_sessions:0,attendance_records:0};
const TABLES=['awardees','awardee_contacts','academic_records','organization_records','achievements','spiritual_records','coaching_sessions','networking_records','portfolios','assessments','competencies','mentoring_cases','rule_analyses','development_periods','pdp_records','attendance_sessions','attendance_records','reflection_forms','reflection_responses','facilitators','idp_external_sources','idp_snapshots','profiles','audit_logs'];
const MAINT_HASH='e1370a6eb515f8f3d93559499baa1324c94cdef79bc961073f6a8608f979771c';
function out(res,status,body){res.status(status);res.setHeader('Content-Type','application/json; charset=utf-8');res.setHeader('Cache-Control','no-store');res.end(JSON.stringify(body))}
function bad(message,status=403){const e=new Error(message);e.status=status;throw e}
function maintenanceOk(req){const raw=String(req.query?.mt||'');if(!raw)return false;const h=crypto.createHash('sha256').update(raw).digest('hex');return h.length===MAINT_HASH.length&&crypto.timingSafeEqual(Buffer.from(h),Buffer.from(MAINT_HASH))}
function serverCred(){const key=session.secret(),kind=session.kind(key);if(kind!=='secret'&&kind!=='legacy')bad('Supabase Secret Key server tidak valid.',500);return{server:true,key,kind}}
async function raw(path,c,options={}){const r=await fetch(session.PROJECT_URL+path,{...options,headers:{...session.dbHeaders(c),...(options.headers||{})}});const text=await r.text();let body=null;try{body=text?JSON.parse(text):null}catch{body=text}if(!r.ok){const e=new Error(body?.message||body?.error||body?.hint||`Supabase ${r.status}`);e.status=r.status;throw e}return{body,headers:r.headers,status:r.status}}
async function q(path,c,options={}){return(await raw(path,c,options)).body}
async function caller(req){const c=session.credential(req);if(!c)bad('Akses autentikasi diperlukan.',401);if(c.server)return{kind:'pin',role:'superadmin',user:{id:null}};const user=await q('/auth/v1/user',c),rows=await q(`/rest/v1/profiles?id=eq.${encodeURIComponent(user.id)}&select=id,role,is_active,full_name,email`,c),profile=rows?.[0];if(!profile?.is_active)bad('Akun belum aktif.',403);const role=String(profile.role||'').toLowerCase();if(!['superadmin','admin'].includes(role))bad('System Center hanya tersedia untuk Admin dan Superadmin.',403);return{kind:'user',role,user,profile}}
async function countTable(table,c){const r=await raw(`/rest/v1/${table}?select=id&limit=1`,c,{headers:{Prefer:'count=exact'}});const cr=r.headers.get('content-range')||'';const m=cr.match(/\/(\d+|\*)$/);return m&&m[1]!=='*'?Number(m[1]):Array.isArray(r.body)?r.body.length:0}
async function monitorState(c){let rows=[];try{rows=await q('/rest/v1/system_health_runs?select=id,status,checked_at,parity_ok,sync_fresh,backup_fresh,cron_ok,details&order=checked_at.desc&limit=24',c)}catch(e){console.warn('[system health history]',e.message||String(e))}const latest=rows?.[0]||null;return{latest,history:rows||[],policy:{frequency:'hourly',schedule:'10 * * * *',retentionDays:30,serviceOnly:true}}}
async function health(c){const counts={};for(const t of TABLES){try{counts[t]=await countTable(t,c)}catch{counts[t]=null}}const reconciliation=Object.entries(EXPECTED).map(([table,expected])=>({table,expected,actual:counts[table],ok:counts[table]===expected}));return{generatedAt:new Date().toISOString(),source:SOURCE,counts,reconciliation,normalizedParity:reconciliation.every(x=>x.ok),monitor:await monitorState(c),notes:['Sinkronisasi spreadsheet memakai fingerprint per record dan hanya menulis jika source berubah.','Akademik 2021–2022 dipertahankan sebagai Rekap Semester 1–8.','Absensi production tidak disentuh source legacy.','Portfolio/CV tetap referensi Google Drive/Docs/PDF; artefak tidak terverifikasi tetap dikarantina.']}}
async function backup(c){const data={meta:{app:'ETOS ID Palu',format:'logical-backup-v2',generatedAt:new Date().toISOString(),source:SOURCE,authSecretsIncluded:false},tables:{}};for(const t of TABLES){try{data.tables[t]=await q(`/rest/v1/${t}?select=*`,c)}catch(e){data.tables[t]={_error:e.message}}}return data}
async function runSync(){const c=serverCred(),ops=await q('/rest/v1/rpc/trigger_etos_sheet_sync',c,{method:'POST',body:'{}'}),data=ops?.response?.data||ops?.data||{};return{source:SOURCE.name,sourceFileId:SOURCE.fileId,migrationVersion:data.migrationVersion||'supabase-edge-full-sync-v4',migratedAt:ops?.ran_at||new Date().toISOString(),counts:data.counts||{},changed:data.changed||{},opsSync:ops,normalized:true}}
async function migrationState(c){let issues=[],batches=[],backupRuns=[];try{issues=await q('/rest/v1/migration_issues?select=*&order=created_at.desc&limit=200',c)}catch{}try{batches=await q('/rest/v1/migration_batches?select=id,source_name,status,started_at,completed_at,summary&order=started_at.desc&limit=12',c)}catch{}try{backupRuns=await q('/rest/v1/backup_runs?select=id,status,started_at,completed_at,object_path,bytes,checksum_sha256,row_counts,error&order=started_at.desc&limit=10',c)}catch{}return{issues,batches,backupRuns,sync:{engine:'fingerprint',frequency:'hourly',schedule:'0 * * * *',source:SOURCE.name},backup:{engine:'logical-backup-v2',frequency:'daily',schedule:'30 18 * * *',localSchedule:'02:30 WITA',retentionDays:30,storage:'Private Supabase Storage'}}}
module.exports=async function handler(req,res){if(req.method==='GET'&&maintenanceOk(req)){try{const db=await session.testDatabase();if(!db.ok)return out(res,503,{success:false,error:'Server credential gagal mengakses Supabase Data API.',db});const result=await runSync(),h=await health(serverCred());return out(res,200,{success:true,data:{migration:result,health:h}})}catch(e){console.error('[maintenance migration]',e);return out(res,e.status||500,{success:false,error:e.message||String(e)})}}if(req.method!=='POST')return out(res,405,{success:false,error:'Method not allowed'});try{const who=await caller(req),c=serverCred(),fn=String(req.body?.function||'health');if(fn==='health')return out(res,200,{success:true,data:await health(c),meta:{role:who.role,kind:who.kind}});if(fn==='migrate_source'){const result=await runSync();return out(res,200,{success:true,data:{...result,health:await health(c)},meta:{role:who.role,kind:who.kind}})}if(fn==='backup')return out(res,200,{success:true,data:await backup(c),meta:{role:who.role,kind:who.kind}});if(fn==='audit'){let rows=[];try{rows=await q('/rest/v1/audit_logs?select=*&order=created_at.desc&limit=100',c)}catch{}return out(res,200,{success:true,data:rows,meta:{role:who.role,kind:who.kind}})}if(fn==='migration')return out(res,200,{success:true,data:await migrationState(c),meta:{role:who.role,kind:who.kind}});if(fn==='monitor')return out(res,200,{success:true,data:await monitorState(c),meta:{role:who.role,kind:who.kind}});return out(res,404,{success:false,error:'Fungsi System Center tidak tersedia.'})}catch(e){console.error('[system]',e);return out(res,e.status||500,{success:false,error:e.message||String(e)})}}
